/// Project collaboration text for the interface language.
///
/// The application owns the catalog; the graph surface takes this value, so the
/// package stays free of product copy. Chinese and English both come from here,
/// next to the other feature strings.
library;

import 'package:presentation_flutter/presentation_flutter.dart';

/// The graph surface text for one interface language.
GraphViewStrings graphViewStringsFor(String languageCode) =>
    languageCode.startsWith('zh') ? _zh : const GraphViewStrings();

const GraphViewStrings _zh = GraphViewStrings(
  builderRole: '构建者',
  reviewerRole: '审阅者',
  zoomPercentLabel: '缩放 {percent}%',
  projectsTitle: '项目',
  roleFilterLabel: '角色',
  allRoles: '全部角色',
  units: '单元',
  ready: '就绪',
  startable: '可启动',
  blocked: '受阻',
  running: '运行中',
  accepted: '已接受',
  stale: '已过期',
  filterAll: '全部',
  filterFrontier: '前沿',
  filterAnomalies: '需关注',
  zoomIn: '放大',
  zoomOut: '缩小',
  resetView: '重置视图',
  inspectorTooltip: '状态检查器',
  listTooltip: '紧凑列表',
  swimlanesTooltip: '泳道图',
  windowNote: '当前显示 {shown}/{total} 个单元；上方计数覆盖全部单元。',
  emptyWindow: '准备窗口内没有单元',
  emptyFiltered: '没有单元符合当前筛选',
  gateShared: '共享门 · 一次运行',
  gateRuns: '门 · {runs} 次运行',
  cannotStart: '无法启动：{reason}',
  startableNow: '可以启动',
  readyNotStartable: '已就绪，暂不可启动',
  detailsTitle: '详情',
  unitDetailTitle: '单元',
  inspectorTitle: '状态检查器',
  closeDetails: '关闭详情',
  detailEmpty: '选择一个单元，查看它的执行、接受与观测状态、无法启动的原因，以及所属方发布的动作。',
  inspectorEmpty: '选择一个单元，查看它的尝试、访问、事件、错误与证据引用。',
  factExecution: '执行',
  factAcceptance: '接受',
  factObservation: '观测',
  factReady: '依赖',
  factStartable: '启动',
  whyCannotStart: '为什么不能启动',
  affectedUnits: '受影响单元',
  noDependents: '没有声明依赖它的单元',
  highlightAffected: '高亮 {count} 个受影响单元',
  sharedGate: '共享门',
  gateSummary: '{runs} 次运行 · {anchors} 个引用锚点',
  gateOneIdentity: '同一个门：引用锚点不会增加第二次运行。',
  attemptsTitle: '尝试',
  visitsTitle: '访问与汇合',
  eventsTitle: '事件',
  evidenceTitle: '证据',
  noAttempts: '没有尝试记录',
  noVisits: '没有访问记录',
  noEvents: '没有事件记录',
  noEvidence: '没有证据引用',
  factAttempts: '尝试次数',
  factVisits: '访问与汇合',
  factEvents: '事件',
  factEvidence: '证据引用',
  factLastError: '最近错误',
  factLastEvent: '最近事件',
  actionsTitle: '动作',
  noActions: '该单元没有发布动作，只能观测。',
  typedInputs: '输入与产出',
  noTypedRefs: '没有声明类型化结果引用',
  consumes: '消费',
  produces: '产出',
  actionObserve: '观测',
  actionManage: '托管',
  actionTakeover: '接管',
  actionPause: '暂停',
  actionCancel: '取消',
  waitingForReceipt: '等待所属方',
  takeoverTitle: '接管该单元',
  takeoverBody: '范围：该单元及其访问。若仍有旧写入者持有它，所属方会拒绝该请求并在此显示原因。在所属方答复前不会发生任何变化。',
  takeoverConfirm: '请求接管',
  cancel: '取消',
  listStartable: '可启动',
  listReady: '已就绪',
  listBlocked: '受阻',
  unavailableTitle: '项目协作暂不可用',
  unavailableLoading: '正在载入项目图',
  unavailableSource: '项目来源已不可用',
  unavailableBinding: '该构建未绑定项目来源',
  unavailablePreparation: '无法准备项目图',
  unavailableLayout: '无法准备项目布局',
  unavailableUnknown: '项目图暂不可用',
  executionNotStarted: '未开始',
  executionClaimed: '已认领',
  executionRunning: '运行中',
  executionSucceeded: '已成功',
  executionFailed: '已失败',
  executionCancelled: '已取消',
  acceptancePending: '待接受',
  acceptanceReviewing: '审阅中',
  acceptanceAccepted: '已接受',
  acceptanceRejected: '已拒绝',
  acceptanceSuperseded: '已被取代',
  observationFresh: '新鲜',
  observationStale: '已过期',
  observationUnknown: '未知',
  blockerDependencyMissing: '依赖尚未满足',
  blockerResultMissing: '缺少所需结果',
  blockerVisitMissing: '缺少所需访问',
  blockerNotMaterialized: '输入尚未实体化',
  blockerAuthorityMissing: '缺少原始授权',
  blockerRouteUnavailable: '没有可运行的路线',
  blockerBudgetMissing: '预算已用尽',
  blockerCapacityMissing: '没有可用容量',
  blockerConflictingWriter: '仍有其他写入者持有',
  blockerObservationStale: '最近观测已过期',
  blockerManagedByOther: '由其他会话托管',
  blockerPaused: '已暂停',
  blockerUnknown: '所属方报告了未知原因',
  receiptAccepted: '所属方已接受该请求',
  receiptPreviewed: '所属方已生成预览',
  receiptStaleRevision: '计划已变化，请求未应用',
  receiptConflictingWriter: '仍有其他写入者持有该单元',
  receiptAuthorityMissing: '缺少原始授权',
  receiptUnknownNode: '该单元已不在计划中',
  receiptDuplicate: '相同请求正在处理中',
  receiptNoPreview: '没有可提交的预览',
  receiptOriginMismatch: '请求来自未知界面',
  receiptUnavailable: '原生项目服务尚未接入',
  receiptUnknown: '所属方拒绝了该请求',
  insertUnit: '插入单元',
  insertTitle: '插入单元',
  insertUnitRef: '单元引用',
  insertUnitRefHelp: '所属方可解析的受限引用。',
  insertLane: '泳道',
  insertRole: '角色',
  insertNote: '在按预览版本提交之前，不会发生任何变化。',
  insertPreview: '预览影响',
  insertImpactTitle: '预览影响',
  insertImpactNone: '不会移动或重新设门任何现有单元。',
  insertImpactAffected: '将影响 {count} 个单元',
  insertCommit: '提交版本 {revision}',
  insertDiscard: '放弃预览',
  noReceiptYet: '尚未收到任何答复',
  receiptLine: '{message} · 计划 {revision}',
  planRevision: '计划 {revision}',
  attemptQueued: '排队中',
  attemptRunning: '运行中',
  attemptSucceeded: '已成功',
  attemptFailed: '已失败',
  attemptCancelled: '已取消',
  attemptSuperseded: '已被取代',
);
