import {
  FLUTTER_COMPOSITION_INPUTS,
  FAKE_AGENT_SERVICE_INPUTS,
  flutterTests,
  flutterAnalyze,
  defineModule,
} from "../helpers.mjs";

export const FLUTTER_MODULES = Object.freeze([
  defineModule({
      id: "flutter.contract.typed-error-chain",
      kind: "flutter-contract",
      summary: "Generated typed client errors, lossless stdio decoding, and localized recovery",
      inputs: [
        "apps/desktop/lib/src/contracts/generated/client_error.g.dart",
        "apps/desktop/lib/src/platform/native_client/agent_service_stdio_rpc/response_codec.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_runtime_result_policy.dart",
        "apps/desktop/lib/src/application/localization/client_application_strings.dart",
        "apps/desktop/test/client_error_contract_test.dart",
      ],
      command: flutterTests(["test/client_error_contract_test.dart"]),
    }),
  defineModule({
      id: "flutter.contract.client-state",
      kind: "flutter-contract",
      summary: "Generated bounded client-state DTOs over the structured native gateway",
      inputs: [
        "apps/desktop/lib/src/contracts/generated/client_state.g.dart",
        "apps/desktop/lib/src/platform/native_client/native_state_actions.dart",
        "apps/desktop/lib/src/platform/native_client/agent_service.dart",
        "apps/desktop/test/client_state_contract_test.dart",
      ],
      command: flutterTests(["test/client_state_contract_test.dart"]),
    }),
  defineModule({
      id: "flutter.contract.secure-mesh",
      kind: "flutter-contract",
      summary: "Generated bounded Secure Mesh bridge DTOs and typed MethodChannel boundary",
      inputs: [
        "schemas/client_bridge/secure_mesh.json",
        "schemas/client_bridge/manifest.json",
        "tools/scripts/generate-client-bridge-contracts.mjs",
        "tools/templates/client_bridge/secure_mesh_capability_models.dart",
        "tools/templates/client_bridge/secure_mesh_kt_models.dart",
        "tools/templates/client_bridge/secure_mesh_mls_models.dart",
        "tools/templates/client_bridge/secure_mesh_file_sync_models.dart",
        "tools/templates/client_bridge/secure_mesh_approval_models.dart",
        "apps/desktop/lib/src/contracts/generated/secure_mesh.g.dart",
        "apps/desktop/lib/src/platform/secure_mesh/secure_mesh_mobile_bridge.dart",
      ],
      command: flutterTests(["test/secure_mesh_contract_test.dart"]),
    }),
  defineModule({
      id: "flutter.composition.dependencies",
      kind: "flutter-composition",
      summary: "Flutter dependency graph, analyzer options, and locked package composition",
      inputs: FLUTTER_COMPOSITION_INPUTS,
      command: flutterAnalyze(),
    }),
  defineModule({
      id: "flutter.feature.mcp-transfer",
      kind: "flutter-feature",
      summary: "MCP transfer preview, explicit confirmation, and private native execution",
      inputs: [
        "apps/desktop/lib/src/contracts/mcp_adapter.dart",
        "apps/desktop/lib/src/application/features/mcp/controller/mcp_transfer_controller.dart",
        "apps/desktop/lib/src/platform/native_client/native_mcp_actions.dart",
        "apps/desktop/test/mcp_transfer_controller_test.dart",
        "apps/desktop/test/native_mcp_actions_test.dart",
      ],
      command: flutterTests([
        "test/mcp_transfer_controller_test.dart",
        "test/native_mcp_actions_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.catalog-convergence",
      kind: "flutter-feature",
      summary: "Desktop catalog lifecycle, private structured native bridge, bounded state, and visible revision projection",
      inputs: [
        "apps/desktop/lib/src/contracts/catalog_convergence/**",
        "apps/desktop/lib/src/application/features/catalog_convergence/**",
        "apps/desktop/lib/src/application/controller/assembly/client_catalog_convergence_component_assembly.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/catalog_convergence_status_card.dart",
        "apps/desktop/lib/src/platform/native_client/native_catalog_actions.dart",
        "apps/desktop/test/catalog_convergence_controller_test.dart",
        "apps/desktop/test/catalog_convergence_status_card_test.dart",
        "apps/desktop/test/catalog_convergence_architecture_test.dart",
      ],
      command: flutterTests([
        "test/catalog_convergence_controller_test.dart",
        "test/catalog_convergence_status_card_test.dart",
        "test/catalog_convergence_architecture_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agents",
      kind: "flutter-feature",
      summary: "Agent workspace coordination, rendering, and target presentation",
      inputs: [
        "apps/desktop/lib/src/application/features/agents/workspace/**",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_display_names.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_render_adapter.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_workspace_sidebar.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agents_canvas.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agents_toolbar.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/mobile_widgets_page.dart",
        "apps/desktop/lib/src/platform/agent_render_adapter/**",
        "apps/desktop/lib/src/platform/agents/**",
        "apps/desktop/lib/src/contracts/agent_command_runner.dart",
        "apps/desktop/lib/src/contracts/agent_render_adapter_source.dart",
        "apps/desktop/assets/agent-icons/**",
        "apps/desktop/assets/agent-render-adapters/**",
        "apps/desktop/test/agent_application_dependency_boundary_test.dart",
        "apps/desktop/test/agent_render_adapter_test.dart",
      ],
      command: flutterTests([
        "test/agent_application_dependency_boundary_test.dart",
        "test/agent_render_adapter_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agents.workspace.renderer-cache",
      kind: "flutter-feature",
      summary: "Agent workspace render-adapter resolution cache",
      inputs: [
        "apps/desktop/test/agents_workspace/agents_workspace_renderer_cache_test.dart",
        "apps/desktop/test/agents_workspace/support/agents_workspace_test_harness.dart",
      ],
      command: flutterTests([
        "test/agents_workspace/agents_workspace_renderer_cache_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.adaptive-flywheel",
      kind: "flutter-feature",
      summary: "Restored capsule role editor, strategy import, background runtime detection, and workflow diagram",
      inputs: [
        "apps/desktop/lib/src/contracts/generated/strategy.g.dart",
        "apps/desktop/lib/src/contracts/adaptive_flywheel_models.dart",
        "apps/desktop/lib/src/backend/features/agents/services/adaptive_flywheel_service.dart",
        "apps/desktop/lib/src/application/features/agents/adaptive_flywheel/**",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_dialog.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_multi_capsule_section.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_workflow_diagram.dart",
        "apps/desktop/test/adaptive_flywheel_controller_test.dart",
      ],
      command: flutterTests(["test/adaptive_flywheel_controller_test.dart"]),
    }),
  defineModule({
      id: "flutter.feature.agents.workspace.renderer-process-card",
      kind: "flutter-feature",
      summary: "Agent workspace semantic artifacts and structured process cards",
      inputs: [
        "apps/desktop/test/agents_workspace/agents_workspace_renderer_process_card_test.dart",
        "apps/desktop/test/agents_workspace/support/agents_workspace_test_harness.dart",
      ],
      command: flutterTests([
        "test/agents_workspace/agents_workspace_renderer_process_card_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agents.workspace.renderer-collapse",
      kind: "flutter-feature",
      summary: "Agent workspace collapsed metadata, plugins, and subagent output",
      inputs: [
        "apps/desktop/test/agents_workspace/agents_workspace_renderer_collapse_test.dart",
        "apps/desktop/test/agents_workspace/support/agents_workspace_test_harness.dart",
      ],
      command: flutterTests([
        "test/agents_workspace/agents_workspace_renderer_collapse_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agents.workspace.layout",
      kind: "flutter-feature",
      summary: "Agent workspace desktop and mobile layout boundaries",
      inputs: [
        "apps/desktop/test/agents_workspace/agents_workspace_layout_test.dart",
        "apps/desktop/test/agents_workspace/support/agents_workspace_test_harness.dart",
      ],
      command: flutterTests([
        "test/agents_workspace/agents_workspace_layout_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agents.workspace.interaction",
      kind: "flutter-feature",
      summary: "Agent workspace process, composer, and navigation interactions",
      inputs: [
        "apps/desktop/test/agents_workspace/agents_workspace_interaction_test.dart",
        "apps/desktop/test/agents_workspace/support/agents_workspace_test_harness.dart",
      ],
      command: flutterTests([
        "test/agents_workspace/agents_workspace_interaction_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agents.workspace.state",
      kind: "flutter-feature",
      summary: "Agent workspace active-turn, history, and localization state",
      inputs: [
        "apps/desktop/test/agents_workspace/agents_workspace_state_test.dart",
        "apps/desktop/test/agents_workspace/support/agents_workspace_test_harness.dart",
      ],
      command: flutterTests([
        "test/agents_workspace/agents_workspace_state_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations",
      kind: "flutter-feature",
      summary: "Local agent conversation lifecycle, archive, projection, and UI",
      inputs: [
        "apps/desktop/lib/src/application/features/agents/archive/**",
        "apps/desktop/lib/src/application/features/agents/contracts/agent_conversation_gateway.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/agent_conversation_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/agent_conversation_read_only_policy.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_live_projection_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_message_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_mobile_session_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_presentation_signals.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_refresh_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_relay_projection_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_runtime_result_policy.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_selection_store.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/agent_conversation_search_index.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_session_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_session_state_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_working_directory_fallback.dart",
        "apps/desktop/lib/src/application/features/conversations/**",
        "apps/desktop/lib/src/application/features/agents/policy/conversation_refresh_policy.dart",
        "apps/desktop/lib/src/application/features/agents/policy/conversation_session_index.dart",
        "apps/desktop/lib/src/application/composition/agent_conversation_gateway_adapter.dart",
        "apps/desktop/lib/src/backend/features/agents/services/agent_conversation_archive_service.dart",
        "apps/desktop/lib/src/backend/features/agents/services/agent_conversation_service.dart",
        "apps/desktop/lib/src/backend/features/conversations/**",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_composer.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_event_card.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_event_details_builder.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_image_attachments.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_layout_metrics.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_display.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_view.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_parity_disclosure.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_process_card.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_process_operations.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_process_projection.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_runtime_settings.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_session_presentation.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_timeline.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_truncation_notice.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_search_palette.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_workspace.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/global_search_features.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_agent_avatar.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_chrome_tabs.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_contact_list.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_conversation_header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_conversation_switcher.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_details_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_message_group.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_notification_bell.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_participant_flow.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_process_status_row.dart",
        "apps/desktop/lib/src/frontend/features/conversations/**",
        "apps/desktop/lib/src/contracts/agent_conversation_context_projection.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_message.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_message_parser.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_models.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_projection_repository.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_privacy_projection.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_semantic.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_session.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_structured_projection.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_tab_activity.dart",
        "apps/desktop/lib/src/contracts/client_conversation_models.dart",
        "apps/desktop/lib/src/platform/agents/agent_conversation_projection_store.dart",
        "packages/contracts/client/semantic-conversation.schema.json",
        "apps/desktop/test/agent_conversation_archive_component_test.dart",
        "apps/desktop/test/agent_conversation_archive_test.dart",
        "apps/desktop/test/agent_conversation_component_boundary_test.dart",
        "apps/desktop/test/agent_conversation_composer_test.dart",
        "apps/desktop/test/agent_conversation_composer_apple_chrome_test.dart",
        "apps/desktop/test/agent_conversation_event_card_test.dart",
        "apps/desktop/test/agent_conversation_dispatch_test.dart",
        "apps/desktop/test/agent_conversation_event_component_boundary_test.dart",
        "apps/desktop/test/agent_conversation_history_loading_test.dart",
        "apps/desktop/test/agent_conversation_local_read_only_test.dart",
        "apps/desktop/test/agent_conversation_message_display_test.dart",
        "apps/desktop/test/agent_conversation_model_boundary_test.dart",
        "apps/desktop/test/agent_conversation_parity_disclosure_test.dart",
        "apps/desktop/test/agent_conversation_privacy_projection_test.dart",
        "apps/desktop/test/agent_conversation_process_projection_test.dart",
        "apps/desktop/test/agent_conversation_projection_test.dart",
        "apps/desktop/test/agent_conversation_runtime_settings_test.dart",
        "apps/desktop/test/conversation_runtime_result_policy_test.dart",
        "apps/desktop/test/agent_conversation_search_index_test.dart",
        "apps/desktop/test/agent_conversation_search_palette_test.dart",
        "apps/desktop/test/agent_conversation_semantic_test.dart",
        "apps/desktop/test/agent_conversation_send_availability_copy_test.dart",
        "apps/desktop/test/agent_conversation_send_failure_projection_test.dart",
        "apps/desktop/test/agent_conversation_sidebar_test.dart",
        "apps/desktop/test/agent_conversation_tab_activity_test.dart",
        "apps/desktop/test/client_conversation_archive_bindings_test.dart",
        "apps/desktop/test/client_conversation_controller_test.dart",
        "apps/desktop/test/canonical_group_conversation_projection_test.dart",
        "apps/desktop/test/conversation_process_card_apple_chrome_test.dart",
        "apps/desktop/test/conversation_presentation_signals_test.dart",
        "apps/desktop/test/conversation_refresh_policy_test.dart",
        "apps/desktop/test/conversation_session_index_test.dart",
        "apps/desktop/test/fixtures/agent_conversation_service_scenarios.dart",
        "apps/desktop/test/messaging/messaging_chrome_band_test.dart",
        "apps/desktop/test/messaging/messaging_chrome_tabs_test.dart",
        "apps/desktop/test/messaging/messaging_composer_strategy_test.dart",
        "apps/desktop/test/messaging/messaging_contact_list_test.dart",
        "apps/desktop/test/messaging/messaging_conversation_switcher_test.dart",
        "apps/desktop/test/messaging/messaging_details_panel_test.dart",
        "apps/desktop/test/messaging/messaging_image_attachment_test.dart",
        "apps/desktop/test/messaging/messaging_participant_flow_test.dart",
        "apps/desktop/test/messaging/messaging_process_status_row_test.dart",
        "apps/desktop/test/messaging/messaging_workspace_selection_test.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_archive_component_test.dart",
        "test/agent_conversation_archive_test.dart",
        "test/agent_conversation_component_boundary_test.dart",
        "test/agent_conversation_composer_test.dart",
        "test/agent_conversation_composer_apple_chrome_test.dart",
        "test/agent_conversation_event_card_test.dart",
        "test/agent_conversation_dispatch_test.dart",
        "test/agent_conversation_event_component_boundary_test.dart",
        "test/agent_conversation_history_loading_test.dart",
        "test/agent_conversation_local_read_only_test.dart",
        "test/agent_conversation_message_display_test.dart",
        "test/agent_conversation_model_boundary_test.dart",
        "test/agent_conversation_parity_disclosure_test.dart",
        "test/agent_conversation_privacy_projection_test.dart",
        "test/agent_conversation_process_projection_test.dart",
        "test/agent_conversation_projection_test.dart",
        "test/agent_conversation_runtime_settings_test.dart",
        "test/conversation_runtime_result_policy_test.dart",
        "test/agent_conversation_search_index_test.dart",
        "test/agent_conversation_search_palette_test.dart",
        "test/agent_conversation_semantic_test.dart",
        "test/agent_conversation_send_availability_copy_test.dart",
        "test/agent_conversation_send_failure_projection_test.dart",
        "test/agent_conversation_sidebar_test.dart",
        "test/agent_conversation_tab_activity_test.dart",
        "test/client_conversation_archive_bindings_test.dart",
        "test/client_conversation_controller_test.dart",
        "test/canonical_group_conversation_projection_test.dart",
        "test/conversation_process_card_apple_chrome_test.dart",
        "test/conversation_presentation_signals_test.dart",
        "test/conversation_refresh_policy_test.dart",
        "test/conversation_session_index_test.dart",
        "test/messaging/messaging_chrome_band_test.dart",
        "test/messaging/messaging_chrome_tabs_test.dart",
        "test/messaging/messaging_composer_strategy_test.dart",
        "test/messaging/messaging_contact_list_test.dart",
        "test/messaging/messaging_conversation_switcher_test.dart",
        "test/messaging/messaging_details_panel_test.dart",
        "test/messaging/messaging_image_attachment_test.dart",
        "test/messaging/messaging_participant_flow_test.dart",
        "test/messaging/messaging_process_status_row_test.dart",
        "test/messaging/messaging_workspace_selection_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.history-loading",
      kind: "flutter-feature",
      summary: "Native conversation history listing, streaming, and pagination",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/history_loading_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/history_loading_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.filtering",
      kind: "flutter-feature",
      summary: "Visible conversation filtering and provider wrapper projection",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/filtering_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/filtering_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.structured-events",
      kind: "flutter-feature",
      summary: "Structured event normalization, bounds, identity, and redaction",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/structured_event_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/structured_event_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.dispatch-resume",
      kind: "flutter-feature",
      summary: "Conversation dispatch, exact resume, streaming, steer, and cancel",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/dispatch_resume_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/dispatch_resume_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.snapshots",
      kind: "flutter-feature",
      summary: "Conversation snapshot collection and local archive job lifecycle",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/snapshot_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/snapshot_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.follow-up-queue",
      kind: "flutter-feature",
      summary: "Bounded FIFO follow-up turns with exact native-session rebinding",
      inputs: [
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_turn_queue.dart",
        "apps/desktop/test/conversation_turn_queue_test.dart",
      ],
      command: flutterTests([
        "test/conversation_turn_queue_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.archive-selection",
      kind: "flutter-feature",
      summary: "All-conversation and exact-keyword local backup selection dialog",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation_archive_dialog.dart",
        "apps/desktop/test/conversation_archive_dialog_test.dart",
      ],
      command: flutterTests([
        "test/conversation_archive_dialog_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-dispatcher",
      kind: "flutter-feature",
      summary: "Thin message block facade and kind/layout presenter dispatch",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/dispatcher.dart",
        "apps/desktop/test/agent_conversation_message_blocks/dispatcher_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/dispatcher_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-disclosures",
      kind: "flutter-feature",
      summary: "Message body splitting, recommended-plugin details, metadata details, and event detail rendering",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/disclosures.dart",
        "apps/desktop/test/agent_conversation_message_blocks/disclosures_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/disclosures_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-roles",
      kind: "flutter-feature",
      summary: "User bubble and assistant document/bubble role presentations",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/role_blocks.dart",
        "apps/desktop/test/agent_conversation_message_blocks/role_blocks_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/role_blocks_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-subagent",
      kind: "flutter-feature",
      summary: "Subagent preview, expansion state, and child message rendering",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/subagent.dart",
        "apps/desktop/test/agent_conversation_message_blocks/subagent_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/subagent_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-composition",
      kind: "flutter-feature",
      summary: "Thin pane facade with message, send-gate, header, and composer composition",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/composition.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_controls.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_presentation.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_recent_sessions.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_workspace.dart",
        "apps/desktop/test/agent_conversation_recent_sessions_test.dart",
        "apps/desktop/test/agent_conversation_pane/composition_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_recent_sessions_test.dart",
        "test/agent_conversation_pane/composition_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-actions",
      kind: "flutter-feature",
      summary: "Pane empty selection, new, archive, and mobile composer surfaces",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/actions.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_controls.dart",
        "apps/desktop/test/agent_conversation_pane/actions_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_pane/actions_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-resize",
      kind: "flutter-feature",
      summary: "Conversation history split bounds and reusable edge drag handling",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/resize.dart",
        "apps/desktop/test/agent_conversation_pane/resize_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_pane/resize_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-header",
      kind: "flutter-feature",
      summary: "Conversation identity, parity, orchestration, OpenCode status, and sidebar controls",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_connection_chips.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_controls.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_presentation.dart",
        "apps/desktop/test/agent_conversation_pane/header_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_pane/header_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.history-session",
      kind: "flutter-feature",
      summary: "Conversation history session models, search, header, list, and panel composition",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_list.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_models.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_search.dart",
        "apps/desktop/test/history_session_component_boundary_test.dart",
        "apps/desktop/test/history_session_panel_test.dart",
      ],
      command: flutterTests([
        "test/history_session_component_boundary_test.dart",
        "test/history_session_panel_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage",
      kind: "flutter-feature",
      summary: "Local token usage aggregation, time windows, charts, and summaries",
      inputs: [
        "apps/desktop/lib/src/application/features/agents/contracts/agent_usage_gateway.dart",
        "apps/desktop/lib/src/application/features/agents/controller/agent_usage_daily_cache.dart",
        "apps/desktop/lib/src/application/features/agents/controller/agent_usage_controller.dart",
        "apps/desktop/lib/src/application/composition/agent_usage_gateway_adapter.dart",
        "apps/desktop/lib/src/backend/features/agents/services/agent_usage_service.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_summary_widgets.dart",
        "apps/desktop/lib/src/contracts/agent_usage_models.dart",
        "apps/desktop/test/agent_usage_daily_cache_test.dart",
        "apps/desktop/test/agent_usage_controller_test.dart",
        "apps/desktop/test/agent_usage_refresh_test.dart",
        "apps/desktop/test/agent_usage_service_test.dart",
        "apps/desktop/test/agent_usage_summary_widgets_test.dart",
        "apps/desktop/test/client_agent_usage_facade_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_daily_cache_test.dart",
        "test/agent_usage_controller_test.dart",
        "test/agent_usage_refresh_test.dart",
        "test/agent_usage_service_test.dart",
        "test/agent_usage_summary_widgets_test.dart",
        "test/client_agent_usage_facade_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.window-control",
      kind: "flutter-feature",
      summary: "Selectable 1-to-90-day token usage window control",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_window_control.dart",
        "apps/desktop/test/agent_usage_window_control_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_window_control_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.formatters",
      kind: "flutter-feature",
      summary: "Bounded token, percentage, and timeline-label formatting",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_formatters.dart",
        "apps/desktop/test/agent_usage_formatters_test.dart",
      ],
      command: flutterTests(["test/agent_usage_formatters_test.dart"]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.timeline-boundary",
      kind: "flutter-feature",
      summary: "Thin timeline facade and one-way normal-library boundaries",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline_data.dart",
        "apps/desktop/test/agent_usage_component_boundary_test.dart",
      ],
      command: flutterTests(["test/agent_usage_component_boundary_test.dart"]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.timeline-models",
      kind: "flutter-feature",
      summary: "Timeline grouping, snapshot, series, and aggregate value models",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline/agent_usage_timeline_models.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_timeline_models_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_timeline/agent_usage_timeline_models_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.timeline-builder",
      kind: "flutter-feature",
      summary: "Thirty-day agent/model bucket aggregation and top-series selection",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline/agent_usage_timeline_builder.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_timeline_builder_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_timeline/agent_usage_timeline_builder_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.source-parser",
      kind: "flutter-feature",
      summary: "Usage-source JSON, daily-shape, date, and numeric token parsing",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline/agent_usage_source_parser.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_source_parser_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_timeline/agent_usage_source_parser_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.token-breakdown",
      kind: "flutter-feature",
      summary: "Exact token components and normalized per-model merge",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline/agent_usage_token_breakdown.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_token_breakdown_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_timeline/agent_usage_token_breakdown_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.display-names",
      kind: "flutter-feature",
      summary: "Agent and model alias normalization for usage presentation",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline/agent_usage_display_names.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_display_names_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_timeline/agent_usage_display_names_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.series-color",
      kind: "flutter-feature",
      summary: "Known and stable fallback color assignment for usage series",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline/agent_usage_series_color_policy.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_series_color_policy_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_timeline/agent_usage_series_color_policy_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.visibility",
      kind: "flutter-feature",
      summary: "Detected-agent and meaningful-history visibility policy",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_timeline/agent_usage_visibility_policy.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_visibility_policy_test.dart",
      ],
      command: flutterTests([
        "test/agent_usage_timeline/agent_usage_visibility_policy_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.visualization",
      kind: "flutter-feature",
      summary: "Token usage panel, chart geometry, controls, painter, and overview",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_panel_widgets.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_chart_controls.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_chart_geometry.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_wave_chart_painter.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_wave_overview.dart",
        "apps/desktop/test/agent_usage_chart_geometry_test.dart",
        "apps/desktop/test/agent_usage_charts_test.dart",
        "apps/desktop/test/agent_usage_visualization_test.dart",
        "apps/desktop/test/fixtures/agent_usage_panel_scenarios.dart",
      ],
      command: flutterTests([
        "test/agent_usage_chart_geometry_test.dart",
        "test/agent_usage_charts_test.dart",
        "test/agent_usage_visualization_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.scenario.formatting",
      kind: "flutter-feature",
      summary: "Usage totals, compact number formatting, and grouping controls",
      inputs: [
        "apps/desktop/test/fixtures/agent_usage_panel/formatting_scenarios.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_agent_service_fakes.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_panel_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_usage_panel/formatting_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.scenario.timeline",
      kind: "flutter-feature",
      summary: "Daily usage timeline, snapshot semantics, and interactive tooltip",
      inputs: [
        "apps/desktop/test/fixtures/agent_usage_panel/timeline_scenarios.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_agent_service_fakes.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_panel_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_usage_panel/timeline_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.scenario.model-share",
      kind: "flutter-feature",
      summary: "Stable model ranking, formal naming, denominator, and share bars",
      inputs: [
        "apps/desktop/test/fixtures/agent_usage_panel/model_share_scenarios.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_agent_service_fakes.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_panel_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_usage_panel/model_share_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.scenario.polling",
      kind: "flutter-feature",
      summary: "Bounded local token polling without presentation status churn",
      inputs: [
        "apps/desktop/test/fixtures/agent_usage_panel/polling_scenarios.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_agent_service_fakes.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_panel_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_usage_panel/polling_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-usage.scenario.cache",
      kind: "flutter-feature",
      summary: "Retained usage cache freshness and unload-safe refresh coalescing",
      inputs: [
        "apps/desktop/test/fixtures/agent_usage_panel/cache_scenarios.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_agent_service_fakes.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_usage_panel/cache_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.adapter-plugin-management",
      kind: "flutter-feature",
      summary: "Canonical agent-adapter inventory, confirmed managed-bridge lifecycle, and desktop plugin destination",
      inputs: [
        "apps/desktop/lib/src/application/features/plugin_management/**",
        "apps/desktop/lib/src/application/controller/assembly/client_plugin_management_component_assembly.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/**",
        "apps/desktop/lib/src/contracts/presentation/semantic_destination.dart",
        "apps/desktop/lib/src/application/features/navigation/semantic_destination_catalog.dart",
        "apps/desktop/lib/src/frontend/shell/client_chrome_features.dart",
        "apps/desktop/lib/src/frontend/shell/client_shell.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/destinations/plugin_management_destination.dart",
        "apps/desktop/test/adapter_plugin_controller_test.dart",
        "apps/desktop/test/layout/semantic_destination_catalog_test.dart",
      ],
      command: flutterTests([
        "test/adapter_plugin_controller_test.dart",
        "test/optional_collaboration_settings_boundary_test.dart",
        "test/layout/semantic_destination_catalog_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_bundle_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration",
      kind: "flutter-feature",
      summary: "Disabled-by-default, explicit-confirmation optional collaboration lifecycle",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_controller_context.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_workflow_action_context.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_workflow_controller.dart",
        "apps/desktop/lib/src/backend/features/settings/services/optional_collaboration_service.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_gateway.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_catalog_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_kind.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_parsing.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_plan_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_result_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_catalog_action.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings_action_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings_policy.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_status_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_workflow_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_workflow_plan_review.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_workflow_sections.dart",
        "apps/desktop/test/optional_collaboration_controller_test.dart",
        "apps/desktop/test/optional_collaboration_models_test.dart",
        "apps/desktop/test/optional_collaboration_service_test.dart",
        "apps/desktop/test/optional_collaboration_settings_boundary_test.dart",
        "apps/desktop/test/optional_collaboration_settings_test.dart",
        "apps/desktop/test/optional_collaboration_workflow_controller_test.dart",
        "apps/desktop/test/optional_collaboration_workflow_models_test.dart",
        "apps/desktop/test/optional_collaboration_workflow_service_test.dart",
        "apps/desktop/test/support/optional_collaboration_test_fixtures.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_controller_test.dart",
        "test/optional_collaboration_local_server_parser_test.dart",
        "test/optional_collaboration_models_test.dart",
        "test/optional_collaboration_service_test.dart",
        "test/optional_collaboration_settings_boundary_test.dart",
        "test/optional_collaboration_settings_test.dart",
        "test/optional_collaboration_workflow_controller_test.dart",
        "test/optional_collaboration_workflow_models_test.dart",
        "test/optional_collaboration_workflow_service_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.runner-trust",
      kind: "flutter-feature",
      summary: "Direct-user runner trust import and removal bound to key, source repository, fixed identity, and fingerprint",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_runner_trust_actions.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_model_parsing.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_runner_trust_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_runner_trust_section.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_controller_test.dart",
        "test/optional_collaboration_models_test.dart",
        "test/optional_collaboration_service_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.install-lifecycle",
      kind: "flutter-feature",
      summary: "Explicit enablement, exact-commit install planning, plan cancellation, application, disablement, and uninstall",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_install_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_lifecycle_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_plugin_binding.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_install_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_plugin_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_install_plan_review.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_install_section.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_lifecycle_sections.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_controller_test.dart",
        "test/optional_collaboration_models_test.dart",
        "test/optional_collaboration_service_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.local-server-assembly",
      kind: "flutter-feature",
      summary: "Typed local assembly, digest-bound signed-runner deployment, verified runtime lifecycle, and direct approvals",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_local_assembly_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_server_runtime_actions.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_assembly_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_identity.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_lifecycle_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_parser.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_parsing.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_state.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_local_assembly_section.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_local_server_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_local_server_section.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_workflow_choice_subtitle.dart",
        "apps/desktop/test/optional_collaboration_local_server_models_test.dart",
        "apps/desktop/test/optional_collaboration_local_server_parser_test.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_local_server_models_test.dart",
        "test/optional_collaboration_local_server_parser_test.dart",
        "test/optional_collaboration_workflow_models_test.dart",
        "test/optional_collaboration_workflow_service_test.dart",
        "test/optional_collaboration_workflow_controller_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.mcp-install",
      kind: "flutter-feature",
      summary: "Agent-scoped MCP installation planning, local destination binding, per-file approval, cancellation, and apply",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_mcp_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_workflow_validation.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_mcp_workflow_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_agent_destination_editor.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_mcp_install_section.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_workflow_models_test.dart",
        "test/optional_collaboration_workflow_service_test.dart",
        "test/optional_collaboration_workflow_controller_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay",
      kind: "flutter-feature",
      summary: "Mobile relay, local pairing, and Secure Mesh UI",
      inputs: [
        "apps/desktop/lib/src/application/features/mobile_relay/controller/mobile_home_layout_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/mobile_relay_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/policy/**",
        "apps/desktop/lib/src/application/composition/mobile_home_layout_repository_adapter.dart",
        "apps/desktop/lib/src/application/composition/mobile_relay_client_adapter.dart",
        "apps/desktop/lib/src/backend/features/mobile_relay/**",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_add_agent.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agent_list.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agent_list_items.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agent_nav_icon.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agents_empty_state.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agents_home.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_desktop_agent_list.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_home_entry_ordering.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_local_agent.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_surface_gestures.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_swipe_pin_action.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/secure_mesh_approval_card.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/secure_mesh_capability_card.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/secure_mesh_file_sync_card.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/shell_pair_device_dialog.dart",
        "apps/desktop/lib/src/platform/mobile_relay/**",
        "apps/desktop/lib/src/contracts/mobile_home_layout.dart",
        "apps/desktop/lib/src/contracts/mobile_home_layout_repository.dart",
        "apps/desktop/lib/src/contracts/mobile_pairing_presentation.dart",
        "apps/desktop/lib/src/contracts/mobile_relay/**",
        "apps/desktop/lib/src/contracts/mobile_relay_control.dart",
        "apps/desktop/lib/src/contracts/generated/secure_mesh.g.dart",
        "apps/desktop/test/mobile_agents_home_boundary_test.dart",
        "apps/desktop/test/mobile_agent_list_component_boundary_test.dart",
        "apps/desktop/test/mobile_home_entry_ordering_test.dart",
        "apps/desktop/test/mobile_home_layout_controller_test.dart",
        "apps/desktop/test/mobile_pairing_policy_test.dart",
        "apps/desktop/test/mobile_relay_component_boundary_test.dart",
        "apps/desktop/test/mobile_relay_controller_test.dart",
        "apps/desktop/test/mobile_relay_station_validation_test.dart",
        "apps/desktop/test/mobile_relay_models_boundary_test.dart",
        "apps/desktop/test/mobile_relay_operations_test.dart",
        "apps/desktop/test/mobile_relay_secure_mesh_operations_test.dart",
        "apps/desktop/test/mobile_relay_service_test.dart",
        "apps/desktop/test/secure_mesh_capability_service_test.dart",
        "apps/desktop/test/secure_mesh_panel_test.dart",
        "apps/desktop/test/support/fake_mobile_relay_dispatch.dart",
      ],
      command: flutterTests([
        "test/mobile_agents_home_boundary_test.dart",
        "test/mobile_agent_list_component_boundary_test.dart",
        "test/mobile_home_entry_ordering_test.dart",
        "test/mobile_home_layout_controller_test.dart",
        "test/mobile_pairing_policy_test.dart",
        "test/mobile_relay_component_boundary_test.dart",
        "test/mobile_relay_controller_test.dart",
        "test/mobile_relay_station_validation_test.dart",
        "test/mobile_relay_models_boundary_test.dart",
        "test/mobile_relay_operations_test.dart",
        "test/mobile_relay_secure_mesh_operations_test.dart",
        "test/mobile_relay_service_test.dart",
        "test/secure_mesh_capability_service_test.dart",
        "test/secure_mesh_panel_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.configuration",
      kind: "flutter-feature",
      summary: "Local mobile layout persistence and station configuration",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/configuration_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/configuration_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.pairing",
      kind: "flutter-feature",
      summary: "Pairing projection, reset, station selection, sync, and Secure Mesh operations",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/pairing_scenarios.dart",
        "apps/desktop/test/fixtures/mobile_relay/config_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/pairing_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.android-bridge",
      kind: "flutter-feature",
      summary: "Android Secure Mesh status and app-private runtime receipt bridge",
      inputs: [
        "apps/desktop/android/app/src/main/kotlin/land/lico/licoup/SecureMeshAndroidAtomicRecordWriter.kt",
        "apps/desktop/android/app/src/main/kotlin/land/lico/licoup/SecureMeshAndroidNativeDispatchQueue.kt",
        "apps/desktop/test/fixtures/mobile_relay/android_bridge_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/android_bridge_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.relay-poll",
      kind: "flutter-feature",
      summary: "Relay command binding, completion validation, and redacted failures",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/relay_poll_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/relay_poll_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.session-list",
      kind: "flutter-feature",
      summary: "Native session projection, deduplication, paging, and payload bounds",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/session_list_scenarios.dart",
        "apps/desktop/test/fixtures/mobile_relay/session_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/session_list_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.ios-bridge",
      kind: "flutter-feature",
      summary: "iOS Secure Mesh status and native JSON method-channel bridge",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/ios_bridge_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/ios_bridge_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-composition",
      kind: "flutter-feature",
      summary: "Thin Mobile Relay panel facade, platform routing, and Secure Mesh card composition",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/composition.dart",
        "apps/desktop/test/mobile_relay_panel/composition_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/composition_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-pairing",
      kind: "flutter-feature",
      summary: "Explicit station, pairing status, one-time code, and copy presentation",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/pairing.dart",
        "apps/desktop/test/mobile_relay_panel/pairing_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/pairing_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-qr",
      kind: "flutter-feature",
      summary: "Pairing invite QR rendering and configured-station generation gate",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/qr.dart",
        "apps/desktop/test/mobile_relay_panel/qr_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/qr_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-scan",
      kind: "flutter-feature",
      summary: "Mobile pairing scan prompt and platform-native scan affordance",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/scan.dart",
        "apps/desktop/test/mobile_relay_panel/scan_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/scan_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-trust",
      kind: "flutter-feature",
      summary: "Device trust state, fingerprints, safety number, and verification QR",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/trust.dart",
        "apps/desktop/test/mobile_relay_panel/trust_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/trust_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.secure-mesh-controller",
      kind: "flutter-feature",
      summary: "Secure Mesh status, approval, protocol, file, and skill controller composition",
      inputs: [
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_approval_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_controller_support.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_file_transfer_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_protocol_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_skill_transfer_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_status_controller.dart",
        "apps/desktop/test/secure_mesh_component_boundary_test.dart",
        "apps/desktop/test/secure_mesh_component_controllers_test.dart",
        "apps/desktop/test/secure_mesh_controller_test.dart",
      ],
      command: flutterTests([
        "test/secure_mesh_component_boundary_test.dart",
        "test/secure_mesh_component_controllers_test.dart",
        "test/secure_mesh_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.settings",
      kind: "flutter-feature",
      summary: "Settings shell, appearance, updates, directories, and log export",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/client_log_export_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/client_update_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/directory_path_controller.dart",
        "apps/desktop/lib/src/contracts/client_log_export.dart",
        "apps/desktop/lib/src/contracts/client_update_gateway.dart",
        "apps/desktop/lib/src/contracts/directory_opener.dart",
        "apps/desktop/lib/src/backend/features/settings/services/client_update_service.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/archived_conversations_settings_section.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/client_update_settings_card.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/layout_profile_selector.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/settings_log_export_tile.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/settings_panel.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/settings_panel_widgets.dart",
        "apps/desktop/lib/src/platform/appearance/**",
        "apps/desktop/lib/src/platform/presentation/**",
        "apps/desktop/lib/src/platform/runtime_platform_bridge.dart",
        "apps/desktop/lib/src/contracts/appearance/**",
        "apps/desktop/lib/src/contracts/client_update_models.dart",
        "apps/desktop/lib/src/contracts/locale_preferences.dart",
        "apps/desktop/assets/appearance-presets/**",
        "apps/desktop/assets/provider-icons/**",
        "apps/desktop/test/appearance_preset_catalog_service_test.dart",
        "apps/desktop/test/archived_conversations_settings_section_test.dart",
        "apps/desktop/test/client_log_export_controller_test.dart",
        "apps/desktop/test/client_log_export_service_test.dart",
        "apps/desktop/test/client_update_controller_test.dart",
        "apps/desktop/test/client_update_service_test.dart",
        "apps/desktop/test/directory_path_controller_test.dart",
        "apps/desktop/test/settings_component_boundary_test.dart",
        "apps/desktop/test/settings_panel_test.dart",
      ],
      command: flutterTests([
        "test/appearance_preset_catalog_service_test.dart",
        "test/archived_conversations_settings_section_test.dart",
        "test/client_log_export_controller_test.dart",
        "test/client_log_export_service_test.dart",
        "test/client_update_controller_test.dart",
        "test/client_update_service_test.dart",
        "test/directory_path_controller_test.dart",
        "test/settings_component_boundary_test.dart",
        "test/settings_panel_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.skill-hub",
      kind: "flutter-feature",
      summary: "Skill Hub catalog, compatibility, preferences, and UI",
      inputs: [
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_hub_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_hub_status.dart",
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_operation_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/models/skill_agent_compatibility.dart",
        "apps/desktop/lib/src/application/features/skill_hub/models/skill_category_catalog.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/local_skill_hub_catalog_source.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/skill_hub_skill_catalog.dart",
        "apps/desktop/lib/src/backend/features/skill_hub/**",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel_card_support.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel_catalog.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel_icon_picker.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel_widgets.dart",
        "apps/desktop/lib/src/platform/skill_hub/**",
        "apps/desktop/lib/src/contracts/skill_hub.dart",
        "apps/desktop/lib/src/contracts/skill_hub_preferences.dart",
        "apps/desktop/assets/skill-category-icons/**",
        "apps/desktop/test/skill_agent_compatibility_test.dart",
        "apps/desktop/test/skill_category_catalog_test.dart",
        "apps/desktop/test/skill_hub_component_boundary_test.dart",
        "apps/desktop/test/skill_hub_controller_test.dart",
        "apps/desktop/test/skill_hub_invocation_counts_test.dart",
        "apps/desktop/test/skill_hub_panel_test.dart",
        "apps/desktop/test/skill_hub_skill_catalog_test.dart",
      ],
      command: flutterTests([
        "test/skill_agent_compatibility_test.dart",
        "test/skill_category_catalog_test.dart",
        "test/skill_hub_component_boundary_test.dart",
        "test/skill_hub_controller_test.dart",
        "test/skill_hub_invocation_counts_test.dart",
        "test/skill_hub_panel_test.dart",
        "test/skill_hub_skill_catalog_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.skill-hub.delete",
      kind: "flutter-feature",
      summary: "Explicit multi-agent skill deletion controller and service",
      inputs: [
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_delete_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/skill_delete_service.dart",
        "apps/desktop/lib/src/contracts/skill_delete.dart",
        "apps/desktop/test/skill_delete_controller_test.dart",
        "apps/desktop/test/skill_delete_service_test.dart",
      ],
      command: flutterTests([
        "test/skill_delete_controller_test.dart",
        "test/skill_delete_service_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.skill-hub.usage",
      kind: "flutter-feature",
      summary: "Time-windowed reports over runtime-collected local skill invocation aggregates",
      inputs: [
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_usage_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/skill_usage_service.dart",
        "apps/desktop/lib/src/contracts/skill_usage.dart",
        "apps/desktop/test/skill_usage_controller_test.dart",
        "apps/desktop/test/skill_usage_service_test.dart",
      ],
      command: flutterTests([
        "test/skill_usage_controller_test.dart",
        "test/skill_usage_service_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.targets",
      kind: "flutter-feature",
      summary: "Target discovery, ordering, manual entry, and cards",
      inputs: [
        "apps/desktop/lib/src/application/features/targets/**",
        "apps/desktop/lib/src/frontend/features/targets/**",
        "apps/desktop/lib/src/contracts/target_candidate.dart",
        "apps/desktop/lib/src/contracts/target_management.dart",
        "apps/desktop/test/manual_target_dialog_test.dart",
        "apps/desktop/test/scanned_targets_incremental_scan_test.dart",
        "apps/desktop/test/target_controller_test.dart",
        "apps/desktop/test/target_candidate_conversation_test.dart",
        "apps/desktop/test/target_card_test.dart",
      ],
      command: flutterTests([
        "test/manual_target_dialog_test.dart",
        "test/scanned_targets_incremental_scan_test.dart",
        "test/target_controller_test.dart",
        "test/target_candidate_conversation_test.dart",
        "test/target_card_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layer.contracts",
      kind: "flutter-layer",
      summary: "Generated and cross-platform Secure Mesh contract projections",
      inputs: [
        "apps/desktop/lib/src/contracts/generated/**",
        "apps/desktop/lib/src/contracts/target_candidate.dart",
        "apps/desktop/test/fixtures/secure_mesh_capability_projection.dart",
        "apps/desktop/test/secure_mesh_kt_models_test.dart",
        "apps/desktop/test/secure_mesh_mls_models_test.dart",
        "apps/desktop/test/target_candidate_conversation_test.dart",
      ],
      command: flutterTests([
        "test/secure_mesh_kt_models_test.dart",
        "test/secure_mesh_mls_models_test.dart",
        "test/target_candidate_conversation_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layer.layout",
      kind: "flutter-layer",
      summary: "Layout registry, profiles, destination ports, and scoped state",
      inputs: [
        "apps/desktop/lib/src/application/features/layout/**",
        "apps/desktop/lib/src/application/composition/built_in_layout_composition.dart",
        "apps/desktop/lib/src/contracts/presentation/**",
        "apps/desktop/lib/src/frontend/layout/layout_agents_strategy.dart",
        "apps/desktop/lib/src/frontend/layout/layout_chrome_features.dart",
        "apps/desktop/lib/src/frontend/layout/layout_chrome_port.dart",
        "apps/desktop/lib/src/frontend/layout/layout_component_kit.dart",
        "apps/desktop/lib/src/frontend/layout/layout_definition.dart",
        "apps/desktop/lib/src/frontend/layout/layout_destination_port_mount.dart",
        "apps/desktop/lib/src/frontend/layout/layout_destination_presentation.dart",
        "apps/desktop/lib/src/frontend/layout/layout_focus_coordinator.dart",
        "apps/desktop/lib/src/frontend/layout/layout_host.dart",
        "apps/desktop/lib/src/frontend/layout/layout_palette.dart",
        "apps/desktop/lib/src/frontend/layout/layout_registry.dart",
        "apps/desktop/lib/src/frontend/layout/layout_scope.dart",
        "apps/desktop/lib/src/frontend/layout/layout_surface_bundle.dart",
        "apps/desktop/lib/src/frontend/layout/layout_visual_tokens.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/messaging/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/mobile/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/components/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/destinations/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/preview/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/tokens/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/dashboard_desktop.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_desktop_shell.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_folder_sidebar.dart",
        "apps/desktop/test/layout/fixtures/**",
        "apps/desktop/test/layout/production_baseline/**",
        "apps/desktop/test/layout/profiles/messaging/**",
        "apps/desktop/test/layout/profiles/dashboard/mobile/**",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_bundle_test.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_golden_test.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_test_harness.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_widget_test.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_folder_sidebar_test.dart",
        "apps/desktop/test/layout/built_in_layout_composition_test.dart",
        "apps/desktop/test/layout/layout_agents_strategy_test.dart",
        "apps/desktop/test/layout/layout_catalog_test.dart",
        "apps/desktop/test/layout/layout_catalog_test_fixtures.dart",
        "apps/desktop/test/layout/layout_chrome_port_test.dart",
        "apps/desktop/test/layout/layout_destination_port_contract_test.dart",
        "apps/desktop/test/layout/layout_destination_port_mount_test.dart",
        "apps/desktop/test/layout/layout_destination_presentation_test.dart",
        "apps/desktop/test/layout/layout_host_fixture_test.dart",
        "apps/desktop/test/layout/layout_host_test_fixtures.dart",
        "apps/desktop/test/layout/layout_manager_test.dart",
        "apps/desktop/test/layout/layout_palette_test.dart",
        "apps/desktop/test/layout/layout_profile_contract_test.dart",
        "apps/desktop/test/layout/layout_scoped_state_fixture_test.dart",
        "apps/desktop/test/layout/layout_state_store_test.dart",
        "apps/desktop/test/layout/presentation_preferences_repository_test.dart",
        "apps/desktop/test/layout/semantic_destination_catalog_test.dart",
        "apps/desktop/test/layout_profile_selector_test.dart",
        "apps/desktop/test/client_android_orientation_test.dart",
      ],
      command: flutterTests([
        "test/layout/built_in_layout_composition_test.dart",
        "test/layout/layout_agents_strategy_test.dart",
        "test/layout/layout_catalog_test.dart",
        "test/layout/layout_chrome_port_test.dart",
        "test/layout/layout_destination_port_contract_test.dart",
        "test/layout/layout_destination_port_mount_test.dart",
        "test/layout/layout_destination_presentation_test.dart",
        "test/layout/layout_manager_test.dart",
        "test/layout/layout_palette_test.dart",
        "test/layout/layout_profile_contract_test.dart",
        "test/layout/layout_state_store_test.dart",
        "test/layout/layout_host_fixture_test.dart",
        "test/layout/layout_scoped_state_fixture_test.dart",
        "test/layout/presentation_preferences_repository_test.dart",
        "test/layout/profiles/messaging/desktop/messaging_desktop_bundle_test.dart",
        "test/layout/profiles/messaging/desktop/messaging_desktop_shell_test.dart",
        "test/layout/profiles/messaging/mobile/messaging_mobile_bundle_test.dart",
        "test/layout/profiles/messaging/mobile/messaging_mobile_shell_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_bundle_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_golden_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_widget_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_folder_sidebar_test.dart",
        "test/layout/production_baseline/production_layout_baseline_test.dart",
        "test/layout/semantic_destination_catalog_test.dart",
        "test/layout_profile_selector_test.dart",
        "test/client_android_orientation_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layout.dashboard-desktop-chrome.composition",
      kind: "flutter-layer",
      summary: "Dashboard desktop chrome facade and notes-style shell composition",
      inputs: [
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_desktop_chrome.dart",
      ],
      command: flutterTests([
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_widget_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layout.dashboard-desktop-chrome.folder-sidebar",
      kind: "flutter-layer",
      summary: "Notes-style folder sidebar: six destinations, house selection rule, embedded global search",
      inputs: [
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_folder_sidebar.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_folder_sidebar_test.dart",
      ],
      command: flutterTests([
        "test/layout/profiles/dashboard/desktop/dashboard_folder_sidebar_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layout.dashboard-desktop-chrome.search",
      kind: "flutter-layer",
      summary: "Dashboard global section search, aliases, focus, and keyboard submission",
      inputs: [
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_desktop_search.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_search_test.dart",
      ],
      command: flutterTests([
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_search_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.facade",
      kind: "flutter-controller",
      summary: "Thin ClientController and focused runtime facade delegation",
      inputs: [
        "apps/desktop/lib/src/application/controller/client_controller.dart",
        "apps/desktop/lib/src/application/controller/client_agent_usage_facade.dart",
        "apps/desktop/lib/src/application/controller/client_conversation_archive_bindings.dart",
        "apps/desktop/lib/src/application/controller/client_conversation_facade.dart",
        "apps/desktop/lib/src/application/controller/client_lifecycle_facade.dart",
        "apps/desktop/lib/src/application/controller/client_maintenance_facade.dart",
        "apps/desktop/lib/src/application/controller/client_mobile_relay_facade.dart",
        "apps/desktop/lib/src/application/controller/client_navigation_facade.dart",
        "apps/desktop/lib/src/application/controller/client_presentation_facade.dart",
        "apps/desktop/lib/src/application/controller/client_routing_facade.dart",
        "apps/desktop/lib/src/application/controller/client_skill_hub_facade.dart",
        "apps/desktop/lib/src/application/controller/client_target_facade.dart",
        "apps/desktop/test/client_controller_facade_boundary_test.dart",
        "apps/desktop/test/client_controller_runtime_facades_test.dart",
        "apps/desktop/test/client_controller_construction_test.dart",
      ],
      command: flutterTests([
        "test/client_controller_facade_boundary_test.dart",
        "test/client_controller_runtime_facades_test.dart",
        "test/client_controller_construction_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.boundary",
      kind: "flutter-controller",
      summary: "Root component assembly and independent factory boundaries",
      inputs: [
        "apps/desktop/lib/src/application/controller/client_component_assembly.dart",
        "apps/desktop/lib/src/application/controller/assembly/client_component_assembly_contracts.dart",
        "apps/desktop/test/client_component_assembly_leaves_test.dart",
        "apps/desktop/test/client_controller_component_boundary_test.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/client_controller_component_boundary_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.lifecycle",
      kind: "flutter-controller",
      summary: "Authoritative client lifecycle state machine and immutable projection",
      inputs: [
        "apps/desktop/lib/src/application/controller/client_lifecycle_coordinator.dart",
        "apps/desktop/test/client_lifecycle_coordinator_test.dart",
      ],
      command: flutterTests(["test/client_lifecycle_coordinator_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.assembly.conversation",
      kind: "flutter-controller",
      summary: "Conversation gateways and presentation signal factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_conversation_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/conversation_presentation_signals_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.target",
      kind: "flutter-controller",
      summary: "Target discovery controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_target_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/target_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.skill",
      kind: "flutter-controller",
      summary: "Skill Hub controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_skill_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/skill_hub_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.settings",
      kind: "flutter-controller",
      summary: "Settings and maintenance controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_settings_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/client_update_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.mobile",
      kind: "flutter-controller",
      summary: "Mobile Relay and Secure Mesh controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_mobile_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/mobile_relay_component_boundary_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.usage",
      kind: "flutter-controller",
      summary: "Agent usage controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_usage_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/agent_usage_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.navigation",
      kind: "flutter-controller",
      summary: "Client navigation hook factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_navigation_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/client_navigation_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.presentation",
      kind: "flutter-controller",
      summary: "Shell and layout presentation factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_presentation_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/client_shell_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.scenario.bootstrap",
      kind: "flutter-controller",
      summary: "Client bootstrap, portable data, and initial relay behavior",
      inputs: [
        "apps/desktop/test/client_bootstrap_test.dart",
        "apps/desktop/test/fixtures/client_controller_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/bootstrap_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/preload_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
        "apps/desktop/test/fixtures/client_controller/support/fake_mobile_relay_service.dart",
      ],
      command: flutterTests(["test/client_bootstrap_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.target",
      kind: "flutter-controller",
      summary: "Target discovery, selection, and tab ordering behavior",
      inputs: [
        "apps/desktop/test/client_target_test.dart",
        "apps/desktop/test/fixtures/client_controller/target_history_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/target_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_target_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.mobile-history",
      kind: "flutter-controller",
      summary: "Mobile Secure Mesh native history pagination and exact selection",
      inputs: [
        "apps/desktop/test/client_mobile_history_test.dart",
        "apps/desktop/test/fixtures/client_controller/mobile_history_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
        "apps/desktop/test/fixtures/client_controller/support/fake_mobile_relay_service.dart",
      ],
      command: flutterTests(["test/client_mobile_history_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.history-refresh",
      kind: "flutter-controller",
      summary: "Native history streaming, paging, refresh, and scheduler behavior",
      inputs: [
        "apps/desktop/test/client_history_refresh_test.dart",
        "apps/desktop/test/fixtures/client_controller/history_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/history_refresh_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_history_refresh_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.history-runtime",
      kind: "flutter-controller",
      summary: "Cached history selection and active native runtime turn behavior",
      inputs: [
        "apps/desktop/test/client_history_runtime_test.dart",
        "apps/desktop/test/fixtures/client_controller/history_runtime_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/history_runtime/**",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_history_runtime_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.conversation-dispatch",
      kind: "flutter-controller",
      summary: "Conversation runtime dispatch, refresh, and failure behavior",
      inputs: [
        "apps/desktop/test/client_conversation_dispatch_test.dart",
        "apps/desktop/test/fixtures/client_controller/conversation_dispatch_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_conversation_dispatch_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.local-management",
      kind: "flutter-controller",
      summary: "Local skill, archive, snapshot, and management behavior",
      inputs: [
        "apps/desktop/test/client_local_management_test.dart",
        "apps/desktop/test/fixtures/client_controller/local_management_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/conversation_archive_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/skill_freshness_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/skill_management_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/target_management_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_local_management_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.secure-mesh",
      kind: "flutter-controller",
      summary: "Secure Mesh pairing, command, file, skill, and approval behavior",
      inputs: [
        "apps/desktop/test/client_secure_mesh_test.dart",
        "apps/desktop/test/fixtures/client_controller/secure_mesh_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
        "apps/desktop/test/fixtures/client_controller/support/fake_mobile_relay_service.dart",
        "apps/desktop/test/fixtures/client_controller/support/no_preload_client_controller.dart",
      ],
      command: flutterTests(["test/client_secure_mesh_test.dart"]),
    }),
  defineModule({
      id: "flutter.layer.shell",
      kind: "flutter-layer",
      summary: "Application composition, navigation, localization, and shared shell",
      inputs: [
        "apps/desktop/lib/app.dart",
        "apps/desktop/lib/main.dart",
        "apps/desktop/lib/src/application/composition/**",
        "apps/desktop/lib/src/application/controller/client_conversation_archive_bindings.dart",
        "apps/desktop/lib/src/application/controller/client_lifecycle_coordinator.dart",
        "apps/desktop/lib/src/application/controller/client_shell_controller.dart",
        "apps/desktop/lib/src/application/localization/**",
        "apps/desktop/lib/src/application/models/**",
        "apps/desktop/lib/src/application/product_acceptance/**",
        "apps/desktop/lib/src/application/features/navigation/**",
        "apps/desktop/lib/src/frontend/l10n/**",
        "apps/desktop/lib/src/frontend/shared/**",
        "apps/desktop/lib/src/frontend/shell/**",
        "apps/desktop/assets/brand/**",
        "apps/desktop/integration_test/**",
        "apps/desktop/test/apple_buttons_theme_test.dart",
        "apps/desktop/test/apple_notifications_chrome_test.dart",
        "apps/desktop/test/apple_popup_select_test.dart",
        "apps/desktop/test/apple_ui_dependency_boundary_test.dart",
        "apps/desktop/test/client_application_strings_test.dart",
        "apps/desktop/test/client_controller_facade_boundary_test.dart",
        "apps/desktop/test/client_lifecycle_coordinator_test.dart",
        "apps/desktop/test/client_navigation_controller_test.dart",
        "apps/desktop/test/client_section_preload_controller_test.dart",
        "apps/desktop/test/client_shell_controller_test.dart",
        "apps/desktop/test/client_shell_mobile_layout_test.dart",
        "apps/desktop/test/i18n_contract_test.dart",
        "apps/desktop/test/l10n_library_boundary_test.dart",
        "apps/desktop/test/message_markdown_test.dart",
        "apps/desktop/test/message_markdown_component_boundary_test.dart",
        "apps/desktop/test/theme_test.dart",
        "apps/desktop/test/widget_test.dart",
      ],
      command: flutterTests([
        "test/apple_buttons_theme_test.dart",
        "test/apple_notifications_chrome_test.dart",
        "test/apple_popup_select_test.dart",
        "test/apple_ui_dependency_boundary_test.dart",
        "test/client_application_strings_test.dart",
        "test/client_controller_facade_boundary_test.dart",
        "test/client_lifecycle_coordinator_test.dart",
        "test/client_navigation_controller_test.dart",
        "test/client_section_preload_controller_test.dart",
        "test/client_shell_controller_test.dart",
        "test/client_shell_mobile_layout_test.dart",
        "test/i18n_contract_test.dart",
        "test/l10n_library_boundary_test.dart",
        "test/message_markdown_test.dart",
        "test/message_markdown_component_boundary_test.dart",
        "test/theme_test.dart",
        "test/widget_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layer.platform-storage",
      kind: "flutter-layer",
      summary: "Portable data, workspace manifests, clipboard, and log storage",
      inputs: [
        "apps/desktop/lib/src/platform/storage/**",
        "apps/desktop/lib/src/platform/client_clipboard_service.dart",
        "apps/desktop/lib/src/platform/runtime_platform_bridge.dart",
        "apps/desktop/test/client_log_export_service_test.dart",
        "apps/desktop/test/client_workspace_manifest_component_test.dart",
        "apps/desktop/test/portable_data_root_test.dart",
      ],
      command: flutterTests([
        "test/client_log_export_service_test.dart",
        "test/client_workspace_manifest_component_test.dart",
        "test/portable_data_root_test.dart",
      ]),
    })
]);
