import { command, node, defineModule } from "../helpers.mjs";

export const REGRESSION_MODULES = Object.freeze([
  defineModule({
      id: "regression.cli-command-admission-source-bundle",
      kind: "regression-infrastructure",
      summary: "Single-registry typed CLI admission source ownership and migration closure",
      inputs: [
        "crates/licoup-native/src/ffi/commands/**",
        "tests/contract/client/cli-command-admission-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/cli-command-admission-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.assistant-workflow-contract",
      kind: "regression-infrastructure",
      summary: "Assistant/Profile migration authority, deterministic candidates, zero-effect preflight, exact bindings and privacy-safe receipts",
      inputs: [
        "docs/adrs/0004-assistant-authored-flexible-workflows.md",
        "crates/licoup-native/src/domain/client_conversation/**",
        "crates/licoup-native/src/domain/adaptive_flywheel/**",
        "crates/licoup-native/src/domain/agent_usage/workflow_ledger.rs",
        "crates/licoup-native/resources/assistant-workflow-authoring/SKILL.md",
        "crates/licoup-native/src/bin/lico-subagent-mcp.rs",
        "schemas/client_bridge/conversation.json",
        "schemas/client_bridge/strategy.json",
        "tests/contract/client/assistant-workflow-contract.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/assistant-workflow-contract.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.subagent-mcp-common",
      kind: "regression-infrastructure",
      summary: "Assistant/Profile facade, exact Membership delegation, readiness observation, and packaged Subagent MCP runtime",
      inputs: [
        "crates/licoup-native/src/bin/lico-subagent-mcp.rs",
        "crates/licoup-native/src/core/mcp/server.rs",
        "crates/licoup-native/src/core/mcp/tests/server.rs",
        "crates/licoup-native/src/domain/subagent_mcp/**",
        "crates/licoup-agent-runtime/**",
        "crates/licoup-agent-adapters/**",
        "crates/licoup-conversation/src/store/**",
        "crates/licoup-native/src/platform/subagent_mcp_supervisor.rs",
        "crates/licoup-native/resources/subagent-mesh/**",
        "schemas/subagent_mcp/**",
        "crates/licoup-native/src/bin/licoup/stdio_rpc/server.rs",
        "crates/licoup-native/src/domain/client_conversation/**",
        "crates/licoup-native/src/domain/adaptive_flywheel/assistant.rs",
        "crates/licoup-native/src/domain/adaptive_flywheel/service.rs",
        "crates/licoup-native/src/platform/cursor_driver/control.rs",
        "crates/licoup-native/src/platform/antigravity_driver/control.rs",
        "crates/licoup-native/src/platform/codex_plugin_manager.rs",
        "docs/protocols/subagent-mcp.md",
        "docs/protocols/subagent-mcp.zh-CN.md",
        "docs/functionality/USER-GUIDE.md",
        "docs/functionality/USER-GUIDE.zh-CN.md",
        "apps/desktop/packaging.modules.json",
        "apps/desktop/scripts/package-client/resource-assembly.mjs",
        "apps/desktop/scripts/package-client/bundle-resolver/**",
        "tests/contract/client/lico-subagent-mcp.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/lico-subagent-mcp.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.subagent-mcp-verification-routes",
      kind: "regression-infrastructure",
      summary: "Hermetic Subagent MCP startup recognition, direct-effect preflight, and target-keyed evidence",
      inputs: [
        "tests/product-e2e/cli/subagent-mcp/upstream.mjs",
        "tests/product-e2e/cli/subagent-mcp/upstream/**",
        "tests/product-e2e/cli/subagent-mcp/upstream.test.mjs",
        "tests/product-e2e/cli/subagent-mcp/downstream.mjs",
        "tests/product-e2e/cli/subagent-mcp/downstream.test.mjs",
        "tests/product-e2e/cli/subagent-mcp/streamable-http.mjs",
        "tests/product-e2e/cli/subagent-mcp/common-authority.test.mjs",
        "tests/product-e2e/cli/subagent-mcp/security.test.mjs",
        "tests/product-e2e/cli/subagent-mcp/interop-manifest.mjs",
        "tests/product-e2e/cli/subagent-mcp/interop-manifest.test.mjs",
        "tests/product-e2e/cli/subagent-mcp/interop-manifest.yaml",
        "tools/scripts/lib/agent-conversation-verification-models.mjs",
        "tools/scripts/lib/agent-conversation-verification-models.test.mjs",
        "tools/scripts/config/agent-conversation-verification-models.toml",
      ],
      command: command(
        "node",
        [
          "--test",
          "tests/product-e2e/cli/subagent-mcp/upstream.test.mjs",
          "tests/product-e2e/cli/subagent-mcp/downstream.test.mjs",
          "tests/product-e2e/cli/subagent-mcp/interop-manifest.test.mjs",
          "tests/product-e2e/cli/subagent-mcp/common-authority.test.mjs",
          "tests/product-e2e/cli/subagent-mcp/security.test.mjs",
          "tools/scripts/lib/agent-conversation-verification-models.test.mjs",
        ],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.unified-conversation-backend",
      kind: "regression-infrastructure",
      summary: "Generated canonical Conversation contract, native authority, explicit role-driven scheduling, and legacy-owner retirement",
      inputs: [
        "schemas/client_bridge/conversation.json",
        "schemas/client_bridge/manifest.json",
        "schemas/client_bridge/state.json",
        "crates/licoup-native/src/domain/client_conversation/**",
        "crates/licoup-native/src/domain/adaptive_flywheel/**",
        "crates/licoup-native/src/bin/lico-conversation-mcp.rs",
        "crates/licoup-native/src/bin/lico-subagent-mcp.rs",
        "tests/contract/client/unified-conversation-backend.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/unified-conversation-backend.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.infrastructure",
      kind: "regression-infrastructure",
      summary: "Module catalog, changed-file selection, and safe process execution",
      inputs: [
        "CONTRIBUTING.md",
        "CONTRIBUTING.zh-CN.md",
        "package.json",
        "package-lock.json",
        "tools/regression/**",
        "tools/scripts/client-module-regression.mjs",
        "tools/scripts/client-module-regression-self-test.mjs",
        "tools/scripts/client-regression-foundation.mjs",
        "tools/scripts/client-regression-frontend.mjs",
        "tools/scripts/client-regression-backend.mjs",
        "tools/scripts/client-regression-integration.mjs",
        "tools/scripts/client-regression-scenarios.mjs",
        "tools/scripts/client-regression-environment.mjs",
        "tests/contract/client/client-module-regression.test.mjs",
        "tests/contract/client/client-agent-regression-entries.test.mjs",
        "tests/contract/client/client-platform-regression-entries.test.mjs",
        "tests/contract/client/client-regression-batching.test.mjs",
        "tests/contract/client/client-regression-report.test.mjs",
        "tests/contract/client/flutter-native-regression-stats.test.mjs",
        "tests/contract/client/rust-regression-toolchain-stats.test.mjs",
        "tests/product-e2e/cli/agent-conversations/deepseek-harness/conversation.test.mjs",
      ],
      command: node("tools/scripts/client-module-regression-self-test.mjs", [], 60_000),
    }),
  defineModule({
      id: "regression.adaptive-flywheel-strategy-package",
      kind: "regression-infrastructure",
      summary: "Independent Graph strategy ZIP catalog, empty until import, and complete ordinal retirement",
      inputs: [
        "schemas/client_bridge/strategy.json",
        "crates/licoup-native/src/domain/adaptive_flywheel/**",
        "tests/contract/client/adaptive-flywheel-strategy.test.mjs",
        "tests/contract/client/unified-conversation-backend.test.mjs",
      ],
      command: command(
        "node",
        [
          "--test",
          "tests/contract/client/adaptive-flywheel-strategy.test.mjs",
          "tests/contract/client/unified-conversation-backend.test.mjs",
        ],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.agent-scan-paths",
      kind: "regression-infrastructure",
      summary: "Agent discovery allowlist TOML, env-only home, and no unused-agent other-app probe",
      inputs: [
        "crates/licoup-native/resources/agent-scan-paths.toml",
        "crates/licoup-native/src/domain/targets/scan_paths.rs",
        "crates/licoup-native/src/domain/targets/binaries.rs",
        "crates/licoup-native/src/domain/targets/platform_paths.rs",
        "crates/licoup-native/src/platform/paths.rs",
        "crates/licoup-native/src/domain/conversation/history_discovery.rs",
        "apps/desktop/lib/src/platform/native_client/agent_service_actions.dart",
        "apps/desktop/lib/src/application/controller/client_lifecycle_facade.dart",
        "apps/desktop/lib/src/application/controller/client_navigation_facade.dart",
        "tests/contract/client/agent-scan-paths.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/agent-scan-paths.test.mjs"],
        30_000,
      ),
    }),
  defineModule({
      id: "regression.test-artifact-lifecycle",
      kind: "regression-infrastructure",
      summary: "Leased build outputs, fail-closed reclaim markers, and download-cache isolation",
      inputs: [
        "package.json",
        "tools/scripts/client-build.mjs",
        "tests/contract/client/client-build.test.mjs",
        "tools/scripts/cargo-client.mjs",
        "tools/scripts/client-test-artifacts.mjs",
        "tools/scripts/client-android-native-tests.mjs",
        "tools/scripts/client-secure-mesh-trust-ux.mjs",
        "tools/scripts/lib/cargo-test-filter-runner.mjs",
        "tools/scripts/lib/test-artifact-lifecycle.mjs",
        "tools/scripts/lib/test-artifact-lifecycle/**",
        "tools/scripts/lib/test-artifact-lifecycle.test.mjs",
        "tools/regression/client-module-execution.mjs",
        "tools/regression/client-module-regression-tests/runner-safety.mjs",
        "tests/smoke/native-client-smoke.mjs",
      ],
      command: command(
        "node",
        ["--test", "tools/scripts/lib/test-artifact-lifecycle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.public-client-docs",
      kind: "regression-infrastructure",
      summary: "Bilingual public client product, privacy, and manual optional-collaboration contract",
      inputs: [
        "README.md",
        "README.zh-CN.md",
        "CONTRIBUTING.md",
        "CONTRIBUTING.zh-CN.md",
        "SECURITY.md",
        "SECURITY.zh-CN.md",
        "docs/functionality/USER-GUIDE.md",
        "docs/functionality/USER-GUIDE.zh-CN.md",
        "docs/architecture/README.md",
        "docs/architecture/README.zh-CN.md",
        "docs/COMPATIBILITY.md",
        "docs/COMPATIBILITY.zh-CN.md",
        "crates/licoup-native/resources/agent-native-capabilities.json",
        "tools/scripts/client-support-matrix.mjs",
        "tests/contract/client/public-client-docs.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/public-client-docs.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.documentation-governance",
      kind: "regression-infrastructure",
      summary: "Formal document layout, public Git candidate, links, language pairs, and local-asset isolation",
      inputs: [
        ".gitignore",
        "package.json",
        "README.md",
        "README.zh-CN.md",
        "PRODUCT.md",
        "CONTRIBUTING.md",
        "CONTRIBUTING.zh-CN.md",
        "CODE_OF_CONDUCT.md",
        "CHANGELOG.md",
        "LICENSE",
        "SECURITY.md",
        "SECURITY.zh-CN.md",
        "docs/README.md",
        "docs/RUNBOOK.md",
        "docs/COMPATIBILITY.md",
        "docs/COMPATIBILITY.zh-CN.md",
        "docs/ENTITY-CONFIG-LAYOUT.md",
        "docs/architecture/**",
        "docs/functionality/**",
        "docs/protocols/**",
        "docs/examples/**",
        "docs/adrs/**",
        "apps/desktop/README.md",
        "crates/licoup-native/README.md",
        "crates/lico-catalog-convergence/README.md",
        "packages/contracts/client/README.md",
        "packages/protocols/native-client/README.md",
        "tools/verify-documentation.mjs",
        "tools/scripts/client-support-matrix.mjs",
        "crates/licoup-native/resources/agent-native-capabilities.json",
      ],
      command: node("tools/verify-documentation.mjs", [], 60_000),
    }),
  defineModule({
      id: "regression.secure-mesh-source-bundles",
      kind: "regression-infrastructure",
      summary: "Aggregate source-evidence contracts for physically split Secure Mesh modules",
      inputs: [
        "tests/contract/client/secure-mesh-source-bundles.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-source-bundles.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.core-state-machine-test-layout",
      kind: "regression-infrastructure",
      summary: "Physical Secure Mesh state-machine test ownership, names, and stable vectors",
      inputs: [
        "crates/licoup-native/src/core/secure_mesh_acp.rs",
        "crates/licoup-native/src/core/secure_mesh_acp/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_capability_proof.rs",
        "crates/licoup-native/src/core/secure_mesh_capability_proof/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_session_negotiation.rs",
        "crates/licoup-native/src/core/secure_mesh_session_negotiation/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_sparse_pq_ratchet.rs",
        "crates/licoup-native/src/core/secure_mesh_sparse_pq_ratchet/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_mls_product/security_ledger.rs",
        "crates/licoup-native/src/core/secure_mesh_mls_product/security_ledger/test_support.rs",
        "crates/licoup-native/src/core/secure_mesh_mls_product/tests/security_ledger.rs",
        "tests/contract/client/core-state-machine-test-layout.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/core-state-machine-test-layout.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-update-source-bundle",
      kind: "regression-infrastructure",
      summary: "Fail-closed client-update source split, release authority, and redaction contract",
      inputs: [
        "crates/licoup-native/src/domain/client_update.rs",
        "crates/licoup-native/src/domain/client_update/**",
        "tests/contract/client/client-update-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-update-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.codex-app-server-source-bundle",
      kind: "regression-infrastructure",
      summary: "Codex app-server split ownership, fail-closed protocol, bounded IO, and redaction contract",
      inputs: [
        "crates/licoup-native/src/platform/codex_app_server.rs",
        "crates/licoup-native/src/platform/codex_app_server/**",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/codex.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/codex/**",
        "tests/contract/client/codex-app-server-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/codex-app-server-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.key-transparency-source-bundle",
      kind: "regression-infrastructure",
      summary: "Key-transparency workflow ownership, fail-closed authority reset, and one-way persistence boundary",
      inputs: [
        "crates/licoup-native/src/domain/mobile_relay/key_transparency.rs",
        "crates/licoup-native/src/domain/mobile_relay/key_transparency/**",
        "tests/contract/client/key-transparency-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/key-transparency-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.local-material-source-bundle",
      kind: "regression-infrastructure",
      summary: "Local endpoint material split ownership, fail-closed reset, and generation-mutation boundary",
      inputs: [
        "crates/licoup-native/src/domain/mobile_relay/endpoint_trust/local_material.rs",
        "crates/licoup-native/src/domain/mobile_relay/endpoint_trust/local_material/**",
        "tests/contract/client/local-material-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/local-material-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.directory-transparency-source-bundle",
      kind: "regression-infrastructure",
      summary: "Directory claim, freshness, verifier, authority, and authorization split ownership",
      inputs: [
        "crates/licoup-native/src/domain/mobile_relay/endpoint_trust/directory_transparency.rs",
        "crates/licoup-native/src/domain/mobile_relay/endpoint_trust/directory_transparency/**",
        "tests/contract/client/directory-transparency-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/directory-transparency-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.pairwise-session-source-bundle",
      kind: "regression-infrastructure",
      summary: "Pairwise status, replay redaction, ciphertext operations, atomic commit, handshake, and durable-store split",
      inputs: [
        "crates/licoup-native/src/domain/mobile_relay/pairwise_session.rs",
        "crates/licoup-native/src/domain/mobile_relay/pairwise_session/**",
        "tests/contract/client/pairwise-session-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/pairwise-session-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.relay-operations-source-bundle",
      kind: "regression-infrastructure",
      summary: "Ciphertext-only relay commands, canonical context, mailbox, envelope, registration, delivery, status, and allow-list split",
      inputs: [
        "crates/licoup-native/src/domain/mobile_relay/relay_operations.rs",
        "crates/licoup-native/src/domain/mobile_relay/relay_operations/**",
        "tests/contract/client/relay-operations-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/relay-operations-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-architecture-modules",
      kind: "regression-infrastructure",
      summary: "Terminal Presentation Boundary rules, synthetic violations, thin architecture entry, and frozen phase ordering",
      inputs: [
        "tools/verify-client-boundary.mjs",
        "apps/desktop/scripts/verify-client-architecture.mjs",
        "apps/desktop/scripts/client-architecture/assertions.mjs",
        "apps/desktop/scripts/client-architecture/context.mjs",
        "apps/desktop/scripts/client-architecture/filesystem.mjs",
        "apps/desktop/scripts/client-architecture/checks/composition.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/mobile-relay-bridges.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/physical-layers-and-libraries.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/presentation-boundary.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/shell-isolation-and-native-stdio.mjs",
        "apps/desktop/scripts/client-architecture/checks/foundations.mjs",
        "apps/desktop/scripts/client-architecture/checks/native.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/command-and-file-transport.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/conversation-domain.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/crate-core-and-facade-bounds.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/domain-and-crypto-boundaries.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-authority-and-custody.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-foundations-and-local-archive.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/target-readiness-reducer.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/android-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/ios-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/runtime-drivers-and-local-service.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/target-serve-and-gateway.mjs",
        "apps/desktop/scripts/client-architecture/checks/privacy.mjs",
        "tests/contract/client/client-architecture-modules.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-architecture-modules.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.package-client-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin package-client facade and nineteen bounded packaging authorities",
      inputs: [
        "apps/desktop/scripts/package-client.mjs",
        "apps/desktop/scripts/package-client/build/flutter.mjs",
        "apps/desktop/scripts/package-client/build/native.mjs",
        "apps/desktop/scripts/package-client/build/swift.mjs",
        "apps/desktop/scripts/package-client/bundle-resolver/linux.mjs",
        "apps/desktop/scripts/package-client/bundle-resolver/macos.mjs",
        "apps/desktop/scripts/package-client/bundle-resolver/windows.mjs",
        "apps/desktop/scripts/package-client/cli-policy.mjs",
        "apps/desktop/scripts/package-client/config-codec.mjs",
        "apps/desktop/scripts/package-client/macos/install.mjs",
        "apps/desktop/scripts/package-client/macos/metadata.mjs",
        "apps/desktop/scripts/package-client/macos/signing.mjs",
        "apps/desktop/scripts/package-client/module-selection.mjs",
        "apps/desktop/scripts/package-client/orchestrator.mjs",
        "apps/desktop/scripts/package-client/portable-manifest.mjs",
        "apps/desktop/scripts/package-client/process-runner.mjs",
        "apps/desktop/scripts/package-client/pub-cache.mjs",
        "apps/desktop/scripts/package-client/resource-assembly.mjs",
        "apps/desktop/scripts/package-client/source-staging.mjs",
        "apps/desktop/scripts/package-client/windows-manifest.mjs",
        "tests/contract/client/package-client/package-client-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/package-client/package-client-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.verify-client-plan-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin plan-gate facade, static check leaves, shared readers, and dedicated leaf regressions",
      inputs: [
        "apps/desktop/scripts/verify-client-plan.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/android-ios.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/client-boundary.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/crypto-redaction-handoff.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/docs-readiness.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/evidence-routing.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/linux-windows.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/package-and-runner.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/physical-evidence.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/secret-store.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/trust-release.mjs",
        "apps/desktop/scripts/verify-client-plan/dynamic-self-tests.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/assert.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/context.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/fs.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/sanitize.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-leaf-fixtures.test.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-ordering.test.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-privacy.test.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        [
          "--test",
          "tests/contract/client/verify-client-plan/verify-client-plan-leaf-fixtures.test.mjs",
          "tests/contract/client/verify-client-plan/verify-client-plan-ordering.test.mjs",
          "tests/contract/client/verify-client-plan/verify-client-plan-privacy.test.mjs",
          "tests/contract/client/verify-client-plan/verify-client-plan-source-bundle.test.mjs",
        ],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.layout-boundaries",
      kind: "regression-infrastructure",
      summary: "Target-state layout ownership, structural shared-renderer policy, profile path, and import-boundary verifier",
      inputs: [
        "apps/desktop/scripts/verify-layout-boundaries.mjs",
        "apps/desktop/scripts/verify-layout-boundaries-self-test.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/run.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/helpers.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/fixtures.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/product.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/imports.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/ports.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/identity.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/bundle-product.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/cli.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/config.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dart-source.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dependency-policy.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/errors.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/import-graph.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/ownership.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/paths.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/state-authority.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/surface-parse.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/verify.mjs",
      ],
      command: node(
        "apps/desktop/scripts/verify-layout-boundaries.mjs",
        ["--self-test"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.layout-boundaries-source-bundle",
      kind: "regression-infrastructure",
      summary: "Layout boundary leaf ownership, structural dependency policy, thin facade, and synthetic self-test contract",
      inputs: [
        "tests/contract/client/layout-boundaries-source-bundle.test.mjs",
        "apps/desktop/scripts/verify-layout-boundaries.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/bundle-product.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/cli.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/config.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dart-source.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dependency-policy.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/errors.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/import-graph.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/ownership.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/paths.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/state-authority.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/surface-parse.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/verify.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/layout-boundaries-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.layout-visual-manifests",
      kind: "regression-infrastructure",
      summary: "Layout visual-manifest check surface and dedicated self-test",
      inputs: [
        "apps/desktop/scripts/verify-layout-visual-manifests.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests-self-test.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/catalog.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/check.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/cli.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/config.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/errors.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/generate.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/manifest-codec.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/owner-roots.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/paths.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/write.mjs",
      ],
      command: node(
        "apps/desktop/scripts/verify-layout-visual-manifests-self-test.mjs",
        [],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.layout-visual-manifests-source-bundle",
      kind: "regression-infrastructure",
      summary: "Layout visual-manifest leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/layout-visual-manifests-source-bundle.test.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/catalog.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/check.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/cli.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/config.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/errors.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/generate.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/manifest-codec.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/owner-roots.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/paths.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/write.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/layout-visual-manifests-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.agent-conversation-parity-reducer",
      kind: "regression-infrastructure",
      summary: "Native-agent conversation parity reducer contract and ACP self-test binding",
      inputs: [
        "tests/contract/client/agent-conversation-parity-reducer.test.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer-facade.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/cli.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/constants.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/digests.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/errors.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/evidence.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/inputs.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/inventory.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/json.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/privacy.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/reduce.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/run.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity-facade.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/agent-ids.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/cli.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/acp-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/app-server-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/copilot-sdk-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/pi-rpc-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/constants.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/errors.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/evidence.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/live-gate.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/live.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/native/acp-turn.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/native/app-server.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/native/pi.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/packaging.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/process.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/results.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/round-facts.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/run-round.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/run.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/self-test/fake-runtime.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/self-test/runner.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/session-cleanup.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/session-query.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/sidecar.mjs",
      ],
      command: node(
        "tests/contract/client/agent-conversation-parity-reducer.test.mjs",
        [],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.acp-conversation-parity-source-bundle",
      kind: "regression-infrastructure",
      summary: "ACP conversation parity leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/acp-conversation-parity-source-bundle.test.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity-facade.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/agent-ids.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/cli.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/acp-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/app-server-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/copilot-sdk-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/clients/pi-rpc-client.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/constants.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/errors.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/evidence.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/live-gate.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/live.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/native/acp-turn.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/native/app-server.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/native/pi.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/packaging.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/process.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/results.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/round-facts.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/run-round.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/run.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/self-test/fake-runtime.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/self-test/runner.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/session-cleanup.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/session-query.mjs",
        "tests/product-e2e/cli/agent-conversations/support/parity/sidecar.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/acp-conversation-parity-source-bundle.test.mjs"],
        180_000,
      ),
    }),
  defineModule({
      id: "regression.mobile-simulator-closure-source-bundle",
      kind: "regression-infrastructure",
      summary: "Mobile simulator closure leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/mobile-simulator-closure-source-bundle.test.mjs",
        "tools/scripts/client-mobile-simulator-closure.mjs",
        "tools/scripts/client-mobile-simulator-closure/android/artifacts.mjs",
        "tools/scripts/client-mobile-simulator-closure/android/device.mjs",
        "tools/scripts/client-mobile-simulator-closure/android/verify.mjs",
        "tools/scripts/client-mobile-simulator-closure/cli.mjs",
        "tools/scripts/client-mobile-simulator-closure/constants.mjs",
        "tools/scripts/client-mobile-simulator-closure/errors.mjs",
        "tools/scripts/client-mobile-simulator-closure/flutter.mjs",
        "tools/scripts/client-mobile-simulator-closure/ios/artifacts.mjs",
        "tools/scripts/client-mobile-simulator-closure/ios/device.mjs",
        "tools/scripts/client-mobile-simulator-closure/ios/verify.mjs",
        "tools/scripts/client-mobile-simulator-closure/process.mjs",
        "tools/scripts/client-mobile-simulator-closure/receipt.mjs",
        "tools/scripts/client-mobile-simulator-closure/run.mjs",
        "tools/scripts/client-mobile-simulator-closure/self-test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/mobile-simulator-closure-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.android-physical-install-launch-source-bundle",
      kind: "regression-infrastructure",
      summary: "Android physical install/launch leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/android-physical-install-launch-source-bundle.test.mjs",
        "tools/scripts/client-android-physical-install-launch.mjs",
        "tools/scripts/client-android-physical-install-launch/apk/inspect.mjs",
        "tools/scripts/client-android-physical-install-launch/cli.mjs",
        "tools/scripts/client-android-physical-install-launch/constants.mjs",
        "tools/scripts/client-android-physical-install-launch/device/adb.mjs",
        "tools/scripts/client-android-physical-install-launch/device/classify.mjs",
        "tools/scripts/client-android-physical-install-launch/device/select.mjs",
        "tools/scripts/client-android-physical-install-launch/operations/install.mjs",
        "tools/scripts/client-android-physical-install-launch/operations/launch.mjs",
        "tools/scripts/client-android-physical-install-launch/privacy/leak-scan.mjs",
        "tools/scripts/client-android-physical-install-launch/privacy/sanitize.mjs",
        "tools/scripts/client-android-physical-install-launch/report/blocked.mjs",
        "tools/scripts/client-android-physical-install-launch/report/build.mjs",
        "tools/scripts/client-android-physical-install-launch/run.mjs",
        "tools/scripts/client-android-physical-install-launch/runtime/status.mjs",
        "tools/scripts/client-android-physical-install-launch/self-test.mjs",
        "tools/scripts/client-android-physical-install-launch/util/hash.mjs",
        "tools/scripts/client-android-physical-install-launch/util/json.mjs",
        "tools/scripts/client-android-physical-install-launch/util/paths.mjs",
        "tools/scripts/client-android-physical-install-launch/version.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/android-physical-install-launch-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.cli-vm-source-bundle",
      kind: "regression-infrastructure",
      summary: "Client CLI VM leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/cli-vm-source-bundle.test.mjs",
        "tools/scripts/client-cli-vm.mjs",
        "tools/scripts/client-cli-vm/cli.mjs",
        "tools/scripts/client-cli-vm/constants.mjs",
        "tools/scripts/client-cli-vm/distro/select.mjs",
        "tools/scripts/client-cli-vm/image/disk.mjs",
        "tools/scripts/client-cli-vm/image/download.mjs",
        "tools/scripts/client-cli-vm/image/seed.mjs",
        "tools/scripts/client-cli-vm/linux-product/artifacts.mjs",
        "tools/scripts/client-cli-vm/linux-product/bootstrap.mjs",
        "tools/scripts/client-cli-vm/linux-product/command.mjs",
        "tools/scripts/client-cli-vm/linux-product/incomplete.mjs",
        "tools/scripts/client-cli-vm/linux-product/run.mjs",
        "tools/scripts/client-cli-vm/linux-product/shell-helpers.mjs",
        "tools/scripts/client-cli-vm/linux-product/source-manifest.mjs",
        "tools/scripts/client-cli-vm/linux-product/toolchain.mjs",
        "tools/scripts/client-cli-vm/linux-product/validate.mjs",
        "tools/scripts/client-cli-vm/list.mjs",
        "tools/scripts/client-cli-vm/paths.mjs",
        "tools/scripts/client-cli-vm/process.mjs",
        "tools/scripts/client-cli-vm/run.mjs",
        "tools/scripts/client-cli-vm/self-test/runner.mjs",
        "tools/scripts/client-cli-vm/ssh/key.mjs",
        "tools/scripts/client-cli-vm/ssh/session.mjs",
        "tools/scripts/client-cli-vm/sync/artifacts.mjs",
        "tools/scripts/client-cli-vm/sync/repo.mjs",
        "tools/scripts/client-cli-vm/verify/bootstrap.mjs",
        "tools/scripts/client-cli-vm/verify/command.mjs",
        "tools/scripts/client-cli-vm/verify/distro.mjs",
        "tools/scripts/client-cli-vm/vm/lifecycle.mjs",
        "tools/scripts/client-cli-vm/vm/prepare.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/cli-vm-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.release-acceptance-source-bundle",
      kind: "regression-infrastructure",
      summary: "Client release-acceptance leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/release-acceptance-source-bundle.test.mjs",
        "tools/scripts/client-release-acceptance.mjs",
        "tools/scripts/client-release-acceptance/artifacts/android.mjs",
        "tools/scripts/client-release-acceptance/artifacts/digests.mjs",
        "tools/scripts/client-release-acceptance/artifacts/helpers.mjs",
        "tools/scripts/client-release-acceptance/artifacts/macos.mjs",
        "tools/scripts/client-release-acceptance/artifacts/materialize.mjs",
        "tools/scripts/client-release-acceptance/artifacts/receipt.mjs",
        "tools/scripts/client-release-acceptance/artifacts/selected.mjs",
        "tools/scripts/client-release-acceptance/artifacts/stability.mjs",
        "tools/scripts/client-release-acceptance/cli.mjs",
        "tools/scripts/client-release-acceptance/constants.mjs",
        "tools/scripts/client-release-acceptance/evidence.mjs",
        "tools/scripts/client-release-acceptance/load-reports.mjs",
        "tools/scripts/client-release-acceptance/preflight.mjs",
        "tools/scripts/client-release-acceptance/privacy.mjs",
        "tools/scripts/client-release-acceptance/reduce.mjs",
        "tools/scripts/client-release-acceptance/refs.mjs",
        "tools/scripts/client-release-acceptance/report-deps.mjs",
        "tools/scripts/client-release-acceptance/run.mjs",
        "tools/scripts/client-release-acceptance/sanitize-binding.mjs",
        "tools/scripts/client-release-acceptance/self-test/fixtures.mjs",
        "tools/scripts/client-release-acceptance/self-test/runner.mjs",
        "tools/scripts/client-release-acceptance/support-matrix.mjs",
        "tools/scripts/client-release-acceptance/targets.mjs",
        "tools/scripts/client-release-acceptance/util.mjs",
        "tools/scripts/client-release-acceptance/validate-config.mjs",
        "tools/scripts/client-release-acceptance/validate-report.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/release-acceptance-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.artifact-verification-receipts-source-bundle",
      kind: "regression-infrastructure",
      summary: "Artifact verification receipts leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/artifact-verification-receipts-source-bundle.test.mjs",
        "tools/scripts/client-artifact-verification-receipts.mjs",
        "tools/scripts/client-artifact-verification-receipts/cli.mjs",
        "tools/scripts/client-artifact-verification-receipts/constants.mjs",
        "tools/scripts/client-artifact-verification-receipts/errors.mjs",
        "tools/scripts/client-artifact-verification-receipts/invoke/lineage.mjs",
        "tools/scripts/client-artifact-verification-receipts/invoke/target-input.mjs",
        "tools/scripts/client-artifact-verification-receipts/privacy.mjs",
        "tools/scripts/client-artifact-verification-receipts/receipt/build.mjs",
        "tools/scripts/client-artifact-verification-receipts/receipt/empty.mjs",
        "tools/scripts/client-artifact-verification-receipts/run.mjs",
        "tools/scripts/client-artifact-verification-receipts/self-test/fixtures.mjs",
        "tools/scripts/client-artifact-verification-receipts/self-test/runner.mjs",
        "tools/scripts/client-artifact-verification-receipts/util.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-config.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/android.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/common.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/linux.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/macos.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/artifact-verification-receipts-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-release-proof-bundle-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh release-proof-bundle leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/secure-mesh-release-proof-bundle-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/cli.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/config.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/constants.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/contract-readiness.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/freshness.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/integrity.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/io.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/lists.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/privacy.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report-summary-core.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report-summary-physical.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report-summary.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/run.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/client-licoarc-crypto.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/contract.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/freshness.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/physical-evidence.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/redaction.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/android-install.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/client-licoarc-crypto.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/physical-evidence.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/physical-matrix.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/redaction.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/update.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/windows.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/verifiers.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-release-proof-bundle-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.linux-node-matrix-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh linux-node-matrix leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/linux-node-matrix-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/assert.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/cli.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/constants.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/identity.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/matrix.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/operations.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/relay/opaque-relay.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/relay/protocol.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/report.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/run.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/self-test.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/util.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/linux-node-matrix-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.linux-vm-package-receipt-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh linux-vm-package-receipt leaf ownership and thin facade contract",
      inputs: [
        "tests/contract/client/linux-vm-package-receipt-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/cli.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/gui.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/receipt.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/report.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/run.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/util.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/linux-vm-package-receipt-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.e2ee-evidence-bundle-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh e2ee evidence bundle leaf ownership, thin facade, and leak-scan self-test",
      inputs: [
        "tests/contract/client/e2ee-evidence-bundle-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-e2ee-evidence-bundle.mjs",
        "tools/scripts/client-secure-mesh-e2ee-evidence-bundle/run.mjs",
        "tools/scripts/client-secure-mesh-e2ee-evidence-bundle/util.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/e2ee-evidence-bundle-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-toolchain-runner-source-bundle",
      kind: "regression-infrastructure",
      summary: "Client toolchain runner leaf ownership and thin facade contract",
      inputs: [
        "tests/contract/client/client-toolchain-runner-source-bundle.test.mjs",
        "tools/scripts/client-toolchain-runner.mjs",
        "tools/scripts/client-toolchain-runner/artifacts.mjs",
        "tools/scripts/client-toolchain-runner/cli.mjs",
        "tools/scripts/client-toolchain-runner/constants.mjs",
        "tools/scripts/client-toolchain-runner/flutter.mjs",
        "tools/scripts/client-toolchain-runner/process.mjs",
        "tools/scripts/client-toolchain-runner/pub-cache.mjs",
        "tools/scripts/client-toolchain-runner/run.mjs",
        "tools/scripts/client-toolchain-runner/windows.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-toolchain-runner-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.macos-keychain-user-presence-source-bundle",
      kind: "regression-infrastructure",
      summary: "macOS keychain user-presence leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/macos-keychain-user-presence-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/capability/facts.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/capability/summarize.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/cli.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/constants.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/codesign.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/process.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/run-swift.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/swift-source.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/parse.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/privacy.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/proof.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/report.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/run.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/self-test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/macos-keychain-user-presence-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.pairwise-content-audit-source-bundle",
      kind: "regression-infrastructure",
      summary: "Pairwise content audit leaf ownership, thin facade, and contract-bound leaf tokens",
      inputs: [
        "tests/contract/client/pairwise-content-audit-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/constants.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/corpus.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/hash.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/native-test.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/privacy.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/run.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/signoff-load.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/signoff.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/source-check.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/vectors.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/pairwise-content-audit-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.agent-conversation-parity-reducer-source-bundle",
      kind: "regression-infrastructure",
      summary: "Agent conversation parity reducer leaf ownership, thin facade, and --check dry-run contract",
      inputs: [
        "tests/contract/client/agent-conversation-parity-reducer-source-bundle.test.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer-facade.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/cli.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/constants.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/digests.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/errors.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/evidence.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/inputs.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/inventory.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/json.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/privacy.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/reduce.mjs",
        "tests/product-e2e/cli/agent-conversations/support/reducer/run.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/agent-conversation-parity-reducer-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.contracts-client",
      kind: "regression-infrastructure",
      summary: "Client contract schema validation for checked-in semantic envelopes",
      inputs: [
        "tests/contract/client/contracts-client.test.mjs",
        "packages/contracts/client/semantic-conversation.schema.json",
      ],
      command: node("tests/contract/client/contracts-client.test.mjs", [], 60_000),
    }),
  defineModule({
      id: "regression.local-data-egress-boundary",
      kind: "regression-infrastructure",
      summary: "Local-data egress allowlist and GET-only package-fetch boundary",
      inputs: [
        "tests/contract/client/local-data-egress-boundary.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/local-data-egress-boundary.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-agent-usage",
      kind: "regression-infrastructure",
      summary: "Local-token agent-usage evidence gate over native, Flutter, and docs contracts",
      inputs: [
        "apps/desktop/scripts/verify-client-agent-usage.mjs",
        "crates/licoup-native/src/domain/agent_usage/workflow_ledger.rs",
        "apps/desktop/lib/src/contracts/agent_usage_models.dart",
        "apps/desktop/lib/src/application/features/agents/controller/agent_usage_daily_cache.dart",
        "apps/desktop/lib/src/backend/features/agents/services/agent_usage_service.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_panel_widgets.dart",
        "apps/desktop/lib/src/composition/binding_shell_renderer.dart",
        "apps/desktop/lib/src/frontend/shell/client_shell.dart",
        "apps/desktop/lib/src/frontend/l10n/lico_strings_labels.dart",
        "apps/desktop/test/agent_usage_workflow_test.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_panel_fixtures.dart",
        "docs/functionality/CLIENT-DESKTOP.md",
        "docs/functionality/USER-GUIDE.md",
        "docs/functionality/USER-GUIDE.zh-CN.md",
        "docs/architecture/README.md",
        "docs/architecture/README.zh-CN.md",
      ],
      command: node("apps/desktop/scripts/verify-client-agent-usage.mjs", [], 60_000),
    }),
  defineModule({
      id: "architecture.client-boundaries",
      kind: "architecture",
      summary: "Fast client layer, composition, native-module, and platform boundary gate",
      inputs: [
        "tools/verify-client-boundary.mjs",
        "apps/desktop/scripts/verify-client-architecture.mjs",
        "apps/desktop/scripts/client-architecture/assertions.mjs",
        "apps/desktop/scripts/client-architecture/context.mjs",
        "apps/desktop/scripts/client-architecture/filesystem.mjs",
        "apps/desktop/scripts/client-architecture/checks/composition.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/mobile-relay-bridges.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/physical-layers-and-libraries.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/presentation-boundary.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/shell-isolation-and-native-stdio.mjs",
        "apps/desktop/scripts/client-architecture/checks/foundations.mjs",
        "apps/desktop/scripts/client-architecture/checks/native.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/command-and-file-transport.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/conversation-domain.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/crate-core-and-facade-bounds.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/domain-and-crypto-boundaries.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-authority-and-custody.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-foundations-and-local-archive.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/target-readiness-reducer.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/android-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/ios-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/runtime-drivers-and-local-service.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/target-serve-and-gateway.mjs",
        "apps/desktop/scripts/client-architecture/checks/privacy.mjs",
        "apps/desktop/packaging.modules.json",
        "crates/licoup-native/resources/agent-conversation-drivers.json",
        "apps/desktop/lib/**",
        "apps/desktop/integration_test/**",
        "apps/desktop/test/agents_workspace/**",
        "apps/desktop/test/fixtures/client_controller/**",
        "apps/desktop/test/fixtures/client_controller_scenarios.dart",
        "apps/desktop/android/**",
        "apps/desktop/ios/**",
        "crates/licoup-native/Cargo.toml",
        "crates/licoup-native/src/**",
        "packages/contracts/client/semantic-conversation.schema.json",
        "CONTRIBUTING.md",
        "docs/architecture/README.md",
        "docs/functionality/USER-GUIDE.md",
        "tools/scripts/**",
      ],
      command: node("apps/desktop/scripts/verify-client-architecture.mjs", [], 30_000),
    }),
  defineModule({
      id: "regression.agent-conversation-message-blocks-source-bundle",
      kind: "regression-infrastructure",
      summary: "Message block exact exports, one-way presenter ownership, and dedicated widget regressions",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/disclosures.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/dispatcher.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/role_blocks.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/subagent.dart",
        "tests/contract/client/agent-conversation-message-blocks-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/agent-conversation-message-blocks-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.agent-conversation-pane-source-bundle",
      kind: "regression-infrastructure",
      summary: "Agent conversation pane zero-edge import graph, typed projection, and dedicated widget regressions",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/actions.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/composition.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/resize.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_controls.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_presentation.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_recent_sessions.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_workspace.dart",
        "apps/desktop/test/agent_conversation_recent_sessions_test.dart",
        "tests/contract/client/agent-conversation-pane-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/agent-conversation-pane-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.mobile-relay-panel-source-bundle",
      kind: "regression-infrastructure",
      summary: "Mobile Relay panel exact exports, one-way presenter ownership, and dedicated widget regressions",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/composition.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/pairing.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/qr.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/scan.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/trust.dart",
        "tests/contract/client/mobile-relay-panel-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/mobile-relay-panel-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.dashboard-desktop-chrome-source-bundle",
      kind: "regression-infrastructure",
      summary: "Dashboard desktop chrome exact exports, ordinary leaf boundaries, and dedicated widget regressions",
      inputs: [
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_desktop_chrome.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_desktop_search.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_folder_sidebar.dart",
        "tests/contract/client/dashboard-desktop-chrome-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/dashboard-desktop-chrome-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.agent-usage-codex-source-bundle",
      kind: "regression-infrastructure",
      summary: "Codex usage split ownership, local-only scanning, cache, and privacy boundaries",
      inputs: [
        "crates/licoup-native/src/domain/agent_usage/agent_usage_codex.rs",
        "crates/licoup-native/src/domain/agent_usage/agent_usage_codex/**",
        "crates/licoup-native/tests/agent_usage_incremental_cache.rs",
        "crates/licoup-native/tests/agent_usage_cache_cases/**",
        "tests/contract/client/agent-usage-codex-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/agent-usage-codex-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.cursor-openagent-source-bundle",
      kind: "regression-infrastructure",
      summary: "Cursor/OpenAgent exact ownership, explicit parser DAG, read-only bounded SQLite codec, and dedicated regressions",
      inputs: [
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/codec.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/composition.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/cursor.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/cursor_cli.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/cursor_projection.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/fallback.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/openagent.rs",
        "tests/contract/client/cursor-openagent-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/cursor-openagent-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.session-merge-source-bundle",
      kind: "regression-infrastructure",
      summary: "Session merge exact ownership, acyclic leaves, bounded graph closure, and dedicated leaf regressions",
      inputs: [
        "crates/licoup-native/src/domain/conversation/history/session_merge.rs",
        "crates/licoup-native/src/domain/conversation/history/session_merge/codex_lineage.rs",
        "crates/licoup-native/src/domain/conversation/history/session_merge/composition.rs",
        "crates/licoup-native/src/domain/conversation/history/session_merge/dedupe_paging.rs",
        "crates/licoup-native/src/domain/conversation/history/session_merge/delegated_merge.rs",
        "crates/licoup-native/src/domain/conversation/history/session_merge/model_names.rs",
        "crates/licoup-native/src/domain/conversation/history/session_merge/session_index.rs",
        "crates/licoup-native/src/domain/conversation/history/session_merge/stable_order.rs",
        "tests/contract/client/session-merge-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/session-merge-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.message-projection-source-bundle",
      kind: "regression-infrastructure",
      summary: "Message projection exact ownership, acyclic leaves, bounded recursion, cached privacy redaction, and policy separation",
      inputs: [
        "crates/licoup-native/src/domain/conversation/history/message_projection.rs",
        "crates/licoup-native/src/domain/conversation/history/message_projection/antigravity.rs",
        "crates/licoup-native/src/domain/conversation/history/message_projection/generated_context.rs",
        "crates/licoup-native/src/domain/conversation/history/message_projection/json_extract.rs",
        "crates/licoup-native/src/domain/conversation/history/message_projection/projection.rs",
        "crates/licoup-native/src/domain/conversation/history/message_projection/semantic.rs",
        "crates/licoup-native/src/domain/conversation/history/message_projection/structured_privacy.rs",
        "crates/licoup-native/src/domain/conversation/history/session_metadata.rs",
        "tests/contract/client/message-projection-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/message-projection-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.conversation-semantic-source-bundle",
      kind: "regression-infrastructure",
      summary: "Semantic conversation exact ownership, acyclic leaves, privacy/schema separation, and dedicated leaf regressions",
      inputs: [
        "crates/licoup-native/src/domain/conversation_semantic.rs",
        "crates/licoup-native/src/domain/conversation_semantic/artifact_projection.rs",
        "crates/licoup-native/src/domain/conversation_semantic/builder.rs",
        "crates/licoup-native/src/domain/conversation_semantic/execution_projection.rs",
        "crates/licoup-native/src/domain/conversation_semantic/io.rs",
        "crates/licoup-native/src/domain/conversation_semantic/markdown.rs",
        "crates/licoup-native/src/domain/conversation_semantic/model.rs",
        "crates/licoup-native/src/domain/conversation_semantic/privacy.rs",
        "crates/licoup-native/src/domain/conversation_semantic/thread_projection.rs",
        "crates/licoup-native/src/domain/conversation_semantic/validation.rs",
        "tests/contract/client/conversation-semantic-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/conversation-semantic-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.collaboration-workflow-operations-source-bundle",
      kind: "regression-infrastructure",
      summary: "Collaboration workflow operation ownership, approval and digest boundaries, acyclic leaves, and dedicated regressions",
      inputs: [
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/apply_local.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/apply_mcp.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/cancel.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/destination_policy.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/package_revalidation.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/plan_local.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/plan_mcp.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/projection.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/staging.rs",
        "crates/licoup-native/src/domain/collaboration_plugin/workflow/operations/validation.rs",
        "tests/contract/client/collaboration-workflow-operations-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/collaboration-workflow-operations-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-capability-source-bundle",
      kind: "regression-infrastructure",
      summary: "Restricted capability facade, bounded DAG/cache, one-way leaves, and privacy source proof",
      inputs: [
        "crates/licoup-native/resources/secure-mesh-capability-catalog.json",
        "crates/licoup-native/src/core/secure_mesh_capability.rs",
        "crates/licoup-native/src/core/secure_mesh_capability/catalog.rs",
        "crates/licoup-native/src/core/secure_mesh_capability/custody.rs",
        "crates/licoup-native/src/core/secure_mesh_capability/evaluation.rs",
        "crates/licoup-native/src/core/secure_mesh_capability/facts.rs",
        "crates/licoup-native/src/core/secure_mesh_capability/report.rs",
        "crates/licoup-native/src/core/secure_mesh_capability/taxonomy.rs",
        "tests/contract/client/secure-mesh-capability-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-capability-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-prekey-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin prekey facade, pairwise/KeyPackage split, local watermarks, and shared validation proof",
      inputs: [
        "crates/licoup-native/src/core/secure_mesh_prekey.rs",
        "crates/licoup-native/src/core/secure_mesh_prekey/inventory.rs",
        "crates/licoup-native/src/core/secure_mesh_prekey/key_package.rs",
        "crates/licoup-native/src/core/secure_mesh_prekey/pairwise.rs",
        "crates/licoup-native/src/core/secure_mesh_prekey/validation.rs",
        "tests/contract/client/secure-mesh-prekey-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-prekey-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-pairwise-boundary-source-bundle",
      kind: "regression-infrastructure",
      summary: "Atomic handshake and ratchet owners with bounded negotiation, payload, and relay leaves",
      inputs: [
        "crates/licoup-native/src/core/secure_mesh_pairwise/session_negotiation.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/session_negotiation/capability_binding.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/session_negotiation/handshake_machine.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/session_negotiation/input_validation.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/session_negotiation/key_schedule.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/session_negotiation/transcript_codec.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/key_ratchet.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/key_ratchet/payload_adapter.rs",
        "crates/licoup-native/src/core/secure_mesh_pairwise/key_ratchet/relay_codec.rs",
        "tests/contract/client/secure-mesh-pairwise-boundary-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-pairwise-boundary-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.local-service-source-bundle",
      kind: "regression-infrastructure",
      summary: "Target-neutral bounded local HTTP, SSE, state, process, and serve lifecycle source proof",
      inputs: [
        "crates/licoup-native/src/platform/local_service.rs",
        "crates/licoup-native/src/platform/local_service/bounds.rs",
        "crates/licoup-native/src/platform/local_service/concurrency.rs",
        "crates/licoup-native/src/platform/local_service/endpoint.rs",
        "crates/licoup-native/src/platform/local_service/executable.rs",
        "crates/licoup-native/src/platform/local_service/http.rs",
        "crates/licoup-native/src/platform/local_service/params.rs",
        "crates/licoup-native/src/platform/local_service/port.rs",
        "crates/licoup-native/src/platform/local_service/process.rs",
        "crates/licoup-native/src/platform/local_service/serve.rs",
        "crates/licoup-native/src/platform/local_service/sse.rs",
        "crates/licoup-native/src/platform/local_service/state.rs",
        "crates/licoup-native/src/platform/local_service/turn_control.rs",
        "tests/contract/client/local-service-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/local-service-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.file-security-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin file-security facade, fail-closed leaf ownership, and stable consumer boundary source proof",
      inputs: [
        "crates/licoup-native/src/platform/file_security.rs",
        "crates/licoup-native/src/platform/file_security/append_lock.rs",
        "crates/licoup-native/src/platform/file_security/atomic_replace.rs",
        "crates/licoup-native/src/platform/file_security/hardening.rs",
        "crates/licoup-native/src/platform/file_security/marker.rs",
        "crates/licoup-native/src/platform/file_security/policy.rs",
        "crates/licoup-native/src/platform/file_security/sync.rs",
        "crates/licoup-native/src/platform/file_security/unix_hardening.rs",
        "crates/licoup-native/src/platform/file_security/validation.rs",
        "crates/licoup-native/src/platform/file_security/windows_acl.rs",
        "tests/contract/client/file-security-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/file-security-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-state-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin client-state facade, independent local owners, bounded IO, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/client_state.rs",
        "crates/licoup-native/src/platform/client_state/accessors.rs",
        "crates/licoup-native/src/platform/client_state/activity.rs",
        "crates/licoup-native/src/platform/client_state/collections.rs",
        "crates/licoup-native/src/platform/client_state/migration.rs",
        "crates/licoup-native/src/platform/client_state/operations.rs",
        "crates/licoup-native/src/platform/client_state/paths.rs",
        "crates/licoup-native/src/platform/client_state/policy.rs",
        "crates/licoup-native/src/platform/client_state/redaction.rs",
        "crates/licoup-native/src/platform/client_state/serialization.rs",
        "crates/licoup-native/src/platform/client_state/snapshots.rs",
        "tests/contract/client/client-state-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-state-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.opencode-serve-source-bundle",
      kind: "regression-infrastructure",
      summary: "OpenCode thin serve facade, target policy, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/opencode_serve.rs",
        "crates/licoup-native/src/platform/opencode_serve/policy.rs",
        "crates/licoup-native/src/platform/opencode_serve/tests/**",
        "tests/contract/client/opencode-serve-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/opencode-serve-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.kilo-code-serve-source-bundle",
      kind: "regression-infrastructure",
      summary: "Kilo Code thin serve facade, target policy, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/kilo_code_serve.rs",
        "crates/licoup-native/src/platform/kilo_code_serve/policy.rs",
        "crates/licoup-native/src/platform/kilo_code_serve/tests/**",
        "tests/contract/client/kilo-code-serve-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/kilo-code-serve-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.openclaw-gateway-source-bundle",
      kind: "regression-infrastructure",
      summary: "OpenClaw Gateway thin facade, dedicated semantics, shared bounded primitives, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/openclaw_gateway.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/command.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/config.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/health.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/lifecycle.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/model.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/policy.rs",
        "tests/contract/client/openclaw-gateway-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/openclaw-gateway-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.claude-code-driver-source-bundle",
      kind: "regression-infrastructure",
      summary: "Claude Code thin facade, fixed streaming-input lane, exact live continuation, bounded IO, cleanup, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/claude_code_driver.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/claude_code.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/claude_code/events.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/claude_code/state.rs",
        "crates/licoup-native/src/platform/claude_code_driver/command.rs",
        "crates/licoup-native/src/platform/claude_code_driver/control.rs",
        "crates/licoup-native/src/platform/claude_code_driver/errors.rs",
        "crates/licoup-native/src/platform/claude_code_driver/execution.rs",
        "crates/licoup-native/src/platform/claude_code_driver/io.rs",
        "crates/licoup-native/src/platform/claude_code_driver/model.rs",
        "crates/licoup-native/src/platform/claude_code_driver/params.rs",
        "crates/licoup-native/src/platform/claude_code_driver/probe.rs",
        "crates/licoup-native/src/platform/claude_code_driver/supervision.rs",
        "crates/licoup-native/src/platform/claude_code_driver/transport.rs",
        "tests/contract/client/claude-code-driver-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/claude-code-driver-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.openclaw-driver-source-bundle",
      kind: "regression-infrastructure",
      summary: "OpenClaw thin facade, Gateway ACP attach, exact continuity, bounded IO, cleanup, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/openclaw_driver.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw/codec.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw/events.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw/protocol.rs",
        "crates/licoup-native/src/platform/openclaw_driver/continuity.rs",
        "crates/licoup-native/src/platform/openclaw_driver/errors.rs",
        "crates/licoup-native/src/platform/openclaw_driver/execution.rs",
        "crates/licoup-native/src/platform/openclaw_driver/io.rs",
        "crates/licoup-native/src/platform/openclaw_driver/model.rs",
        "crates/licoup-native/src/platform/openclaw_driver/params.rs",
        "crates/licoup-native/src/platform/openclaw_driver/probe.rs",
        "crates/licoup-native/src/platform/openclaw_driver/supervision.rs",
        "tests/contract/client/openclaw-driver-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/openclaw-driver-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.pi-driver-source-bundle",
      kind: "regression-infrastructure",
      summary: "Pi thin facade, official RPC JSONL, exact sessions, bounded IO, cleanup, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/pi_driver.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/pi.rs",
        "crates/licoup-native/src/platform/pi_driver/active_control.rs",
        "crates/licoup-native/src/platform/pi_driver/errors.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/pi/events.rs",
        "crates/licoup-native/src/platform/pi_driver/execution.rs",
        "crates/licoup-native/src/platform/pi_driver/io.rs",
        "crates/licoup-native/src/platform/pi_driver/model.rs",
        "crates/licoup-native/src/platform/pi_driver/params.rs",
        "crates/licoup-native/src/platform/pi_driver/probe.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/pi/protocol.rs",
        "crates/licoup-native/src/platform/pi_driver/sessions.rs",
        "crates/licoup-native/src/platform/pi_driver/supervision.rs",
        "crates/licoup-native/src/platform/pi_driver/tests/**",
        "tests/contract/client/pi-driver-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/pi-driver-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.native-stdio-rpc-source-bundle",
      kind: "regression-infrastructure",
      summary: "Ordinary-library ownership, dependency direction, bounds, and privacy evidence",
      inputs: [
        "apps/desktop/lib/src/platform/native_client/agent_service_stdio_rpc.dart",
        "apps/desktop/lib/src/platform/native_client/agent_service_stdio_rpc/**",
        "apps/desktop/test/native_client_component_boundary_test.dart",
        "apps/desktop/test/native_stdio_rpc_client_test.dart",
        "apps/desktop/test/native_stdio_rpc_line_framer_test.dart",
        "apps/desktop/test/native_stdio_rpc_protocol_test.dart",
        "apps/desktop/test/native_persistent_runtime_test.dart",
        "apps/desktop/test/agent_conversation_reattachment_test.dart",
        "tests/contract/client/native-stdio-rpc-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/native-stdio-rpc-source-bundle.test.mjs"],
        60_000,
      ),
    }),
]);
