import {
  rustLayer,
  rustBinaryTests,
  defineModule,
  secureMeshModule,
} from "../helpers.mjs";

export const RUST_CORE_MODULES = Object.freeze([
  defineModule({
      id: "rust.core.acp.composition",
      kind: "rust-core",
      summary: "ACP facade, shared protocol types, validation, and error boundaries",
      inputs: [
        "crates/lico-client-native/src/core/acp.rs",
        "crates/lico-client-native/src/core/acp/error.rs",
        "crates/lico-client-native/src/core/acp/types.rs",
        "crates/lico-client-native/src/core/acp/validation.rs",
        "crates/lico-client-native/src/core/acp/tests.rs",
      ],
      command: rustLayer("core::acp::tests"),
    }),
  defineModule({
      id: "rust.core.acp.requests",
      kind: "rust-core",
      summary: "ACP initialize, session lifecycle, prompt, cancel, and close requests",
      inputs: [
        "crates/lico-client-native/src/core/acp/requests.rs",
        "crates/lico-client-native/src/core/acp/tests/requests.rs",
      ],
      command: rustLayer("core::acp::tests::requests"),
    }),
  defineModule({
      id: "rust.core.acp.responses",
      kind: "rust-core",
      summary: "ACP response envelopes, session updates, and redacted remote errors",
      inputs: [
        "crates/lico-client-native/src/core/acp/responses.rs",
        "crates/lico-client-native/src/core/acp/tests/responses.rs",
      ],
      command: rustLayer("core::acp::tests::responses"),
    }),
  defineModule({
      id: "rust.core.acp.codec",
      kind: "rust-core",
      summary: "Bounded ACP JSON-line framing and decoding",
      inputs: [
        "crates/lico-client-native/src/core/acp/codec.rs",
        "crates/lico-client-native/src/core/acp/tests/codec.rs",
      ],
      command: rustLayer("core::acp::tests::codec"),
    }),
  defineModule({
      id: "rust.core.task-queue",
      kind: "rust-core",
      summary: "Bounded Rust FIFO queue, backpressure, disconnect, and ownership semantics",
      inputs: [
        "crates/lico-client-native/src/core/task_queue.rs",
      ],
      command: rustLayer("core::task_queue::tests"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.secret-custody-port",
      kind: "rust-core",
      summary: "Platform-neutral secret handles, authorization budget, and custody port",
      inputs: [
        "crates/lico-client-native/src/core/authorized_secure_record.rs",
        "crates/lico-client-native/src/core/secure_mesh_secret_store.rs",
        "crates/lico-client-native/src/core/secure_mesh_secret_store/authorization.rs",
        "crates/lico-client-native/src/core/secure_mesh_secret_store/handle.rs",
        "crates/lico-client-native/src/core/secure_mesh_secret_store/port.rs",
        "crates/lico-client-native/src/core/secure_mesh_secret_store/tests.rs",
      ],
      command: rustLayer("core::secure_mesh_secret_store::tests::"),
    }),
  defineModule({
      id: "rust.core.mcp.composition",
      kind: "rust-core",
      summary: "MCP facade, protocol revision, and shared adapter composition",
      inputs: [
        "crates/lico-client-native/src/core/mcp.rs",
        "crates/lico-client-native/src/core/mcp/tests.rs",
      ],
      command: rustLayer("core::mcp::tests"),
    }),
  defineModule({
      id: "rust.core.mcp.wire",
      kind: "rust-core",
      summary: "Bounded MCP JSON-RPC stdio and HTTP wire codec",
      inputs: [
        "crates/lico-client-native/src/core/mcp/wire.rs",
        "crates/lico-client-native/src/core/mcp/tests/wire.rs",
      ],
      command: rustLayer("core::mcp::tests::wire"),
    }),
  defineModule({
      id: "rust.core.mcp.transfer",
      kind: "rust-core",
      summary: "Exact-scope one-shot MCP external transfer approval",
      inputs: [
        "crates/lico-client-native/src/core/mcp/transfer.rs",
        "crates/lico-client-native/src/core/mcp/tests/transfer.rs",
      ],
      command: rustLayer("core::mcp::tests::transfer"),
    }),
  defineModule({
      id: "rust.core.safe-archive",
      kind: "rust-core",
      summary: "Bounded no-follow archive inspection and extraction",
      inputs: [
        "crates/lico-client-native/src/core/safe_archive.rs",
      ],
      command: rustLayer("core::safe_archive::tests"),
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh",
      summary: "Secure Client Mesh protocol versions and public envelope bounds",
      source: "secure_mesh",
      resources: [
        "crates/lico-client-native/resources/secure-client-relay-core-conformance.json",
        "crates/lico-client-native/resources/secure-client-relay-core-contract.json",
      ],
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.acp",
      summary: "ACP payload projection over encrypted Secure Client Mesh messages",
      source: "secure_mesh_acp",
      testInputs: [
        "crates/lico-client-native/src/core/secure_mesh_acp/tests/mod.rs",
      ],
    }),
  defineModule({
      id: "rust.core.secure-mesh.approval",
      kind: "rust-core",
      summary: "Encrypted remote-approval request, fanout, CAS response, and redacted inbox aggregate",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_approval.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/**",
      ],
      command: rustLayer("core::secure_mesh_approval::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.approval.request",
      kind: "rust-core",
      summary: "Bounded approval request validation and plaintext-detail rejection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_approval/input.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/request.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/tests/request.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_approval::tests::request::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.approval.fanout",
      kind: "rust-core",
      summary: "Per-trusted-endpoint encrypted fanout projection without plaintext operation detail",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_approval/request.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/projection.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/tests/fanout.rs",
      ],
      command: rustLayer("core::secure_mesh_approval::tests::fanout::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.approval.response",
      kind: "rust-core",
      summary: "First-valid-response CAS, trust, expiry, nonce, and inbox convergence",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_approval/ledger.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/projection.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/response.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/tests/response.rs",
      ],
      command: rustLayer("core::secure_mesh_approval::tests::response::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.approval.capability",
      kind: "rust-core",
      summary: "Fail-closed agent approval-bridge capability projection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_approval/capability.rs",
        "crates/lico-client-native/src/core/secure_mesh_approval/tests/capability.rs",
      ],
      command: rustLayer("core::secure_mesh_approval::tests::capability::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.capability.composition",
      kind: "rust-core",
      summary: "Stable restricted capability facade and public catalog-to-report flow",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_capability.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/composition.rs",
      ],
      command: rustLayer("core::secure_mesh_capability::tests::composition::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.capability.taxonomy",
      kind: "rust-core",
      summary: "Exhaustive constant-time capability identifiers, scopes, and serde",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_capability/taxonomy.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/taxonomy.rs",
      ],
      command: rustLayer("core::secure_mesh_capability::tests::taxonomy::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.capability.catalog",
      kind: "rust-core",
      summary: "Bounded embedded capability catalog, deterministic DAG, digest, and cache",
      inputs: [
        "crates/lico-client-native/resources/secure-mesh-capability-catalog.json",
        "crates/lico-client-native/src/core/secure_mesh_capability/catalog.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/catalog.rs",
      ],
      command: rustLayer("core::secure_mesh_capability::tests::catalog::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.capability.facts",
      kind: "rust-core",
      summary: "Bounded capability facts, evidence, reasons, and mandatory fact projection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_capability/facts.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/facts.rs",
      ],
      command: rustLayer("core::secure_mesh_capability::tests::facts::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.capability.custody",
      kind: "rust-core",
      summary: "Independent local secret-custody strategy and hardening selection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_capability/custody.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/custody.rs",
      ],
      command: rustLayer("core::secure_mesh_capability::tests::custody::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.capability.evaluation",
      kind: "rust-core",
      summary: "Single-pass bounded capability DAG evaluation and fail-closed policy",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_capability/evaluation.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/evaluation.rs",
      ],
      command: rustLayer("core::secure_mesh_capability::tests::evaluation::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.capability.report",
      kind: "rust-core",
      summary: "Deterministic exact-set capability report projection and schema",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_capability/report.rs",
        "crates/lico-client-native/src/core/secure_mesh_capability/tests/report.rs",
      ],
      command: rustLayer("core::secure_mesh_capability::tests::report::"),
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.capability-proof",
      summary: "Signed capability proof issuance, validation, and replay protection",
      source: "secure_mesh_capability_proof",
      testInputs: [
        "crates/lico-client-native/src/core/secure_mesh_capability_proof/tests/mod.rs",
      ],
    }),
  defineModule({
      id: "rust.core.secure-mesh.command",
      kind: "rust-core",
      summary: "Encrypted command policy, replay bounds, and platform-neutral execution contract",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_command.rs",
        "crates/lico-client-native/src/core/secure_mesh_command/tests.rs",
      ],
      command: rustLayer("core::secure_mesh_command::tests"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.command.schema",
      kind: "rust-core",
      summary: "Secure command schema decoding and session parameter projection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_command/schema.rs",
      ],
      command: rustLayer("core::secure_mesh_command::tests::agent_sessions_"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.command.replay",
      kind: "rust-core",
      summary: "Secure command idempotency and replay-ledger decisions",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_command/replay.rs",
      ],
      command: rustLayer("core::secure_mesh_command::tests::secure_mesh_command_idempotency"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.command.policy",
      kind: "rust-core",
      summary: "Secure command risk, confirmation, allowlist, and target policy",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_command/policy.rs",
      ],
      command: rustLayer("core::secure_mesh_command::tests::secure_mesh_command_gate_"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.command.runtime",
      kind: "rust-core",
      summary: "Secure command executor port, dispatch result validation, and failure taxonomy",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_command/runtime.rs",
      ],
      command: rustLayer("core::secure_mesh_command::tests::ready_agent_dispatch_"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.command.codec",
      kind: "rust-core",
      summary: "Secure command JSON evaluation and execution result codec",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_command/codec.rs",
      ],
      command: rustLayer("core::secure_mesh_command::tests::secure_mesh_command_execution_"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.crypto",
      kind: "rust-core",
      summary: "Payload cryptography, authenticated context, and private bodies",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_crypto.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/**",
      ],
      command: rustLayer("core::secure_mesh_crypto::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.crypto.roundtrip",
      kind: "rust-core",
      summary: "Supported payload-kind framing, sealing, opening, and metadata round trips",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_crypto/content_key.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/frame_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/public_payload.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/tests/roundtrip.rs",
      ],
      command: rustLayer("core::secure_mesh_crypto::tests::roundtrip::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.crypto.tamper",
      kind: "rust-core",
      summary: "AAD, key, authentication, and canonical base64url fail-closed behavior",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_crypto/aad_binding.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/header_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/key_derivation.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/public_payload.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/validation.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/tests/tamper.rs",
      ],
      command: rustLayer("core::secure_mesh_crypto::tests::tamper::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.crypto.padding",
      kind: "rust-core",
      summary: "Authenticated bounded bucket padding across power-of-two and large-payload ranges",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_crypto/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/frame_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/padding.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/public_payload.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/tests/padding.rs",
      ],
      command: rustLayer("core::secure_mesh_crypto::tests::padding::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.crypto.private-context",
      kind: "rust-core",
      summary: "Private-context framing, profile-bound headers, sealed metadata, and secret zeroization",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_crypto/frame_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/header_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/key_derivation.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/length_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/padding.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/private_context.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/tests/private_context.rs",
      ],
      command: rustLayer("core::secure_mesh_crypto::tests::private_context::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.crypto.stable-vector",
      kind: "rust-core",
      summary: "Deterministic headers and ciphertext digests for every stable payload kind",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_crypto/aad_binding.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/frame_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/header_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/key_derivation.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/padding.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/public_payload.rs",
        "crates/lico-client-native/src/core/secure_mesh_crypto/tests/stable_vector.rs",
      ],
      command: rustLayer("core::secure_mesh_crypto::tests::stable_vector::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.directory",
      kind: "rust-core",
      summary: "Encrypted endpoint directory records and deterministic reconciliation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_directory.rs",
        "crates/lico-client-native/src/core/secure_mesh_directory/authority.rs",
        "crates/lico-client-native/src/core/secure_mesh_directory/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_directory/proof.rs",
        "crates/lico-client-native/src/core/secure_mesh_directory/tests.rs",
      ],
      command: rustLayer("core::secure_mesh_directory::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file",
      kind: "rust-core",
      summary: "Secure Mesh encrypted-file public facade",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/mod.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file.key-proof",
      kind: "rust-core",
      summary: "Per-device and MLS file-key wrapping, authenticated context, and receipts",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/key_proof.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/primitives.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/key_proof.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::key_proof"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file.manifest-chunk",
      kind: "rust-core",
      summary: "Encrypted manifest and chunk codec, validation, and round trips",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/manifest_chunk_crypto.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/primitives.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/manifest_chunk_crypto.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::manifest_chunk_crypto"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file.delivery-projection",
      kind: "rust-core",
      summary: "Server-visible encrypted file delivery projection and metadata redaction",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file/delivery_projection.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/delivery_projection.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::delivery_projection"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file.transfer",
      kind: "rust-core",
      summary: "Bounded file-transfer queue, resume, acknowledgement, and purge state",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file/transfer.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/transfer.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::transfer"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file.route-policy",
      kind: "rust-core",
      summary: "Metadata-redacted encrypted file route policy",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file/json_input.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/route_policy.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/route_policy.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::route_policy"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file.receive-policy",
      kind: "rust-core",
      summary: "User-approved receive destination and explicit confirmation policy",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file/json_input.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/receive_policy.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/receive_policy.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::receive_policy"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.file.handoff-reseal",
      kind: "rust-core",
      summary: "Endpoint-specific decrypt-and-reseal handoff proof",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_file/handoff_reseal.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/json_input.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/handoff_reseal.rs",
        "crates/lico-client-native/src/core/secure_mesh_file/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_file::tests::handoff_reseal"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.lifecycle",
      kind: "rust-core",
      summary: "Secure Mesh lifecycle facade and aggregate focused regression",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/tests/mod.rs",
      ],
      command: rustLayer("core::secure_mesh_lifecycle::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.lifecycle.schema",
      kind: "rust-core",
      summary: "Lifecycle action schema, bounds, and canonical wire kinds",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/schema.rs",
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/tests/schema.rs",
      ],
      command: rustLayer("core::secure_mesh_lifecycle::tests::schema::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.lifecycle.policy",
      kind: "rust-core",
      summary: "Lifecycle policy evaluation and private identifier redaction",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/policy.rs",
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/tests/policy.rs",
      ],
      command: rustLayer("core::secure_mesh_lifecycle::tests::policy::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.lifecycle.projection",
      kind: "rust-core",
      summary: "Protected lifecycle status projection and typed content codec",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/projection.rs",
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/tests/projection.rs",
      ],
      command: rustLayer("core::secure_mesh_lifecycle::tests::projection::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.lifecycle.pairwise",
      kind: "rust-core",
      summary: "Pairwise lifecycle envelope sealing, opening, and plaintext rejection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/tests/pairwise.rs",
      ],
      command: rustLayer("core::secure_mesh_lifecycle::tests::pairwise::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.lifecycle.mls",
      kind: "rust-core",
      summary: "MLS lifecycle payload preparation and protected group adapter",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/mls.rs",
        "crates/lico-client-native/src/core/secure_mesh_lifecycle/tests/mls.rs",
      ],
      command: rustLayer("core::secure_mesh_lifecycle::tests::mls::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mlkem-braid",
      kind: "rust-core",
      summary: "ML-KEM Braid stable facade and aggregate focused regression",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mlkem_braid::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mlkem-braid.wire",
      kind: "rust-core",
      summary: "Strict canonical ML-KEM Braid wire model and bounded chunk encoding",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/wire.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/wire.rs",
      ],
      command: rustLayer("core::secure_mesh_mlkem_braid::tests::wire::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mlkem-braid.authenticator",
      kind: "rust-core",
      summary: "Ratcheted authenticator, incremental ML-KEM encapsulation, and output-key KDF",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/authenticator.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/encapsulation_kdf.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/output.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/secret.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/authenticator.rs",
      ],
      command: rustLayer("core::secure_mesh_mlkem_braid::tests::authenticator::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mlkem-braid.erasure",
      kind: "rust-core",
      summary: "Bounded GF(2^16) systematic erasure encoder and decoder",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/erasure_gf.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/erasure_encoder.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/erasure_decoder.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/erasure.rs",
      ],
      command: rustLayer("core::secure_mesh_mlkem_braid::tests::erasure::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mlkem-braid.transitions",
      kind: "rust-core",
      summary: "Fail-closed protocol state and bounded send/receive transitions",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/protocol_state.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/send_transition.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/receive_transition.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/transition.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/session.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/transitions.rs",
      ],
      command: rustLayer("core::secure_mesh_mlkem_braid::tests::transitions::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mlkem-braid.persistence",
      kind: "rust-core",
      summary: "Bounded secret-state persistence and fail-closed restore validation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/persistence.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/validation.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/persistence.rs",
      ],
      command: rustLayer("core::secure_mesh_mlkem_braid::tests::persistence::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mlkem-braid.rotation",
      kind: "rust-core",
      summary: "Stable epoch rotation, loss recovery, and persisted-state continuation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/rotation.rs",
        "crates/lico-client-native/src/core/secure_mesh_mlkem_braid/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mlkem_braid::tests::rotation::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls",
      kind: "rust-core",
      summary: "OpenMLS/ML-KEM public facade and aggregate focused regression",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mls::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls.runtime-self-test",
      kind: "rust-core",
      summary: "Cached side-effect-free OpenMLS create, join, and message runtime self-test",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls/runtime_self_test.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/runtime_self_test.rs",
      ],
      command: rustLayer("core::secure_mesh_mls::tests::runtime_self_test::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls.participant-key-package",
      kind: "rust-core",
      summary: "Identity-bound participant, signer, provider, and authenticated ML-KEM key package",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls/participant.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/key_package.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/provider.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/config.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/capability_extension.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/key_package.rs",
      ],
      command: rustLayer("core::secure_mesh_mls::tests::key_package::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls.group-protocol",
      kind: "rust-core",
      summary: "Group creation, join, membership, commit, sender binding, epoch, and replay protection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls/group_model.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/group_create.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/group_state.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/group_member.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/group_join.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/group_message.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/group_commit.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/group_protocol.rs",
      ],
      command: rustLayer("core::secure_mesh_mls::tests::group_protocol::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls.payload",
      kind: "rust-core",
      summary: "MLS exporter/ML-KEM hybrid payload key and bounded private-context wire codec",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls/group_payload.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/private_context_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/payload.rs",
      ],
      command: rustLayer("core::secure_mesh_mls::tests::payload::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls.provider-storage",
      kind: "rust-core",
      summary: "Zeroized provider secret persistence, selected custody, and authenticated reload",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls/provider.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/provider_storage.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/participant.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/provider_storage.rs",
      ],
      command: rustLayer("core::secure_mesh_mls::tests::provider_storage::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls.durable-store",
      kind: "rust-core",
      summary: "Private SQLite authority, authenticated reconciliation, CAS, rollback, and revocation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls/durable_store.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls/tests/durable_store.rs",
      ],
      command: rustLayer("core::secure_mesh_mls::tests::durable_store::"),
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.mls-pq-epoch",
      summary: "Post-quantum MLS epoch transition binding",
      source: "secure_mesh_mls_pq_epoch",
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls-product",
      kind: "rust-core",
      summary: "Product-facing MLS public facade",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls_product.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/mod.rs",
      ],
      command: rustLayer("core::secure_mesh_mls_product::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls-product.capability-proof",
      kind: "rust-core",
      summary: "MLS build binding, capability proof issuance, freshness, and intersection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls_product/capability_proof.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/helpers.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/capability_proof.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mls_product::tests::capability_proof"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls-product.identity-trust",
      kind: "rust-core",
      summary: "MLS credentials, OpenMLS signers, roster identity, and verified trust",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls_product/helpers.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/identity_trust.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/identity_trust.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mls_product::tests::identity_trust"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls-product.invitation-authorization",
      kind: "rust-core",
      summary: "Welcome, sender, epoch, roster, and directory-authorized member policy",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls_product/invitation_authorization.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/invitation_authorization.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mls_product::tests::invitation_authorization"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls-product.security-ledger",
      kind: "rust-core",
      summary: "Durable one-time input ledger, operation journal, reservations, and transactions",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls_product/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/helpers.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/ledger_transaction.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/security_ledger.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/security_ledger/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/security_ledger.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mls_product::tests::security_ledger"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls-product.group-flow",
      kind: "rust-core",
      summary: "Create, add, remove, join, and commit product group flows",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls_product/group_flow.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/group_flow.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mls_product::tests::group_flow"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.mls-product.payload-codec",
      kind: "rust-core",
      summary: "Identity-bound MLS payload sealing and opening",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_mls_product/payload_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/payload_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_mls_product/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_mls_product::tests::payload_codec"),
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.pqxdh",
      summary: "Hybrid PQXDH key agreement and key material bounds",
      source: "secure_mesh_pqxdh",
    }),
  defineModule({
      id: "rust.core.secure-mesh.prekey.composition",
      kind: "rust-core",
      summary: "Stable restricted prekey facade and test-only directory authorization support",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_prekey.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/composition.rs",
      ],
      command: rustLayer("core::secure_mesh_prekey::tests::composition::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.prekey.pairwise",
      kind: "rust-core",
      summary: "Pairwise signed curve/PQ prekeys, directory authorization, digests, and stable vectors",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_prekey/pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_prekey::tests::pairwise::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.prekey.key-package",
      kind: "rust-core",
      summary: "MLS KeyPackage bounds, suite policy, signing, verification, and stable vectors",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_prekey/key_package.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/key_package.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_prekey::tests::key_package::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.prekey.inventory",
      kind: "rust-core",
      summary: "Pure local prekey and KeyPackage low-water replenishment projection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_prekey/inventory.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/inventory.rs",
      ],
      command: rustLayer("core::secure_mesh_prekey::tests::inventory::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.prekey.validation",
      kind: "rust-core",
      summary: "Shared trust, clock, signature, framing, and digest validation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_prekey/validation.rs",
        "crates/lico-client-native/src/core/secure_mesh_prekey/tests/validation.rs",
      ],
      command: rustLayer("core::secure_mesh_prekey::tests::validation::"),
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.product-readiness",
      summary: "Secure Mesh product readiness evidence reduction",
      source: "secure_mesh_product_readiness",
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.composition",
      kind: "rust-core",
      summary: "Thin relay-envelope facade, mailbox module graph, and test registry",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/mailbox/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/mod.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::envelope"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.delivery",
      kind: "rust-core",
      summary: "Zeroizing delivery secret and opaque channel binding",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/delivery.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/delivery.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::delivery"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.mailbox-token",
      kind: "rust-core",
      summary: "Directional mailbox labels and canonical fixed-size token parsing",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/mailbox/direction.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/mailbox/token.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/mailbox_token.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::mailbox_token"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.schedule",
      kind: "rust-core",
      summary: "HKDF mailbox derivation and bounded current/previous rotation acceptance",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/mailbox/schedule.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/schedule.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::schedule"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.envelope",
      kind: "rust-core",
      summary: "Draft lifecycle, random delivery IDs, sealing, and opaque envelope accessors",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/draft.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/envelope.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/envelope.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::envelope"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.codec",
      kind: "rust-core",
      summary: "Strict wire schema, bounded canonical base64url, buckets, and constant-time compare",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/constant_time.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/wire.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/codec.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::codec"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.aad",
      kind: "rust-core",
      summary: "Canonical associated data for every mutable outer routing field",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/aad.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/aad.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::aad"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.header",
      kind: "rust-core",
      summary: "XChaCha20-Poly1305 private-header round trip and outer-field authentication",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/private_header.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/private_header_frame.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/header.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::header"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.header-negatives",
      kind: "rust-core",
      summary: "Header tamper, retired cipher layout, frame padding, wrong-key, and key-count negatives",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/private_header.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/private_header_frame.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/header_negatives.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests::header_negatives"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.relay-envelope.support",
      kind: "rust-core",
      summary: "Shared protocol constants and isolated relay-envelope fixture closure",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_relay_envelope/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_relay_envelope::tests"),
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.response",
      summary: "Encrypted response correlation and bounded result projection",
      source: "secure_mesh_response",
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.session-negotiation",
      summary: "Peer session negotiation, capability binding, and transcript checks",
      source: "secure_mesh_session_negotiation",
      testInputs: [
        "crates/lico-client-native/src/core/secure_mesh_session_negotiation/tests/mod.rs",
      ],
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.skill-sync",
      summary: "Explicitly approved encrypted skill synchronization",
      source: "secure_mesh_skill_sync",
    }),
  secureMeshModule({
      id: "rust.core.secure-mesh.sparse-pq-ratchet",
      summary: "Sparse post-quantum ratchet scheduling and recovery",
      source: "secure_mesh_sparse_pq_ratchet",
      testInputs: [
        "crates/lico-client-native/src/core/secure_mesh_sparse_pq_ratchet/tests/mod.rs",
      ],
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency",
      kind: "rust-core",
      summary: "Key transparency public facade and test registry",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/mod.rs",
      ],
      command: rustLayer("core::secure_mesh_transparency::tests::diagnostics"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.model",
      kind: "rust-core",
      summary: "Privacy-preserving directory labels and transparency wire models",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/constants.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/proofs.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/support.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::proofs::directory_leaf_serialization_exposes_only_an_opaque_scope_commitment",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.signature-freshness",
      kind: "rust-core",
      summary: "Pinned authority signatures and bounded signed-tree-head freshness",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/signature.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/log.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/signature_freshness.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_transparency::tests::signature_freshness"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.json-codec",
      kind: "rust-core",
      summary: "Bounded canonical JSON and signed-tree-head gossip codec",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/json_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/log.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/gossip.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/support.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::gossip::gossip_json_codec_round_trips_without_leaf_lists",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.inclusion-proof",
      kind: "rust-core",
      summary: "RFC 9162 inclusion proof verification and bounded path construction",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/proofs/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/proofs/hash.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/proofs/inclusion.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/log.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/proofs.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/support.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::proofs::rfc9162_inclusion_paths_are_logarithmic_and_exact",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.consistency-proof",
      kind: "rust-core",
      summary: "RFC 9162 append-only consistency verification and proof construction",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/proofs/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/proofs/hash.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/proofs/consistency.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/log.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/proofs.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/support.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::proofs::rfc9162_consistency_paths_are_logarithmic_and_exact",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.sparse-map",
      kind: "rust-core",
      summary: "Sparse-directory inclusion, absence, and cached empty-tree hashes",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/sparse_map.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/log.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/proofs.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_transparency::tests::proofs::sparse_map"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.diagnostics",
      kind: "rust-core",
      summary: "Explicitly non-authorizing diagnostic hash chain",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/diagnostics.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/diagnostics.rs",
      ],
      command: rustLayer("core::secure_mesh_transparency::tests::diagnostics"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.client-observation",
      kind: "rust-core",
      summary: "Durable client state construction and split-view observation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/client_state/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/client_state/observation.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/gossip.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/support.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::gossip::gossip_same_size_split_view_is_persisted",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.client-authorization.current",
      kind: "rust-core",
      summary: "Purpose-bound authorization at the current signed checkpoint",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/client_state/authorization.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_directory::tests::purpose_receipt_requires_target_label_at_current_sth_and_freshness_after_restart",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.client-authorization.absence",
      kind: "rust-core",
      summary: "Typed authenticated directory absence authorization",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/client_state/authorization.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_directory::tests::authenticated_absence_is_typed_and_bound_to_requested_label",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.client-authorization.gossip",
      kind: "rust-core",
      summary: "Fresh independent gossip prerequisite for directory authorization",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/client_state/authorization.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_directory::tests::directory_authorization_requires_persisted_fresh_peer_gossip",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.client-authorization.absence-rollback",
      kind: "rust-core",
      summary: "Fail-closed transition from a present directory label to absence",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/client_state/authorization.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_directory::tests::previously_present_label_cannot_become_absent_across_restart",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.persistence.schema",
      kind: "rust-core",
      summary: "Current transparency schema initialization and explicit reset boundary",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/mod.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/schema.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/sql.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/persistence.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::persistence::unsupported_schema_requires_explicit_state_reset",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.persistence.checkpoint-consistency",
      kind: "rust-core",
      summary: "Atomic checkpoint consistency and restart-safe rollback detection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/checkpoint.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/persistence.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::persistence::sqlite_checkpoint_requires_consistency_and_persists_rollback_across_restart",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.persistence.checkpoint-retention",
      kind: "rust-core",
      summary: "Bounded checkpoint retention without weakening rollback protection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/checkpoint.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/persistence.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::persistence::checkpoint_retention_is_bounded_without_weakening_latest_rollback_guard",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.persistence.directory-quota",
      kind: "rust-core",
      summary: "Directory-label and purpose-authorization quotas with stale reclamation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/directory.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/persistence.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::persistence::directory_label_and_authorization_quotas_are_bounded_with_stale_reclamation",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.persistence.gossip",
      kind: "rust-core",
      summary: "Bounded gossip observations bound to full signed tree heads",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/gossip.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/gossip.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::gossip::gossip_observations_bind_distinct_issue_times_for_the_same_tree_view",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.persistence.time-watermark",
      kind: "rust-core",
      summary: "Durable time watermark preventing clock rollback and freshness revival",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/time_guard.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/persistence.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::persistence::durable_time_watermark_prevents_clock_rollback_and_expiry_revival",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.transparency.persistence.authenticated-time",
      kind: "rust-core",
      summary: "Authenticate tree heads before persisting temporal security blocks",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_transparency/persistence/time_guard.rs",
        "crates/lico-client-native/src/core/secure_mesh_transparency/tests/persistence.rs",
      ],
      command: rustLayer(
        "core::secure_mesh_transparency::tests::persistence::unauthenticated_temporal_input_cannot_persist_security_block",
      ),
    }),
  defineModule({
      id: "rust.core.secure-mesh.trust",
      kind: "rust-core",
      summary: "Endpoint identity, signed trust, verification observation, policy, and protected-send aggregate",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_trust.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/**",
      ],
      command: rustLayer("core::secure_mesh_trust::tests::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.trust.cross-signature",
      kind: "rust-core",
      summary: "Identity-bound device cross-signature issuance and tamper rejection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_trust/codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/identity.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/signature.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/tests/signature.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/tests/support.rs",
      ],
      command: rustLayer("core::secure_mesh_trust::tests::signature::secure_mesh_device_cross_signature_verifies_and_rejects_tamper"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.trust.record",
      kind: "rust-core",
      summary: "Locally signed peer trust record, expiry, peer binding, and JSON codec",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_trust/record.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/signature.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/input.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/tests/signature.rs",
      ],
      command: rustLayer("core::secure_mesh_trust::tests::signature::secure_mesh_device_trust_record_signature_binds_peer_and_expiry"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.trust.verification",
      kind: "rust-core",
      summary: "Symmetric 60-digit SAS, fingerprint-only QR payload, and key-change detection",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_trust/codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/identity.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/verification.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/tests/verification.rs",
      ],
      command: rustLayer("core::secure_mesh_trust::tests::verification::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.trust.policy",
      kind: "rust-core",
      summary: "Fail-closed caller-advisory trust and persisted-record authorization policy",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_trust/decision.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/input.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/policy.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/tests/policy.rs",
      ],
      command: rustLayer("core::secure_mesh_trust::tests::policy::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.trust.authorization",
      kind: "rust-core",
      summary: "Verify-before-send authorization for every protected payload class",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_trust/authorization.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/model.rs",
        "crates/lico-client-native/src/core/secure_mesh_trust/tests/authorization.rs",
      ],
      command: rustLayer("core::secure_mesh_trust::tests::authorization::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-codec",
      kind: "rust-core",
      summary: "Pairwise encrypted wire codec, relay headers, and rollback behavior",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/codec.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::codec"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-key-ratchet.core",
      kind: "rust-core",
      summary: "Atomic pairwise ratchet, KDF, skipped-key, replay, and post-compromise state",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/key_ratchet.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/key_ratchet.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::key_ratchet"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-key-ratchet.payload-adapter",
      kind: "rust-core",
      summary: "Content payload sealing, opening, AAD binding, and fail-closed state rollback",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/key_ratchet/payload_adapter.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/key_ratchet_payload_adapter.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::key_ratchet_payload_adapter::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-key-ratchet.relay-codec",
      kind: "rust-core",
      summary: "Opaque relay envelope and encrypted private-header adaptation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/key_ratchet/relay_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/key_ratchet_relay_codec.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::key_ratchet_relay_codec::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-manager-fanout",
      kind: "rust-core",
      summary: "Independent multi-device sessions, fanout, acknowledgement, and purge",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/manager_fanout.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/manager_fanout.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::manager_fanout"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-persistence",
      kind: "rust-core",
      summary: "Aggregate pairwise encrypted durable state, replay ledgers, reset, and recovery semantics",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::persistence_"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-persistence.capability-replay",
      kind: "rust-core",
      summary: "Atomic capability-proof consumption and monotonic replay-time watermark",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/capability_proof.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/replay_watermark.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/session_commit.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/persistence_capability.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::persistence_capability::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-persistence.prekey-consumption",
      kind: "rust-core",
      summary: "Atomic local and remote one-time prekey consumption with durable tombstones",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/initial_write.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/local_prekey.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/remote_prekey.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/persistence_prekey.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::persistence_prekey::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-persistence.recovery",
      kind: "rust-core",
      summary: "Bound snapshot codec, namespace binding, restart recovery, and anti-reintroduction guards",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/namespace_binding.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/public_snapshot.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/restoration_validation.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/secret_snapshot.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/session_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/session_read.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/persistence_recovery.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::persistence_recovery::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-persistence.schema-reset",
      kind: "rust-core",
      summary: "Destructive reset of all persistent state for an incompatible schema",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/schema.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/store_open.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/persistence_schema_reset.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::persistence_schema_reset::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-persistence.secret-boundary",
      kind: "rust-core",
      summary: "Zeroizing secret-store serialization, namespace binding, and SQLite redaction",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/namespace_binding.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/secret_cleanup.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/secret_snapshot.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/secret_store_io.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/persistence_secret_boundary.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::persistence_secret_boundary::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-persistence.transaction",
      kind: "rust-core",
      summary: "Compare-and-swap commits, cleanup retry, replay rollback rejection, and revocation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/revocation.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/session_commit.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/persistence/store_model.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/persistence_transaction.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::persistence_transaction::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-runtime-self-test",
      kind: "rust-core",
      summary: "Minimal pairwise runtime cryptographic readiness self-test",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/runtime_self_test.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/runtime_self_test.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::runtime_self_test"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-session-negotiation.handshake-machine",
      kind: "rust-core",
      summary: "Atomic pairwise initiate, accept, finish, and capability-confirmed state machine",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/session_negotiation.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/session_negotiation/handshake_machine.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/session_negotiation.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::session_negotiation"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-session-negotiation.capability-binding",
      kind: "rust-core",
      summary: "Build protocol digest and exact capability proof request/context binding",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/session_negotiation/capability_binding.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/session_negotiation_capability_binding.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::session_negotiation_capability_binding::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-session-negotiation.key-schedule",
      kind: "rust-core",
      summary: "PQXDH classical collection and zeroized initial/capability-bound key schedules",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/session_negotiation/key_schedule.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/session_negotiation_key_schedule.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::session_negotiation_key_schedule::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-session-negotiation.transcript-codec",
      kind: "rust-core",
      summary: "Handshake DTOs, canonical transcripts, signatures, confirmations, and session IDs",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/session_negotiation/transcript_codec.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/session_negotiation_transcript_codec.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::session_negotiation_transcript_codec::"),
    }),
  defineModule({
      id: "rust.core.secure-mesh.pairwise-session-negotiation.input-validation",
      kind: "rust-core",
      summary: "Endpoint, local key material, intro shape, and cryptographic input validation",
      inputs: [
        "crates/lico-client-native/src/core/secure_mesh_pairwise/session_negotiation/input_validation.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/test_support.rs",
        "crates/lico-client-native/src/core/secure_mesh_pairwise/tests/session_negotiation_input_validation.rs",
      ],
      command: rustLayer("core::secure_mesh_pairwise::tests::session_negotiation_input_validation::"),
    }),
  defineModule({
      id: "rust.bin.secure-mesh-kt-mock",
      kind: "rust-core",
      summary: "Feature-gated local Key Transparency acceptance mock",
      inputs: [
        "crates/lico-client-native/src/bin/lico-secure-mesh-kt-mock.rs",
      ],
      command: rustBinaryTests(
        "lico-secure-mesh-kt-mock",
        "tests::",
        ["secure-mesh-acceptance-mock-kt"],
      ),
    })
]);
