import { command, node, defineModule } from "../../helpers.mjs";

export const ADAPTERS_MODULES = Object.freeze([
  defineModule({
    id: "regression.agent-sdk",
    kind: "regression-infrastructure",
    summary: "Real language-neutral Agent sample processes and the shared descriptor carrier",
    inputs: [
      "sdk/agent-adapter/**",
      "extensions/generic/**",
      "tests/integration/agent_sdk/**",
      "crates/licoup-extension-contracts/src/**",
      "schemas/extensions/**",
    ],
    command: node("tools/scripts/client-toolchain-runner.mjs", [
      "--", "python3", "-B", "tests/integration/agent_sdk/run_tests.py",
    ], 5 * 60_000),
  }),
  defineModule({
      id: "regression.extension-agent-sample",
      kind: "regression-infrastructure",
      summary: "Execute the offline extension Agent sample through its real bounded JSON-RPC carrier",
      inputs: [
        "crates/licoup-extension-contracts/samples/echo-agent/**",
        "crates/licoup-extension-contracts/tests/test_echo_agent.py",
      ],
      command: node("tools/scripts/client-toolchain-runner.mjs", [
        "--",
        "python3",
        "-B",
        "crates/licoup-extension-contracts/tests/test_echo_agent.py",
      ]),
    }),
  defineModule({
      id: "regression.agent-scan-paths",
      kind: "regression-infrastructure",
      summary: "Agent discovery allowlist TOML, env-only home, and no unused-agent other-app probe",
      inputs: [
        "crates/licoup-agent-targets/resources/agent-scan-paths.toml",
        "crates/licoup-agent-targets/src/domain/targets/scan_paths.rs",
        "crates/licoup-agent-targets/src/domain/targets/binaries.rs",
        "crates/licoup-agent-targets/src/domain/targets/platform_paths.rs",
        "crates/licoup-foundation/src/platform/paths.rs",
        "crates/licoup-native/src/domain/conversation/history_discovery.rs",
        "apps/desktop/lib/src/platform/native_client/agent_service_actions.dart",
        "apps/desktop/lib/src/application/controller/client_lifecycle_facade.dart",
        "apps/desktop/lib/src/application/controller/client_navigation_facade.dart",
        "tests/contract/client/agent-scan-paths.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/agent-scan-paths.test.mjs"],
        30_000,
      ),
    }),
  defineModule({
      id: "regression.codex-app-server-source-bundle",
      kind: "regression-infrastructure",
      summary: "Codex app-server split ownership, fail-closed protocol, bounded IO, and redaction contract",
      inputs: [
        "crates/licoup-native/src/platform/codex_app_server.rs",
        "crates/licoup-native/src/platform/codex_app_server/**",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/codex.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/codex/**",
        "tests/contract/client/codex-app-server-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/codex-app-server-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-agent-usage",
      kind: "regression-infrastructure",
      summary: "Local-token agent-usage evidence gate over native, Flutter, and docs contracts",
      inputs: [
        "apps/desktop/scripts/verify-client-agent-usage.mjs",
        "crates/licoup-native/src/domain/agent_usage/workflow_ledger.rs",
        "apps/desktop/lib/src/contracts/agent_usage_models.dart",
        "apps/desktop/lib/src/application/features/agents/controller/agent_usage_daily_cache.dart",
        "apps/desktop/lib/src/backend/features/agents/services/agent_usage_service.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_panel_widgets.dart",
        "apps/desktop/lib/src/composition/binding_shell_renderer.dart",
        "apps/desktop/lib/src/composition/binding_shell_renderer/shell_destinations.dart",
        "apps/desktop/lib/src/frontend/shell/client_shell.dart",
        "apps/desktop/lib/src/frontend/l10n/lico_strings_labels.dart",
        "apps/desktop/test/agent_usage_workflow_test.dart",
        "apps/desktop/test/fixtures/agent_usage_panel/usage_panel_fixtures.dart",
        "docs/functionality/CLIENT-DESKTOP.md",
        "docs/functionality/USER-GUIDE.md",
        "docs/functionality/USER-GUIDE.zh-CN.md",
        "docs/architecture/README.md",
        "docs/architecture/README.zh-CN.md",
      ],
      command: node("apps/desktop/scripts/verify-client-agent-usage.mjs", [], 60_000),
    }),
  defineModule({
      id: "regression.agent-usage-codex-source-bundle",
      kind: "regression-infrastructure",
      summary: "Codex usage split ownership, local-only scanning, cache, and privacy boundaries",
      inputs: [
        "crates/licoup-native/src/domain/agent_usage/agent_usage_codex.rs",
        "crates/licoup-native/src/domain/agent_usage/agent_usage_codex/**",
        "crates/licoup-native/tests/agent_usage_incremental_cache.rs",
        "crates/licoup-native/tests/agent_usage_cache_cases/**",
        "tests/contract/client/agent-usage-codex-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/agent-usage-codex-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.cursor-openagent-source-bundle",
      kind: "regression-infrastructure",
      summary: "Cursor/OpenAgent exact ownership, explicit parser DAG, read-only bounded SQLite codec, and dedicated regressions",
      inputs: [
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/codec.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/composition.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/cursor.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/cursor_cli.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/cursor_projection.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/fallback.rs",
        "crates/licoup-native/src/domain/conversation/history/cursor_openagent/openagent.rs",
        "tests/contract/client/cursor-openagent-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/cursor-openagent-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.opencode-serve-source-bundle",
      kind: "regression-infrastructure",
      summary: "OpenCode thin serve facade, target policy, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/opencode_serve.rs",
        "crates/licoup-native/src/platform/opencode_serve/policy.rs",
        "crates/licoup-native/src/platform/opencode_serve/tests/**",
        "tests/contract/client/opencode-serve-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/opencode-serve-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.kilo-code-serve-source-bundle",
      kind: "regression-infrastructure",
      summary: "Kilo Code thin serve facade, target policy, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/kilo_code_serve.rs",
        "crates/licoup-native/src/platform/kilo_code_serve/policy.rs",
        "crates/licoup-native/src/platform/kilo_code_serve/tests/**",
        "tests/contract/client/kilo-code-serve-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/kilo-code-serve-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.openclaw-gateway-source-bundle",
      kind: "regression-infrastructure",
      summary: "OpenClaw Gateway thin facade, dedicated semantics, shared bounded primitives, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/openclaw_gateway.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/command.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/config.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/health.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/lifecycle.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/model.rs",
        "crates/licoup-native/src/platform/openclaw_gateway/policy.rs",
        "tests/contract/client/openclaw-gateway-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/openclaw-gateway-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.claude-code-driver-source-bundle",
      kind: "regression-infrastructure",
      summary: "Claude Code thin facade, fixed streaming-input lane, exact live continuation, bounded IO, cleanup, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/claude_code_driver.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/claude_code.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/claude_code/events.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/claude_code/state.rs",
        "crates/licoup-native/src/platform/claude_code_driver/command.rs",
        "crates/licoup-native/src/platform/claude_code_driver/control.rs",
        "crates/licoup-native/src/platform/claude_code_driver/errors.rs",
        "crates/licoup-native/src/platform/claude_code_driver/execution.rs",
        "crates/licoup-native/src/platform/claude_code_driver/io.rs",
        "crates/licoup-native/src/platform/claude_code_driver/model.rs",
        "crates/licoup-native/src/platform/claude_code_driver/params.rs",
        "crates/licoup-native/src/platform/claude_code_driver/probe.rs",
        "crates/licoup-native/src/platform/claude_code_driver/supervision.rs",
        "crates/licoup-native/src/platform/claude_code_driver/transport.rs",
        "tests/contract/client/claude-code-driver-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/claude-code-driver-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.openclaw-driver-source-bundle",
      kind: "regression-infrastructure",
      summary: "OpenClaw thin facade, Gateway ACP attach, exact continuity, bounded IO, cleanup, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/openclaw_driver.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw/codec.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw/events.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/openclaw/protocol.rs",
        "crates/licoup-native/src/platform/openclaw_driver/continuity.rs",
        "crates/licoup-native/src/platform/openclaw_driver/errors.rs",
        "crates/licoup-native/src/platform/openclaw_driver/execution.rs",
        "crates/licoup-native/src/platform/openclaw_driver/io.rs",
        "crates/licoup-native/src/platform/openclaw_driver/model.rs",
        "crates/licoup-native/src/platform/openclaw_driver/params.rs",
        "crates/licoup-native/src/platform/openclaw_driver/probe.rs",
        "crates/licoup-native/src/platform/openclaw_driver/supervision.rs",
        "tests/contract/client/openclaw-driver-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/openclaw-driver-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.pi-driver-source-bundle",
      kind: "regression-infrastructure",
      summary: "Pi thin facade, official RPC JSONL, exact sessions, bounded IO, cleanup, and privacy source proof",
      inputs: [
        "crates/licoup-native/src/platform/pi_driver.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/pi.rs",
        "crates/licoup-native/src/platform/pi_driver/active_control.rs",
        "crates/licoup-native/src/platform/pi_driver/errors.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/pi/events.rs",
        "crates/licoup-native/src/platform/pi_driver/execution.rs",
        "crates/licoup-native/src/platform/pi_driver/io.rs",
        "crates/licoup-native/src/platform/pi_driver/model.rs",
        "crates/licoup-native/src/platform/pi_driver/params.rs",
        "crates/licoup-native/src/platform/pi_driver/probe.rs",
        "crates/licoup-native/src/platform/native_agent_parser/adapters/pi/protocol.rs",
        "crates/licoup-native/src/platform/pi_driver/sessions.rs",
        "crates/licoup-native/src/platform/pi_driver/supervision.rs",
        "crates/licoup-native/src/platform/pi_driver/tests/**",
        "tests/contract/client/pi-driver-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/pi-driver-source-bundle.test.mjs"],
        60_000,
      ),
    }),
]);
