import { command, node, defineModule } from "../../helpers.mjs";

export const INFRASTRUCTURE_MODULES = Object.freeze([
  defineModule({
    id: "regression.public-privacy-scanner",
    kind: "regression-infrastructure",
    summary: "Public audit CLI candidate binding, redacted results and failure handling",
    inputs: ["tools/scripts/repo-local-info-hygiene.mjs", "tests/contract/client/repository-privacy-scanner.test.mjs"],
    command: command("node", ["--test", "tests/contract/client/repository-privacy-scanner.test.mjs"], 60_000),
  }),
  defineModule({
    id: "regression.extension-ui-schema",
    kind: "regression-infrastructure",
    summary: "Strict published UI schema validation and resource-view/secret-field boundaries",
    inputs: ["schemas/extensions/ui.schema.json", "schemas/extensions/graph-resource.schema.json", "crates/licoup-extension-contracts/tests/ui_schema.test.mjs", "crates/licoup-extension-contracts/src/ui.rs"],
    command: command("node", ["--test", "crates/licoup-extension-contracts/tests/ui_schema.test.mjs"], 120_000),
  }),
  defineModule({
    id: "migration.client-state-diagnostic",
    kind: "architecture",
    summary: "Read-only client-state diagnosis and single-step repair against the native migration admission",
    inputs: [
      "tests/contract/client/client-state-migration/diagnostic.test.mjs",
      "tests/contract/client/client-state-migration/admission-mirror.test.mjs",
      "tests/contract/client/client-state-migration/source-invariants.test.mjs",
      "tests/contract/client/client-state-migration/support.mjs",
      "tools/scripts/client-state-migration.mjs",
      "tools/scripts/client-state-migration/**",
      "crates/licoup-native/src/domain/client_state_migration.rs",
      "crates/licoup-native/src/domain/client_state_migration/**",
      "crates/licoup-native/resources/client-state-migration-frontier.json",
      "crates/licoup-client-state/src/policy.rs",
      "crates/licoup-client-state/src/migration.rs",
      "crates/licoup-conversation/src/store/mod.rs",
    ],
    command: command("node", [
      "--test",
      "tests/contract/client/client-state-migration/diagnostic.test.mjs",
      "tests/contract/client/client-state-migration/admission-mirror.test.mjs",
      "tests/contract/client/client-state-migration/source-invariants.test.mjs",
    ], 20 * 60_000),
  }),
  defineModule({
      id: "regression.cli-command-admission-source-bundle",
      kind: "regression-infrastructure",
      summary: "Single-registry typed CLI admission source ownership and migration closure",
      inputs: [
        "crates/licoup-native/src/ffi/commands/**",
        "tests/contract/client/cli-command-admission-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/cli-command-admission-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.infrastructure",
      kind: "regression-infrastructure",
      summary: "Module catalog, changed-file selection, and safe process execution",
      inputs: [
        "CONTRIBUTING.md",
        "CONTRIBUTING.zh-CN.md",
        "package.json",
        "package-lock.json",
        "tools/regression/**",
        "tools/scripts/client-module-regression.mjs",
        "tools/scripts/client-module-regression-self-test.mjs",
        "tools/scripts/client-regression-foundation.mjs",
        "tools/scripts/client-regression-frontend.mjs",
        "tools/scripts/client-regression-backend.mjs",
        "tools/scripts/client-regression-integration.mjs",
        "tools/scripts/client-regression-scenarios.mjs",
        "tools/scripts/client-regression-environment.mjs",
        "tests/contract/client/client-module-regression.test.mjs",
        "tests/contract/client/client-agent-regression-entries.test.mjs",
        "tests/contract/client/client-platform-regression-entries.test.mjs",
        "tests/contract/client/client-regression-batching.test.mjs",
        "tests/contract/client/client-regression-report.test.mjs",
        "tests/contract/client/flutter-native-regression-stats.test.mjs",
        "tests/contract/client/rust-regression-toolchain-stats.test.mjs",
        "tests/product-e2e/cli/agent-conversations/deepseek-harness/conversation.test.mjs",
      ],
      command: node("tools/scripts/client-module-regression-self-test.mjs", [], 60_000),
    }),
  defineModule({
      id: "regression.public-client-docs",
      kind: "regression-infrastructure",
      summary: "Public bilingual entry links resolve to maintained documents",
      inputs: [
        "README.md",
        "README.zh-CN.md",
        "CONTRIBUTING.md",
        "CONTRIBUTING.zh-CN.md",
        "SECURITY.md",
        "SECURITY.zh-CN.md",
        "docs/functionality/USER-GUIDE.md",
        "docs/functionality/USER-GUIDE.zh-CN.md",
        "docs/architecture/README.md",
        "docs/architecture/README.zh-CN.md",
        "docs/COMPATIBILITY.md",
        "docs/COMPATIBILITY.zh-CN.md",
        "crates/licoup-agent-drivers/resources/agent-native-capabilities.json",
        "tools/scripts/client-support-matrix.mjs",
        "tests/contract/client/public-client-docs.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/public-client-docs.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.documentation-governance",
      kind: "regression-infrastructure",
      summary: "Formal document layout, public Git candidate, links, language pairs, and local-asset isolation",
      inputs: [
        "tools/development/**",
        "docs/modules/**",
        "docs/CLOSURE.md",
        "AGENTS.md",
        ".gitignore",
        "package.json",
        "README.md",
        "README.zh-CN.md",
        "PRODUCT.md",
        "CONTRIBUTING.md",
        "CONTRIBUTING.zh-CN.md",
        "CODE_OF_CONDUCT.md",
        "CHANGELOG.md",
        "LICENSE",
        "SECURITY.md",
        "SECURITY.zh-CN.md",
        "docs/README.md",
        "docs/RUNBOOK.md",
        "docs/COMPATIBILITY.md",
        "docs/COMPATIBILITY.zh-CN.md",
        "docs/ENTITY-CONFIG-LAYOUT.md",
        "docs/architecture/**",
        "docs/functionality/**",
        "docs/protocols/**",
        "docs/examples/**",
        "docs/adrs/**",
        "apps/desktop/README.md",
        "crates/licoup-native/README.md",
        "crates/lico-catalog-convergence/README.md",
        "packages/contracts/client/README.md",
        "packages/protocols/native-client/README.md",
        "tools/verify-documentation.mjs",
        "tools/scripts/client-support-matrix.mjs",
        "crates/licoup-agent-drivers/resources/agent-native-capabilities.json",
      ],
      command: node("tools/verify-documentation.mjs", [], 60_000),
    }),
  defineModule({
      id: "regression.client-update-source-bundle",
      kind: "regression-infrastructure",
      summary: "Fail-closed client-update source split, release authority, and redaction contract",
      inputs: [
        "crates/licoup-native/src/domain/client_update.rs",
        "crates/licoup-native/src/domain/client_update/**",
        "tests/contract/client/client-update-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-update-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-architecture-modules",
      kind: "regression-infrastructure",
      summary: "Terminal Presentation Boundary rules, synthetic violations, thin architecture entry, and frozen phase ordering",
      inputs: [
        "tools/verify-client-boundary.mjs",
        "apps/desktop/scripts/verify-client-architecture.mjs",
        "apps/desktop/scripts/client-architecture/assertions.mjs",
        "apps/desktop/scripts/client-architecture/context.mjs",
        "apps/desktop/scripts/client-architecture/filesystem.mjs",
        "apps/desktop/scripts/client-architecture/checks/composition.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/mobile-relay-bridges.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/physical-layers-and-libraries.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/presentation-boundary.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/shell-isolation-and-native-stdio.mjs",
        "apps/desktop/scripts/client-architecture/checks/foundations.mjs",
        "apps/desktop/scripts/client-architecture/checks/native.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/command-and-file-transport.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/conversation-domain.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/crate-core-and-facade-bounds.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/domain-and-crypto-boundaries.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-authority-and-custody.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-foundations-and-local-archive.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/target-readiness-reducer.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/android-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/ios-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/runtime-drivers-and-local-service.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/target-serve-and-gateway.mjs",
        "apps/desktop/scripts/client-architecture/checks/privacy.mjs",
        "tests/contract/client/client-architecture-modules.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-architecture-modules.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.verify-client-plan-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin plan-gate facade, static check leaves, shared readers, and dedicated leaf regressions",
      inputs: [
        "apps/desktop/scripts/verify-client-plan.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/android-ios.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/client-boundary.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/crypto-redaction-handoff.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/docs-readiness.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/evidence-routing.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/linux-windows.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/package-and-runner.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/physical-evidence.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/secret-store.mjs",
        "apps/desktop/scripts/verify-client-plan/checks/trust-release.mjs",
        "apps/desktop/scripts/verify-client-plan/dynamic-self-tests.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/assert.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/context.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/fs.mjs",
        "apps/desktop/scripts/verify-client-plan/shared/sanitize.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-leaf-fixtures.test.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-ordering.test.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-privacy.test.mjs",
        "tests/contract/client/verify-client-plan/verify-client-plan-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        [
          "--test",
          "tests/contract/client/verify-client-plan/verify-client-plan-leaf-fixtures.test.mjs",
          "tests/contract/client/verify-client-plan/verify-client-plan-ordering.test.mjs",
          "tests/contract/client/verify-client-plan/verify-client-plan-privacy.test.mjs",
          "tests/contract/client/verify-client-plan/verify-client-plan-source-bundle.test.mjs",
        ],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-toolchain-runner-source-bundle",
      kind: "regression-infrastructure",
      summary: "Client toolchain runner leaf ownership and thin facade contract",
      inputs: [
        "tests/contract/client/client-toolchain-runner-source-bundle.test.mjs",
        "tools/scripts/client-toolchain-runner.mjs",
        "tools/scripts/client-toolchain-runner/artifacts.mjs",
        "tools/scripts/client-toolchain-runner/cli.mjs",
        "tools/scripts/client-toolchain-runner/constants.mjs",
        "tools/scripts/client-toolchain-runner/flutter.mjs",
        "tools/scripts/client-toolchain-runner/process.mjs",
        "tools/scripts/client-toolchain-runner/pub-cache.mjs",
        "tools/scripts/client-toolchain-runner/run.mjs",
        "tools/scripts/client-toolchain-runner/windows.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-toolchain-runner-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.contracts-client",
      kind: "regression-infrastructure",
      summary: "Client contract schema validation for checked-in semantic envelopes",
      inputs: [
        "tests/contract/client/contracts-client.test.mjs",
        "packages/contracts/client/semantic-conversation.schema.json",
      ],
      command: node("tests/contract/client/contracts-client.test.mjs", [], 60_000),
    }),
  defineModule({
      id: "architecture.client-boundaries",
      kind: "architecture",
      summary: "Fast client layer, composition, native-module, and platform boundary gate",
      inputs: [
        "tools/verify-client-boundary.mjs",
        "apps/desktop/scripts/verify-client-architecture.mjs",
        "apps/desktop/scripts/client-architecture/assertions.mjs",
        "apps/desktop/scripts/client-architecture/context.mjs",
        "apps/desktop/scripts/client-architecture/filesystem.mjs",
        "apps/desktop/scripts/client-architecture/checks/composition.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/mobile-relay-bridges.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/physical-layers-and-libraries.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/presentation-boundary.mjs",
        "apps/desktop/scripts/client-architecture/checks/flutter/shell-isolation-and-native-stdio.mjs",
        "apps/desktop/scripts/client-architecture/checks/foundations.mjs",
        "apps/desktop/scripts/client-architecture/checks/native.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/command-and-file-transport.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/conversation-domain.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/crate-core-and-facade-bounds.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/domain-and-crypto-boundaries.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-authority-and-custody.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/secure-mesh-foundations-and-local-archive.mjs",
        "apps/desktop/scripts/client-architecture/checks/native/target-readiness-reducer.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/android-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/ios-secure-mesh.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/runtime-drivers-and-local-service.mjs",
        "apps/desktop/scripts/client-architecture/checks/platform/target-serve-and-gateway.mjs",
        "apps/desktop/scripts/client-architecture/checks/privacy.mjs",
        "apps/desktop/packaging.modules.json",
        "crates/licoup-agent-drivers/resources/agent-conversation-drivers.json",
        // The architecture checks read the moved trees by hand, and every other
        // crate's own source is named here as one glob, so `licoup-agent-drivers`
        // is named the same way: the host's adapter composition and the ACP
        // session transport and local service control plane it still reads all
        // live under it now, and a change to any of them can break this gate.
        "crates/licoup-agent-drivers/src/**",
        "apps/desktop/lib/**",
        "apps/desktop/integration_test/**",
        "apps/desktop/test/agents_workspace/**",
        "apps/desktop/test/fixtures/client_controller/**",
        "apps/desktop/test/fixtures/client_controller_scenarios.dart",
        "apps/desktop/android/**",
        "apps/desktop/ios/**",
        "crates/licoup-foundation/Cargo.toml",
        "crates/licoup-foundation/src/**",
        "crates/licoup-native/Cargo.toml",
        "crates/licoup-native/src/**",
        "crates/licoup-agent-targets/Cargo.toml",
        "crates/licoup-agent-targets/src/**",
        "crates/licoup-relay/Cargo.toml",
        "crates/licoup-relay/src/**",
        "crates/licoup-client-state/Cargo.toml",
        "crates/licoup-client-state/src/**",
        "crates/licoup-protocol-bindings/Cargo.toml",
        "crates/licoup-protocol-bindings/src/**",
        "crates/licoup-application/Cargo.toml",
        "crates/licoup-application/src/**",
        "crates/licoup-secure-mesh/Cargo.toml",
        "crates/licoup-secure-mesh/src/**",
        "packages/contracts/client/semantic-conversation.schema.json",
        "CONTRIBUTING.md",
        "docs/architecture/README.md",
        "docs/functionality/USER-GUIDE.md",
        "tools/scripts/**",
      ],
      command: node("apps/desktop/scripts/verify-client-architecture.mjs", [], 30_000),
    }),
  defineModule({
      id: "regression.local-service-source-bundle",
      kind: "regression-infrastructure",
      summary: "Target-neutral bounded local HTTP, SSE, state, process, and serve lifecycle source proof",
      inputs: [
        "crates/licoup-agent-drivers/src/local_service.rs",
        "crates/licoup-agent-drivers/src/local_service/bounds.rs",
        "crates/licoup-agent-drivers/src/local_service/concurrency.rs",
        "crates/licoup-agent-drivers/src/local_service/endpoint.rs",
        "crates/licoup-agent-drivers/src/local_service/executable.rs",
        "crates/licoup-agent-drivers/src/local_service/http.rs",
        "crates/licoup-agent-drivers/src/local_service/params.rs",
        "crates/licoup-agent-drivers/src/local_service/port.rs",
        "crates/licoup-agent-drivers/src/local_service/process.rs",
        "crates/licoup-agent-drivers/src/local_service/serve.rs",
        "crates/licoup-agent-drivers/src/local_service/sse.rs",
        "crates/licoup-agent-drivers/src/local_service/state.rs",
        "crates/licoup-agent-drivers/src/local_service/turn_control.rs",
        "tests/contract/client/local-service-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/local-service-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-state-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin client-state facade, independent local owners, bounded IO, and privacy source proof",
      inputs: [
        "crates/licoup-client-state/src/lib.rs",
        "crates/licoup-client-state/src/accessors.rs",
        "crates/licoup-client-state/src/activity.rs",
        "crates/licoup-client-state/src/collections.rs",
        "crates/licoup-client-state/src/migration.rs",
        "crates/licoup-client-state/src/paths.rs",
        "crates/licoup-client-state/src/policy.rs",
        "crates/licoup-client-state/src/redaction.rs",
        "crates/licoup-client-state/src/resource_bounds/mod.rs",
        "crates/licoup-client-state/src/resource_bounds/policy.rs",
        "crates/licoup-client-state/src/resource_bounds/history.rs",
        "crates/licoup-client-state/src/resource_bounds/search.rs",
        "crates/licoup-client-state/src/resource_policy.rs",
        "crates/licoup-client-state/src/serialization.rs",
        "crates/licoup-client-state/src/snapshots.rs",
        "crates/licoup-native/src/platform/client_state.rs",
        "crates/licoup-native/src/platform/client_state/operations.rs",
        "tests/contract/client/client-state-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-state-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.native-stdio-rpc-source-bundle",
      kind: "regression-infrastructure",
      summary: "Ordinary-library ownership, dependency direction, bounds, and privacy evidence",
      inputs: [
        "apps/desktop/lib/src/platform/native_client/native_conversation_command_policy.dart",
        "apps/desktop/lib/src/platform/native_client/native_conversation_port.dart",
        "apps/desktop/lib/src/platform/native_client/agent_service_stdio_rpc.dart",
        "apps/desktop/lib/src/platform/native_client/agent_service_stdio_rpc/**",
        "apps/desktop/test/native_client_component_boundary_test.dart",
        "apps/desktop/test/native_conversation_port_test.dart",
        "apps/desktop/test/native_stdio_rpc_client_test.dart",
        "apps/desktop/test/native_stdio_rpc_line_framer_test.dart",
        "apps/desktop/test/native_stdio_rpc_protocol_test.dart",
        "apps/desktop/test/native_persistent_runtime_test.dart",
        "apps/desktop/test/agent_conversation_reattachment_test.dart",
        "tests/contract/client/native-stdio-rpc-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/native-stdio-rpc-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.client-bridge-generation",
      kind: "regression-infrastructure",
      summary: "Client bridge generator check with real rustfmt and dart format",
      inputs: [
        "tests/contract/client/client-bridge-generation.test.mjs",
        "tools/scripts/generate-client-bridge-contracts.mjs",
        "schemas/client_bridge/**",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/client-bridge-generation.test.mjs"],
        5 * 60_000,
      ),
    }),
  defineModule({
      id: "architecture.development-graph",
      kind: "architecture",
      summary: "Development graph model, impact and selection bridge, work-item export, and offline developer browsing",
      inputs: [
        "tools/architecture-graph/**",
        "tools/development/modules.json",
      ],
      command: command(
        "node",
        ["--test",
        "tools/architecture-graph/test/graph-model.test.mjs",
        "tools/architecture-graph/test/impact-and-selection.test.mjs",
        "tools/architecture-graph/test/publish-and-render.test.mjs",
        "tools/architecture-graph/test/relations-and-deployment.test.mjs",
        "tools/architecture-graph/test/source-identity.test.mjs",
        "tools/architecture-graph/test/work-items.test.mjs",
      ],
        5 * 60_000,
      ),
    }),
]);
