import { command, node, defineModule } from "../../helpers.mjs";

export const PACKAGING_MODULES = Object.freeze([
  defineModule({
    id: "distribution.closure-tools",
    kind: "architecture",
    summary: "Deployment closure, real resolver parity, install-lock byte attribution, and package impact",
    inputs: [
      "tools/distribution/**",
      "tools/architecture-graph/distribution/**",
      "tools/architecture-graph/lib/**",
      "tests/contract/v71_distribution/**",
      "crates/licoup-extension-contracts/src/deployment.rs",
    ],
    command: command("node", ["--test",
        "tests/contract/v71_distribution/catalogue-differential.test.mjs",
        "tests/contract/v71_distribution/cli.test.mjs",
        "tests/contract/v71_distribution/fourth-graph.test.mjs",
        "tests/contract/v71_distribution/install-lock.test.mjs",
        "tests/contract/v71_distribution/profile-closure.test.mjs",
        "tests/contract/v71_distribution/provider-ownership.test.mjs",
        "tests/contract/v71_distribution/removal-preview.test.mjs",
      ], 20 * 60_000),
  }),
  defineModule({
      id: "regression.test-artifact-lifecycle",
      kind: "regression-infrastructure",
      summary: "Leased build outputs, fail-closed reclaim markers, and download-cache isolation",
      inputs: [
        "package.json",
        "tools/scripts/client-build.mjs",
        "tests/contract/client/client-build.test.mjs",
        "tools/scripts/cargo-client.mjs",
        "tools/scripts/client-test-artifacts.mjs",
        "tools/scripts/client-android-native-tests.mjs",
        "tools/scripts/client-secure-mesh-trust-ux.mjs",
        "tools/scripts/lib/cargo-test-filter-runner.mjs",
        "tools/scripts/lib/test-artifact-lifecycle.mjs",
        "tools/scripts/lib/test-artifact-lifecycle/**",
        "tools/scripts/lib/test-artifact-lifecycle.test.mjs",
        "tools/regression/client-module-execution.mjs",
        "tools/regression/client-module-regression-tests/runner-safety.mjs",
        "tests/smoke/native-client-smoke.mjs",
      ],
      command: command(
        "node",
        ["--test", "tools/scripts/lib/test-artifact-lifecycle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.package-client-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin package-client facade and nineteen bounded packaging authorities",
      inputs: [
        "apps/desktop/macos/CustodyHelper/Info.plist",
        "apps/desktop/macos/CustodyHelper/ProductionRelease.entitlements",
        "apps/desktop/scripts/package-client.mjs",
        "apps/desktop/scripts/package-client/build/flutter.mjs",
        "apps/desktop/scripts/package-client/build/native.mjs",
        "apps/desktop/scripts/package-client/build/swift.mjs",
        "apps/desktop/scripts/package-client/bundle-resolver/linux.mjs",
        "apps/desktop/scripts/package-client/bundle-resolver/macos.mjs",
        "apps/desktop/scripts/package-client/bundle-resolver/windows.mjs",
        "apps/desktop/scripts/package-client/cli-policy.mjs",
        "apps/desktop/scripts/package-client/config-codec.mjs",
        "apps/desktop/scripts/package-client/macos/install.mjs",
        "apps/desktop/scripts/package-client/macos/metadata.mjs",
        "apps/desktop/scripts/package-client/macos/signing.mjs",
        "apps/desktop/scripts/package-client/module-selection.mjs",
        "apps/desktop/scripts/package-client/orchestrator.mjs",
        "apps/desktop/scripts/package-client/portable-manifest.mjs",
        "apps/desktop/scripts/package-client/process-runner.mjs",
        "apps/desktop/scripts/package-client/pub-cache.mjs",
        "apps/desktop/scripts/package-client/resource-assembly.mjs",
        "apps/desktop/scripts/package-client/source-staging.mjs",
        "apps/desktop/scripts/package-client/windows-manifest.mjs",
        "tests/contract/client/package-client/package-client-source-bundle.test.mjs",
        "tests/contract/client/package-client/macos-custody-helper.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/package-client/package-client-source-bundle.test.mjs",
          "tests/contract/client/package-client/macos-custody-helper.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.mobile-simulator-closure-source-bundle",
      kind: "regression-infrastructure",
      summary: "Mobile simulator closure leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/mobile-simulator-closure-source-bundle.test.mjs",
        "tools/scripts/client-mobile-simulator-closure.mjs",
        "tools/scripts/client-mobile-simulator-closure/android/artifacts.mjs",
        "tools/scripts/client-mobile-simulator-closure/android/device.mjs",
        "tools/scripts/client-mobile-simulator-closure/android/verify.mjs",
        "tools/scripts/client-mobile-simulator-closure/cli.mjs",
        "tools/scripts/client-mobile-simulator-closure/constants.mjs",
        "tools/scripts/client-mobile-simulator-closure/errors.mjs",
        "tools/scripts/client-mobile-simulator-closure/flutter.mjs",
        "tools/scripts/client-mobile-simulator-closure/ios/artifacts.mjs",
        "tools/scripts/client-mobile-simulator-closure/ios/device.mjs",
        "tools/scripts/client-mobile-simulator-closure/ios/verify.mjs",
        "tools/scripts/client-mobile-simulator-closure/process.mjs",
        "tools/scripts/client-mobile-simulator-closure/receipt.mjs",
        "tools/scripts/client-mobile-simulator-closure/run.mjs",
        "tools/scripts/client-mobile-simulator-closure/self-test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/mobile-simulator-closure-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.android-physical-install-launch-source-bundle",
      kind: "regression-infrastructure",
      summary: "Android physical install/launch leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/android-physical-install-launch-source-bundle.test.mjs",
        "tools/scripts/client-android-physical-install-launch.mjs",
        "tools/scripts/client-android-physical-install-launch/apk/inspect.mjs",
        "tools/scripts/client-android-physical-install-launch/cli.mjs",
        "tools/scripts/client-android-physical-install-launch/constants.mjs",
        "tools/scripts/client-android-physical-install-launch/device/adb.mjs",
        "tools/scripts/client-android-physical-install-launch/device/classify.mjs",
        "tools/scripts/client-android-physical-install-launch/device/select.mjs",
        "tools/scripts/client-android-physical-install-launch/operations/install.mjs",
        "tools/scripts/client-android-physical-install-launch/operations/launch.mjs",
        "tools/scripts/client-android-physical-install-launch/privacy/leak-scan.mjs",
        "tools/scripts/client-android-physical-install-launch/privacy/sanitize.mjs",
        "tools/scripts/client-android-physical-install-launch/report/blocked.mjs",
        "tools/scripts/client-android-physical-install-launch/report/build.mjs",
        "tools/scripts/client-android-physical-install-launch/run.mjs",
        "tools/scripts/client-android-physical-install-launch/runtime/status.mjs",
        "tools/scripts/client-android-physical-install-launch/self-test.mjs",
        "tools/scripts/client-android-physical-install-launch/util/hash.mjs",
        "tools/scripts/client-android-physical-install-launch/util/json.mjs",
        "tools/scripts/client-android-physical-install-launch/util/paths.mjs",
        "tools/scripts/client-android-physical-install-launch/version.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/android-physical-install-launch-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.cli-vm-source-bundle",
      kind: "regression-infrastructure",
      summary: "Client CLI VM leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/cli-vm-source-bundle.test.mjs",
        "tools/scripts/client-cli-vm.mjs",
        "tools/scripts/client-cli-vm/cli.mjs",
        "tools/scripts/client-cli-vm/constants.mjs",
        "tools/scripts/client-cli-vm/distro/select.mjs",
        "tools/scripts/client-cli-vm/image/disk.mjs",
        "tools/scripts/client-cli-vm/image/download.mjs",
        "tools/scripts/client-cli-vm/image/seed.mjs",
        "tools/scripts/client-cli-vm/linux-product/artifacts.mjs",
        "tools/scripts/client-cli-vm/linux-product/bootstrap.mjs",
        "tools/scripts/client-cli-vm/linux-product/command.mjs",
        "tools/scripts/client-cli-vm/linux-product/incomplete.mjs",
        "tools/scripts/client-cli-vm/linux-product/run.mjs",
        "tools/scripts/client-cli-vm/linux-product/shell-helpers.mjs",
        "tools/scripts/client-cli-vm/linux-product/source-manifest.mjs",
        "tools/scripts/client-cli-vm/linux-product/toolchain.mjs",
        "tools/scripts/client-cli-vm/linux-product/validate.mjs",
        "tools/scripts/client-cli-vm/list.mjs",
        "tools/scripts/client-cli-vm/paths.mjs",
        "tools/scripts/client-cli-vm/process.mjs",
        "tools/scripts/client-cli-vm/run.mjs",
        "tools/scripts/client-cli-vm/self-test/runner.mjs",
        "tools/scripts/client-cli-vm/ssh/key.mjs",
        "tools/scripts/client-cli-vm/ssh/session.mjs",
        "tools/scripts/client-cli-vm/sync/artifacts.mjs",
        "tools/scripts/client-cli-vm/sync/repo.mjs",
        "tools/scripts/client-cli-vm/verify/bootstrap.mjs",
        "tools/scripts/client-cli-vm/verify/command.mjs",
        "tools/scripts/client-cli-vm/verify/distro.mjs",
        "tools/scripts/client-cli-vm/vm/lifecycle.mjs",
        "tools/scripts/client-cli-vm/vm/prepare.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/cli-vm-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.release-acceptance-source-bundle",
      kind: "regression-infrastructure",
      summary: "Client release-acceptance leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/release-acceptance-source-bundle.test.mjs",
        "tools/scripts/client-release-acceptance.mjs",
        "tools/scripts/client-release-acceptance/artifacts/android.mjs",
        "tools/scripts/client-release-acceptance/artifacts/digests.mjs",
        "tools/scripts/client-release-acceptance/artifacts/helpers.mjs",
        "tools/scripts/client-release-acceptance/artifacts/macos.mjs",
        "tools/scripts/client-release-acceptance/artifacts/materialize.mjs",
        "tools/scripts/client-release-acceptance/artifacts/receipt.mjs",
        "tools/scripts/client-release-acceptance/artifacts/selected.mjs",
        "tools/scripts/client-release-acceptance/artifacts/stability.mjs",
        "tools/scripts/client-release-acceptance/cli.mjs",
        "tools/scripts/client-release-acceptance/constants.mjs",
        "tools/scripts/client-release-acceptance/evidence.mjs",
        "tools/scripts/client-release-acceptance/load-reports.mjs",
        "tools/scripts/client-release-acceptance/preflight.mjs",
        "tools/scripts/client-release-acceptance/privacy.mjs",
        "tools/scripts/client-release-acceptance/reduce.mjs",
        "tools/scripts/client-release-acceptance/refs.mjs",
        "tools/scripts/client-release-acceptance/report-deps.mjs",
        "tools/scripts/client-release-acceptance/run.mjs",
        "tools/scripts/client-release-acceptance/sanitize-binding.mjs",
        "tools/scripts/client-release-acceptance/self-test/fixtures.mjs",
        "tools/scripts/client-release-acceptance/self-test/runner.mjs",
        "tools/scripts/client-release-acceptance/support-matrix.mjs",
        "tools/scripts/client-release-acceptance/targets.mjs",
        "tools/scripts/client-release-acceptance/util.mjs",
        "tools/scripts/client-release-acceptance/validate-config.mjs",
        "tools/scripts/client-release-acceptance/validate-report.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/release-acceptance-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.artifact-verification-receipts-source-bundle",
      kind: "regression-infrastructure",
      summary: "Artifact verification receipts leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/artifact-verification-receipts-source-bundle.test.mjs",
        "tools/scripts/client-artifact-verification-receipts.mjs",
        "tools/scripts/client-artifact-verification-receipts/cli.mjs",
        "tools/scripts/client-artifact-verification-receipts/constants.mjs",
        "tools/scripts/client-artifact-verification-receipts/errors.mjs",
        "tools/scripts/client-artifact-verification-receipts/invoke/lineage.mjs",
        "tools/scripts/client-artifact-verification-receipts/invoke/target-input.mjs",
        "tools/scripts/client-artifact-verification-receipts/privacy.mjs",
        "tools/scripts/client-artifact-verification-receipts/receipt/build.mjs",
        "tools/scripts/client-artifact-verification-receipts/receipt/empty.mjs",
        "tools/scripts/client-artifact-verification-receipts/run.mjs",
        "tools/scripts/client-artifact-verification-receipts/self-test/fixtures.mjs",
        "tools/scripts/client-artifact-verification-receipts/self-test/runner.mjs",
        "tools/scripts/client-artifact-verification-receipts/util.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-config.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/android.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/common.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/linux.mjs",
        "tools/scripts/client-artifact-verification-receipts/validate-evidence/macos.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/artifact-verification-receipts-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.linux-node-matrix-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh linux-node-matrix leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/linux-node-matrix-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/assert.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/cli.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/constants.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/identity.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/matrix.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/operations.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/relay/opaque-relay.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/relay/protocol.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/report.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/run.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/self-test.mjs",
        "tools/scripts/client-secure-mesh-linux-node-matrix/util.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/linux-node-matrix-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.linux-vm-package-receipt-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh linux-vm-package-receipt leaf ownership and thin facade contract",
      inputs: [
        "tests/contract/client/linux-vm-package-receipt-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/cli.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/gui.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/receipt.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/report.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/run.mjs",
        "tools/scripts/client-secure-mesh-linux-vm-package-receipt/util.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/linux-vm-package-receipt-source-bundle.test.mjs"],
        60_000,
      ),
    }),
]);
