import { command, node, defineModule } from "../../helpers.mjs";

export const PRESENTATION_MODULES = Object.freeze([
  defineModule({
      id: "regression.core-state-machine-test-layout",
      kind: "regression-infrastructure",
      summary: "Physical Secure Mesh state-machine test ownership, names, and stable vectors",
      inputs: [
        "crates/licoup-native/src/core/secure_mesh_acp.rs",
        "crates/licoup-native/src/core/secure_mesh_acp/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_capability_proof.rs",
        "crates/licoup-native/src/core/secure_mesh_capability_proof/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_session_negotiation.rs",
        "crates/licoup-native/src/core/secure_mesh_session_negotiation/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_sparse_pq_ratchet.rs",
        "crates/licoup-native/src/core/secure_mesh_sparse_pq_ratchet/tests/mod.rs",
        "crates/licoup-native/src/core/secure_mesh_mls_product/security_ledger.rs",
        "crates/licoup-native/src/core/secure_mesh_mls_product/security_ledger/test_support.rs",
        "crates/licoup-native/src/core/secure_mesh_mls_product/tests/security_ledger.rs",
        "tests/contract/client/core-state-machine-test-layout.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/core-state-machine-test-layout.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.layout-boundaries",
      kind: "regression-infrastructure",
      summary: "Target-state layout ownership, structural shared-renderer policy, profile path, and import-boundary verifier",
      inputs: [
        "apps/desktop/scripts/verify-layout-boundaries.mjs",
        "apps/desktop/scripts/verify-layout-boundaries-self-test.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/run.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/helpers.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/fixtures.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/product.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/imports.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/ports.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/self-test/cases/identity.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/bundle-product.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/cli.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/config.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dart-source.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dependency-policy.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/errors.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/import-graph.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/ownership.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/paths.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/state-authority.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/surface-parse.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/verify.mjs",
      ],
      command: node(
        "apps/desktop/scripts/verify-layout-boundaries.mjs",
        ["--self-test"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.layout-boundaries-source-bundle",
      kind: "regression-infrastructure",
      summary: "Layout boundary leaf ownership, structural dependency policy, thin facade, and synthetic self-test contract",
      inputs: [
        "tests/contract/client/layout-boundaries-source-bundle.test.mjs",
        "apps/desktop/scripts/verify-layout-boundaries.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/bundle-product.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/cli.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/config.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dart-source.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/dependency-policy.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/errors.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/import-graph.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/ownership.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/paths.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/state-authority.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/surface-parse.mjs",
        "apps/desktop/scripts/verify-layout-boundaries/verify.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/layout-boundaries-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.layout-visual-manifests",
      kind: "regression-infrastructure",
      summary: "Layout visual-manifest check surface and dedicated self-test",
      inputs: [
        "apps/desktop/scripts/verify-layout-visual-manifests.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests-self-test.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/catalog.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/check.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/cli.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/config.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/errors.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/generate.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/manifest-codec.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/owner-roots.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/paths.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/write.mjs",
      ],
      command: node(
        "apps/desktop/scripts/verify-layout-visual-manifests-self-test.mjs",
        [],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.layout-visual-manifests-source-bundle",
      kind: "regression-infrastructure",
      summary: "Layout visual-manifest leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/layout-visual-manifests-source-bundle.test.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/catalog.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/check.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/cli.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/config.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/errors.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/generate.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/manifest-codec.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/owner-roots.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/paths.mjs",
        "apps/desktop/scripts/verify-layout-visual-manifests/write.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/layout-visual-manifests-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.mobile-relay-panel-source-bundle",
      kind: "regression-infrastructure",
      summary: "Mobile Relay panel exact exports, one-way presenter ownership, and dedicated widget regressions",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/composition.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/pairing.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/qr.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/scan.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/trust.dart",
        "tests/contract/client/mobile-relay-panel-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/mobile-relay-panel-source-bundle.test.mjs"],
        60_000,
      ),
    }),
]);
