import { command, node, defineModule } from "../../helpers.mjs";

export const SECURITY_MODULES = Object.freeze([
  defineModule({
      id: "regression.secure-mesh-source-bundles",
      kind: "regression-infrastructure",
      summary: "Aggregate source-evidence contracts for physically split Secure Mesh modules",
      inputs: [
        "tests/contract/client/secure-mesh-source-bundles.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-source-bundles.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.key-transparency-source-bundle",
      kind: "regression-infrastructure",
      summary: "Key-transparency workflow ownership, fail-closed authority reset, and one-way persistence boundary",
      inputs: [
        "crates/licoup-relay/src/domain/mobile_relay/key_transparency.rs",
        "crates/licoup-relay/src/domain/mobile_relay/key_transparency/**",
        "tests/contract/client/key-transparency-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/key-transparency-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.local-material-source-bundle",
      kind: "regression-infrastructure",
      summary: "Local endpoint material split ownership, fail-closed reset, and generation-mutation boundary",
      inputs: [
        "crates/licoup-relay/src/domain/mobile_relay/endpoint_trust/local_material.rs",
        "crates/licoup-relay/src/domain/mobile_relay/endpoint_trust/local_material/**",
        "tests/contract/client/local-material-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/local-material-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.directory-transparency-source-bundle",
      kind: "regression-infrastructure",
      summary: "Directory claim, freshness, verifier, authority, and authorization split ownership",
      inputs: [
        "crates/licoup-relay/src/domain/mobile_relay/endpoint_trust/directory_transparency.rs",
        "crates/licoup-relay/src/domain/mobile_relay/endpoint_trust/directory_transparency/**",
        "tests/contract/client/directory-transparency-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/directory-transparency-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.pairwise-session-source-bundle",
      kind: "regression-infrastructure",
      summary: "Pairwise status, replay redaction, ciphertext operations, atomic commit, handshake, and durable-store split",
      inputs: [
        "crates/licoup-relay/src/domain/mobile_relay/pairwise_session.rs",
        "crates/licoup-relay/src/domain/mobile_relay/pairwise_session/**",
        "tests/contract/client/pairwise-session-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/pairwise-session-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.relay-operations-source-bundle",
      kind: "regression-infrastructure",
      summary: "Ciphertext-only relay commands, canonical context, mailbox, envelope, registration, delivery, status, and allow-list split",
      inputs: [
        "crates/licoup-relay/src/domain/mobile_relay/relay_operations.rs",
        "crates/licoup-relay/src/domain/mobile_relay/relay_operations/**",
        "tests/contract/client/relay-operations-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/relay-operations-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-release-proof-bundle-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh release-proof-bundle leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/secure-mesh-release-proof-bundle-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/cli.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/config.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/constants.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/contract-readiness.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/freshness.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/integrity.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/io.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/lists.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/privacy.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report-summary-core.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report-summary-physical.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report-summary.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/report.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/run.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/client-licoarc-crypto.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/contract.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/freshness.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/physical-evidence.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/self-test/redaction.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/android-install.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/client-licoarc-crypto.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/physical-evidence.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/physical-matrix.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/redaction.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/update.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/summarize/windows.mjs",
        "tools/scripts/client-secure-mesh-release-proof-bundle/verifiers.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-release-proof-bundle-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.e2ee-evidence-bundle-source-bundle",
      kind: "regression-infrastructure",
      summary: "Secure Mesh e2ee evidence bundle leaf ownership, thin facade, and leak-scan self-test",
      inputs: [
        "tests/contract/client/e2ee-evidence-bundle-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-e2ee-evidence-bundle.mjs",
        "tools/scripts/client-secure-mesh-e2ee-evidence-bundle/run.mjs",
        "tools/scripts/client-secure-mesh-e2ee-evidence-bundle/util.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/e2ee-evidence-bundle-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.macos-keychain-user-presence-source-bundle",
      kind: "regression-infrastructure",
      summary: "macOS keychain user-presence leaf ownership, thin facade, and self-test dry-run contract",
      inputs: [
        "tests/contract/client/macos-keychain-user-presence-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/capability/facts.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/capability/summarize.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/cli.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/constants.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/codesign.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/process.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/run-swift.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/helper/swift-source.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/parse.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/privacy.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/proof.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/report.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/run.mjs",
        "tools/scripts/client-secure-mesh-macos-keychain-user-presence-proof/self-test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/macos-keychain-user-presence-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.pairwise-content-audit-source-bundle",
      kind: "regression-infrastructure",
      summary: "Pairwise content audit leaf ownership, thin facade, and contract-bound leaf tokens",
      inputs: [
        "tests/contract/client/pairwise-content-audit-source-bundle.test.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/constants.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/corpus.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/hash.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/native-test.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/privacy.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/run.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/signoff-load.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/signoff.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/source-check.mjs",
        "tools/scripts/client-secure-mesh-pairwise-content-audit/vectors.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/pairwise-content-audit-source-bundle.test.mjs"],
        120_000,
      ),
    }),
  defineModule({
      id: "regression.local-data-egress-boundary",
      kind: "regression-infrastructure",
      summary: "Local-data egress allowlist and GET-only package-fetch boundary",
      inputs: [
        "tests/contract/client/local-data-egress-boundary.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/local-data-egress-boundary.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-capability-source-bundle",
      kind: "regression-infrastructure",
      summary: "Restricted capability facade, bounded DAG/cache, one-way leaves, and privacy source proof",
      inputs: [
        "crates/licoup-secure-mesh/resources/secure-mesh-capability-catalog.json",
        "crates/licoup-secure-mesh/src/core/secure_mesh_capability.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_capability/catalog.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_capability/custody.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_capability/evaluation.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_capability/facts.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_capability/report.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_capability/taxonomy.rs",
        "tests/contract/client/secure-mesh-capability-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-capability-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-prekey-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin prekey facade, pairwise/KeyPackage split, local watermarks, and shared validation proof",
      inputs: [
        "crates/licoup-secure-mesh/src/core/secure_mesh_prekey.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_prekey/inventory.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_prekey/key_package.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_prekey/pairwise.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_prekey/validation.rs",
        "tests/contract/client/secure-mesh-prekey-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-prekey-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.secure-mesh-pairwise-boundary-source-bundle",
      kind: "regression-infrastructure",
      summary: "Atomic handshake and ratchet owners with bounded negotiation, payload, and relay leaves",
      inputs: [
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/session_negotiation.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/session_negotiation/capability_binding.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/session_negotiation/handshake_machine.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/session_negotiation/input_validation.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/session_negotiation/key_schedule.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/session_negotiation/transcript_codec.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/key_ratchet.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/key_ratchet/payload_adapter.rs",
        "crates/licoup-secure-mesh/src/core/secure_mesh_pairwise/key_ratchet/relay_codec.rs",
        "tests/contract/client/secure-mesh-pairwise-boundary-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/secure-mesh-pairwise-boundary-source-bundle.test.mjs"],
        60_000,
      ),
    }),
  defineModule({
      id: "regression.file-security-source-bundle",
      kind: "regression-infrastructure",
      summary: "Thin file-security facade, fail-closed leaf ownership, and stable consumer boundary source proof",
      inputs: [
        "crates/licoup-foundation/src/platform/file_security.rs",
        "crates/licoup-foundation/src/platform/file_security/append_lock.rs",
        "crates/licoup-foundation/src/platform/file_security/atomic_replace.rs",
        "crates/licoup-foundation/src/platform/file_security/hardening.rs",
        "crates/licoup-foundation/src/platform/file_security/marker.rs",
        "crates/licoup-foundation/src/platform/file_security/policy.rs",
        "crates/licoup-foundation/src/platform/file_security/sync.rs",
        "crates/licoup-foundation/src/platform/file_security/unix_hardening.rs",
        "crates/licoup-foundation/src/platform/file_security/validation.rs",
        "crates/licoup-foundation/src/platform/file_security/windows_acl.rs",
        "tests/contract/client/file-security-source-bundle.test.mjs",
      ],
      command: command(
        "node",
        ["--test", "tests/contract/client/file-security-source-bundle.test.mjs"],
        60_000,
      ),
    }),
]);
