[workspace]
members = [
    "crates/lico-catalog-convergence",
    "crates/licoup-protocol-bindings",
    "crates/licoup-client-state",
    "crates/licoup-endpoint-core",
    "crates/licoup-platform-bridges",
    "crates/licoup-agent-adapters",
    "crates/licoup-native",
    "crates/trybuild",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/LicoLand/LicoUp.git"
license = "AGPL-3.0-or-later"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
