[workspace]
members = ["crates/lico-catalog-convergence", "crates/licoup-native", "crates/trybuild"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/LicoLand/LicoUp.git"
license = "AGPL-3.0-or-later"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
