import { FLUTTER_COMPOSITION_INPUTS, flutterTests, flutterAnalyze, defineModule } from "../../helpers.mjs";

export const APPLICATION_SHELL_MODULES = Object.freeze([
  defineModule({
    id: "flutter.feature.application-state-machines",
    kind: "flutter-feature",
    summary: "Configuration-generated application lifecycle and observation transitions",
    inputs: [
      "apps/desktop/lib/src/application/generated/state_machines.g.dart",
      "apps/desktop/lib/src/contracts/generated/client_update_state_machine.g.dart",
      "apps/desktop/lib/src/presentation/generated/settings_state_machines.g.dart",
      "apps/desktop/resources/state-machines.json",
      "apps/desktop/resources/client-update-state-machine.json",
      "apps/desktop/resources/settings-state-machines.json",
      "apps/desktop/test/application_state_machines_test.dart",
    ],
    command: flutterTests(["test/application_state_machines_test.dart"]),
  }),
  defineModule({
    id: "flutter.feature.conversation-prepared-markdown",
    kind: "flutter-feature",
    summary: "Prepared conversation message bodies: projected source, off-thread preparation, revocation, and the message view that renders them",
    inputs: [
      "apps/desktop/lib/src/presentation/conversation/**",
      "apps/desktop/lib/src/frontend/shared/ui/message_markdown.dart",
      "apps/desktop/test/conversation_ui/**",
      "packages/presentation_contract/**",
      "packages/presentation_runtime/**",
    ],
    command: flutterTests(["test/conversation_ui"]),
  }),
  defineModule({
      id: "flutter.feature.ui-state-machine",
    kind: "flutter-feature",
    summary: "UI interaction model and widget transition scenarios",
    inputs: [
      "apps/desktop/test/ui_state_machine/**",
      "apps/desktop/integration_test/ui_state_machine_test.dart",
      "apps/desktop/test_driver/ui_state_machine.dart",
      "apps/desktop/test/ui_state_machine/model.json",
      "tools/scripts/client-ui-state-machine.mjs",
    ],
    command: flutterTests(["test/ui_state_machine"]),
  }),
  defineModule({
      id: "flutter.composition.dependencies",
      kind: "flutter-composition",
      summary: "Flutter dependency graph, analyzer options, and locked package composition",
      inputs: FLUTTER_COMPOSITION_INPUTS,
      command: flutterAnalyze(),
    }),
  defineModule({
      id: "flutter.feature.catalog-convergence",
      kind: "flutter-feature",
      summary: "Desktop catalog lifecycle, private structured native bridge, bounded state, and visible revision projection",
      inputs: [
        "apps/desktop/lib/src/contracts/catalog_convergence/**",
        "apps/desktop/lib/src/application/features/catalog_convergence/**",
        "apps/desktop/lib/src/application/controller/assembly/client_catalog_convergence_component_assembly.dart",
        "apps/desktop/lib/src/platform/native_client/native_catalog_actions.dart",
        "apps/desktop/test/catalog_convergence_controller_test.dart",
        "apps/desktop/test/catalog_convergence_architecture_test.dart",
      ],
      command: flutterTests([
        "test/catalog_convergence_controller_test.dart",
        "test/catalog_convergence_architecture_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.adaptive-flywheel",
      kind: "flutter-feature",
      summary: "Restored capsule role editor, strategy import, background runtime detection, and workflow diagram",
      inputs: [
        "apps/desktop/lib/src/contracts/generated/strategy.g.dart",
        "apps/desktop/lib/src/contracts/adaptive_flywheel_models.dart",
        "apps/desktop/lib/src/application/features/agents/contracts/adaptive_flywheel_gateway.dart",
        "apps/desktop/lib/src/backend/features/agents/services/adaptive_flywheel_service.dart",
        "apps/desktop/lib/src/application/features/agents/adaptive_flywheel/**",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_dialog.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_multi_capsule_section.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_model_list.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_renderer_models.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_workflow_diagram.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/adaptive_flywheel_workflow_layout.dart",
        "apps/desktop/test/adaptive_flywheel_controller_test.dart",
        "apps/desktop/test/adaptive_flywheel_multi_capsule_section_test.dart",
        "apps/desktop/test/adaptive_flywheel_target_catalog_test.dart",
        "apps/desktop/test/adaptive_flywheel_workflow_diagram_test.dart",
        "apps/desktop/test/adaptive_flywheel_model_picker_label_test.dart",
        "apps/desktop/test/adaptive_flywheel_model_list_test.dart",
      ],
      command: flutterTests([
        "test/adaptive_flywheel_controller_test.dart",
        "test/adaptive_flywheel_multi_capsule_section_test.dart",
        "test/adaptive_flywheel_target_catalog_test.dart",
        "test/adaptive_flywheel_workflow_diagram_test.dart",
        "test/adaptive_flywheel_model_picker_label_test.dart",
        "test/adaptive_flywheel_model_list_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.settings",
      kind: "flutter-feature",
      summary: "Settings shell, appearance, updates, directories, and log export",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/contracts/agent_resource_usage_gateway.dart",
        "apps/desktop/lib/src/application/features/settings/controller/agent_resource_usage_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/client_log_export_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/client_resource_usage_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/client_update_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/directory_path_controller.dart",
        "apps/desktop/lib/src/contracts/client_log_export.dart",
        "apps/desktop/lib/src/contracts/agent_resource_usage_models.dart",
        "apps/desktop/lib/src/contracts/client_update_gateway.dart",
        "apps/desktop/lib/src/contracts/directory_opener.dart",
        "apps/desktop/lib/src/contracts/llm_gateway_diagnostics.dart",
        "apps/desktop/lib/src/contracts/llm_vault_authorization.dart",
        "apps/desktop/lib/src/backend/features/settings/services/client_update_service.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/archived_conversations_settings_section.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/client_resource_usage_card.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/client_update_settings_card.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/diagnostics_settings_section.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/layout_profile_selector.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/diagnostics_resource_section.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/resource_usage_shared.dart",
        "apps/desktop/lib/src/frontend/shared/settings_section_catalog.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/settings_control_metrics.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/settings_panel.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/settings_dropdown_list.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/settings_panel_widgets.dart",
        "apps/desktop/lib/src/frontend/features/settings/ui/startup_autostart_card.dart",
        "apps/desktop/lib/src/frontend/features/models/ui/llm_gateway_card.dart",
        "apps/desktop/lib/src/frontend/features/models/ui/llm_gateway_credentials_card.dart",
        "apps/desktop/lib/src/frontend/features/models/ui/models_panel.dart",
        "apps/desktop/lib/src/frontend/features/models/ui/telegram_channel_card.dart",
        "apps/desktop/lib/src/platform/client_resource_usage_probe.dart",
        "apps/desktop/lib/src/platform/system_memory_capacity.dart",
        "apps/desktop/lib/src/platform/appearance/**",
        "apps/desktop/lib/src/platform/presentation/**",
        "apps/desktop/lib/src/platform/runtime_platform_bridge.dart",
        "apps/desktop/lib/src/frontend/appearance/appearance_preset_config.dart",
        "apps/desktop/lib/src/frontend/appearance/appearance_visuals.dart",
        "apps/desktop/lib/src/contracts/appearance/**",
        "apps/desktop/lib/src/contracts/client_update_models.dart",
        "apps/desktop/lib/src/presentation/environment/locale_preferences.dart",
        "apps/desktop/assets/appearance-presets/**",
        "apps/desktop/assets/fonts/**",
        "apps/desktop/assets/provider-icons/**",
        "apps/desktop/test/appearance_preset_catalog_service_test.dart",
        "apps/desktop/test/agent_resource_usage_controller_test.dart",
        "apps/desktop/test/agent_resource_usage_models_test.dart",
        "apps/desktop/test/agent_usage_timeline/agent_usage_cursor_model_share_test.dart",
        "apps/desktop/test/archived_conversations_settings_section_test.dart",
        "apps/desktop/test/client_log_export_controller_test.dart",
        "apps/desktop/test/client_log_export_service_test.dart",
        "apps/desktop/test/client_resource_usage_card_test.dart",
        "apps/desktop/test/client_resource_usage_controller_test.dart",
        "apps/desktop/test/client_resource_usage_probe_test.dart",
        "apps/desktop/test/client_update_controller_test.dart",
        "apps/desktop/test/client_update_service_test.dart",
        "apps/desktop/test/client_update_settings_card_test.dart",
        "apps/desktop/test/directory_path_controller_test.dart",
        "apps/desktop/test/fixtures/settings_presentation_fixture.dart",
        "apps/desktop/test/settings_component_boundary_test.dart",
        "apps/desktop/test/settings_lazy_regions_test.dart",
        "apps/desktop/test/settings_panel_test.dart",
        "apps/desktop/test/settings_presentation_hub_test.dart",
        "apps/desktop/test/llm_gateway_diagnostic_log_test.dart",
        "apps/desktop/test/llm_gateway_lifecycle_controller_test.dart",
        "apps/desktop/test/llm_gateway_models_panel_test.dart",
        "apps/desktop/test/startup_autostart_card_test.dart",
        "apps/desktop/test/system_memory_capacity_test.dart",
        "apps/desktop/test/telegram_channel_card_test.dart",
      ],
      command: flutterTests([
        "test/appearance_preset_catalog_service_test.dart",
        "test/agent_resource_usage_controller_test.dart",
        "test/agent_resource_usage_models_test.dart",
        "test/agent_usage_timeline/agent_usage_cursor_model_share_test.dart",
        "test/archived_conversations_settings_section_test.dart",
        "test/client_log_export_controller_test.dart",
        "test/client_log_export_service_test.dart",
        "test/client_resource_usage_card_test.dart",
        "test/client_resource_usage_controller_test.dart",
        "test/client_resource_usage_probe_test.dart",
        "test/client_update_controller_test.dart",
        "test/client_update_service_test.dart",
        "test/client_update_settings_card_test.dart",
        "test/directory_path_controller_test.dart",
        "test/settings_component_boundary_test.dart",
        "test/settings_lazy_regions_test.dart",
        "test/settings_panel_test.dart",
        "test/settings_presentation_hub_test.dart",
        "test/llm_gateway_diagnostic_log_test.dart",
        "test/llm_gateway_lifecycle_controller_test.dart",
        "test/llm_gateway_models_panel_test.dart",
        "test/startup_autostart_card_test.dart",
        "test/system_memory_capacity_test.dart",
        "test/telegram_channel_card_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.skill-hub",
      kind: "flutter-feature",
      summary: "Skill Hub catalog, compatibility, preferences, and UI",
      inputs: [
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_hub_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_hub_status.dart",
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_operation_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/models/skill_agent_compatibility.dart",
        "apps/desktop/lib/src/application/features/skill_hub/models/skill_category_catalog.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/local_skill_hub_catalog_source.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/skill_hub_skill_catalog.dart",
        "apps/desktop/lib/src/backend/features/skill_hub/**",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_surface.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel_card_support.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel_catalog.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_panel_icon_picker.dart",
        "apps/desktop/lib/src/frontend/features/skill_hub/ui/skill_hub_search.dart",
        "apps/desktop/lib/src/platform/skill_hub/**",
        "apps/desktop/lib/src/contracts/skill_hub.dart",
        "apps/desktop/lib/src/contracts/skill_hub_preferences.dart",
        "apps/desktop/assets/skill-category-icons/**",
        "apps/desktop/test/skill_agent_compatibility_test.dart",
        "apps/desktop/test/skill_category_catalog_test.dart",
        "apps/desktop/test/skill_hub_component_boundary_test.dart",
        "apps/desktop/test/skill_hub_controller_test.dart",
        "apps/desktop/test/skill_hub_invocation_counts_test.dart",
        "apps/desktop/test/skill_hub_panel_test.dart",
        "apps/desktop/test/skill_hub_search_test.dart",
        "apps/desktop/test/skill_hub_skill_catalog_test.dart",
        "apps/desktop/test/skill_hub_presentation_sources_test.dart",
        "apps/desktop/test/fixtures/skill_hub_binding_fixture.dart",
        "apps/desktop/test/fixtures/skill_hub_presentation_fixture.dart",
        "apps/desktop/test/client_interface_entry_hooks_test.dart",
      ],
      command: flutterTests([
        "test/skill_agent_compatibility_test.dart",
        "test/skill_category_catalog_test.dart",
        "test/skill_hub_component_boundary_test.dart",
        "test/skill_hub_controller_test.dart",
        "test/skill_hub_invocation_counts_test.dart",
        "test/skill_hub_panel_test.dart",
        "test/skill_hub_search_test.dart",
        "test/skill_hub_skill_catalog_test.dart",
        "test/skill_hub_presentation_sources_test.dart",
        "test/client_interface_entry_hooks_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.skill-hub.delete",
      kind: "flutter-feature",
      summary: "Explicit multi-agent skill deletion controller and service",
      inputs: [
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_delete_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/skill_delete_service.dart",
        "apps/desktop/lib/src/contracts/skill_delete.dart",
        "apps/desktop/test/skill_delete_controller_test.dart",
        "apps/desktop/test/skill_delete_service_test.dart",
      ],
      command: flutterTests([
        "test/skill_delete_controller_test.dart",
        "test/skill_delete_service_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.skill-hub.usage",
      kind: "flutter-feature",
      summary: "Time-windowed reports over runtime-collected local skill invocation aggregates",
      inputs: [
        "apps/desktop/lib/src/application/features/skill_hub/controller/skill_usage_controller.dart",
        "apps/desktop/lib/src/application/features/skill_hub/services/skill_usage_service.dart",
        "apps/desktop/lib/src/contracts/skill_usage.dart",
        "apps/desktop/test/skill_usage_controller_test.dart",
        "apps/desktop/test/skill_usage_service_test.dart",
      ],
      command: flutterTests([
        "test/skill_usage_controller_test.dart",
        "test/skill_usage_service_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layer.contracts",
      kind: "flutter-layer",
      summary: "Generated and cross-platform Secure Mesh contract projections",
      inputs: [
        "apps/desktop/lib/src/contracts/generated/**",
        "apps/desktop/lib/src/contracts/target_candidate.dart",
        "apps/desktop/test/fixtures/secure_mesh_capability_projection.dart",
        "apps/desktop/test/secure_mesh_kt_models_test.dart",
        "apps/desktop/test/secure_mesh_mls_models_test.dart",
        "apps/desktop/test/target_candidate_conversation_test.dart",
      ],
      command: flutterTests([
        "test/secure_mesh_kt_models_test.dart",
        "test/secure_mesh_mls_models_test.dart",
        "test/target_candidate_conversation_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layer.layout",
      kind: "flutter-layer",
      summary: "Layout registry, profiles, destination ports, and scoped state",
      inputs: [
        "apps/desktop/resources/layout-selection-state-machine.json",
        "apps/desktop/lib/src/application/features/layout/**",
        "apps/desktop/lib/src/composition/built_in_layout_composition.dart",
        "apps/desktop/lib/src/contracts/presentation/**",
        "apps/desktop/lib/src/frontend/layout/layout_agents_strategy.dart",
        "apps/desktop/lib/src/frontend/layout/layout_chrome_features.dart",
        "apps/desktop/lib/src/frontend/layout/layout_chrome_port.dart",
        "apps/desktop/lib/src/frontend/layout/layout_component_kit.dart",
        "apps/desktop/lib/src/frontend/layout/layout_definition.dart",
        "apps/desktop/lib/src/frontend/layout/layout_destination_port_mount.dart",
        "apps/desktop/lib/src/frontend/layout/layout_destination_presentation.dart",
        "apps/desktop/lib/src/frontend/layout/layout_focus_coordinator.dart",
        "apps/desktop/lib/src/frontend/layout/layout_host.dart",
        "apps/desktop/lib/src/frontend/layout/layout_palette.dart",
        "apps/desktop/lib/src/frontend/layout/layout_registry.dart",
        "apps/desktop/lib/src/frontend/layout/layout_scope.dart",
        "apps/desktop/lib/src/frontend/layout/layout_state_port.dart",
        "apps/desktop/lib/src/frontend/layout/layout_state_store.dart",
        "apps/desktop/lib/src/frontend/layout/layout_surface_bundle.dart",
        "apps/desktop/lib/src/frontend/layout/layout_value_builder.dart",
        "apps/desktop/lib/src/frontend/layout/layout_visual_tokens.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/mobile/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/components/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/destinations/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/presentation/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/preview/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/tokens/**",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/dashboard_desktop.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_content_region.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_desktop_shell.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_main_content_card.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_profile_page.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_sidebar_column.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_sidebar_foundation.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/dashboard/desktop/shell/dashboard_sidebar_navigation.dart",
        "apps/desktop/lib/src/frontend/layout/profiles/desktop/**",
        "apps/desktop/lib/src/platform/layout/**",
        "apps/desktop/test/layout/fixtures/**",
        "apps/desktop/test/layout/layout_manager_file_repository_test.dart",
        "apps/desktop/test/layout/layout_manager_production_catalog_test.dart",
        "apps/desktop/test/support/test_layout_palette.dart",
        "apps/desktop/test/layout/production_baseline/**",
        "apps/desktop/test/support/bundled_font_loader.dart",
        "apps/desktop/test/layout/profiles/dashboard/mobile/**",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_bundle_test.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_shell_test.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_desktop_test_harness.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_feature_list_test.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_interaction_golden_test.dart",
        "apps/desktop/test/layout/profiles/dashboard/desktop/dashboard_main_content_card_test.dart",
        "apps/desktop/test/layout/profiles/desktop/**",
        "apps/desktop/test/layout/built_in_layout_composition_test.dart",
        "apps/desktop/test/layout/dashboard_feature_order_store_test.dart",
        "apps/desktop/test/layout/desktop_dock_layout_store_test.dart",
        "apps/desktop/test/layout/layout_agents_strategy_test.dart",
        "apps/desktop/test/layout/layout_catalog_test.dart",
        "apps/desktop/test/layout/layout_catalog_test_fixtures.dart",
        "apps/desktop/test/layout/layout_chrome_port_test.dart",
        "apps/desktop/test/layout/layout_destination_port_contract_test.dart",
        "apps/desktop/test/layout/layout_destination_port_mount_test.dart",
        "apps/desktop/test/layout/layout_destination_presentation_test.dart",
        "apps/desktop/test/layout/layout_host_fixture_test.dart",
        "apps/desktop/test/layout/layout_host_test_fixtures.dart",
        "apps/desktop/test/layout/layout_manager_test.dart",
        "apps/desktop/test/layout/layout_palette_test.dart",
        "apps/desktop/test/layout/layout_profile_contract_test.dart",
        "apps/desktop/test/layout/layout_scoped_state_fixture_test.dart",
        "apps/desktop/test/layout/layout_state_store_test.dart",
        "apps/desktop/test/layout/presentation_preferences_repository_test.dart",
        "apps/desktop/test/layout/semantic_destination_catalog_test.dart",
        "apps/desktop/test/layout_profile_selector_test.dart",
        "apps/desktop/test/client_android_orientation_test.dart",
      ],
      command: flutterTests([
        "test/layout/layout_manager_file_repository_test.dart",
        "test/layout/layout_manager_production_catalog_test.dart",
        "test/layout/built_in_layout_composition_test.dart",
        "test/layout/layout_agents_strategy_test.dart",
        "test/layout/layout_catalog_test.dart",
        "test/layout/layout_chrome_port_test.dart",
        "test/layout/layout_destination_port_contract_test.dart",
        "test/layout/layout_destination_port_mount_test.dart",
        "test/layout/layout_destination_presentation_test.dart",
        "test/layout/layout_manager_test.dart",
        "test/layout/layout_palette_test.dart",
        "test/layout/layout_profile_contract_test.dart",
        "test/layout/layout_state_store_test.dart",
        "test/layout/layout_host_fixture_test.dart",
        "test/layout/layout_scoped_state_fixture_test.dart",
        "test/layout/presentation_preferences_repository_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_bundle_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_desktop_shell_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_feature_list_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_interaction_golden_test.dart",
        "test/layout/profiles/dashboard/desktop/dashboard_main_content_card_test.dart",
        "test/layout/profiles/dashboard/mobile/dashboard_mobile_bundle_test.dart",
        "test/layout/profiles/dashboard/mobile/dashboard_mobile_shell_test.dart",
        "test/layout/profiles/desktop/desktop/desktop_desktop_bundle_test.dart",
        "test/layout/profiles/desktop/desktop/desktop_desktop_shell_test.dart",
        "test/layout/profiles/desktop/desktop/desktop_dock_model_test.dart",
        "test/layout/profiles/desktop/mobile/desktop_mobile_bundle_test.dart",
        "test/layout/profiles/desktop/mobile/desktop_mobile_golden_test.dart",
        "test/layout/profiles/desktop/mobile/desktop_mobile_shell_test.dart",
        "test/layout/dashboard_feature_order_store_test.dart",
        "test/layout/desktop_dock_layout_store_test.dart",
        "test/layout/production_baseline/production_layout_baseline_test.dart",
        "test/layout/production_baseline/production_layout_switch_continuity_test.dart",
        "test/layout/semantic_destination_catalog_test.dart",
        "test/layout_profile_selector_test.dart",
        "test/client_android_orientation_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layer.shell",
      kind: "flutter-layer",
      summary: "Application composition, navigation, localization, and shared shell",
      inputs: [
        "apps/desktop/lib/app.dart",
        "apps/desktop/lib/main.dart",
        "apps/desktop/lib/src/application/composition/**",
        "apps/desktop/lib/src/application/controller/client_conversation_archive_bindings.dart",
        "apps/desktop/lib/src/application/controller/client_lifecycle_coordinator.dart",
        "apps/desktop/lib/src/application/state/application_signal.dart",
        "apps/desktop/lib/src/contracts/client_process_lifecycle.dart",
        "apps/desktop/lib/src/application/localization/**",
        "apps/desktop/lib/src/application/features/models/**",
        "apps/desktop/lib/src/application/features/navigation/**",
        "apps/desktop/lib/src/application/features/agent_hub/**",
        "apps/desktop/lib/src/frontend/features/agent_hub/**",
        "apps/desktop/lib/src/contracts/agent_hub.dart",
        "apps/desktop/lib/src/frontend/l10n/**",
        "apps/desktop/lib/src/shared/l10n/lico_strings_catalog.dart",
        "apps/desktop/lib/src/projections/application_projection_source.dart",
        "apps/desktop/lib/src/projections/shell/shell_projection_producer.dart",
        "apps/desktop/lib/src/frontend/shared/**",
        "apps/desktop/lib/src/frontend/shell/**",
        "apps/desktop/lib/src/platform/process/client_process_lifecycle.dart",
        "apps/desktop/lib/src/platform/window_chrome/window_chrome_channel.dart",
        "apps/desktop/assets/brand/**",
        "apps/desktop/shaders/**",
        "apps/desktop/integration_test/**",
        "apps/desktop/test/apple_buttons_theme_test.dart",
        "apps/desktop/test/continuous_stroke_test.dart",
        "apps/desktop/test/lico_glass_test.dart",
        "apps/desktop/test/apple_notifications_chrome_test.dart",
        "apps/desktop/test/apple_popup_select_test.dart",
        "apps/desktop/test/apple_ui_dependency_boundary_test.dart",
        "apps/desktop/test/client_application_strings_test.dart",
        "apps/desktop/test/client_current_view_restore_test.dart",
        "apps/desktop/test/client_current_view_store_test.dart",
        "apps/desktop/test/client_controller_facade_boundary_test.dart",
        "apps/desktop/test/client_lifecycle_coordinator_test.dart",
        "apps/desktop/test/client_navigation_controller_test.dart",
        "apps/desktop/test/client_interface_entry_hook_controller_test.dart",
        "apps/desktop/test/client_interface_entry_hooks_test.dart",
        "apps/desktop/test/agent_hub_detail_tabs_test.dart",
        "apps/desktop/test/agent_hub_panel_test.dart",
        "apps/desktop/test/agent_hub_ports_test.dart",
        "apps/desktop/test/presentation_state_owners_test.dart",
        "apps/desktop/test/client_shell_mobile_layout_test.dart",
        "apps/desktop/test/client_shell_user_journey_test.dart",
        "apps/desktop/test/design_system_boundary_test.dart",
        "apps/desktop/test/i18n_contract_test.dart",
        "apps/desktop/test/l10n_library_boundary_test.dart",
        "apps/desktop/test/composer_activity_border_test.dart",
        "apps/desktop/test/messaging/conversation_material_profiles_test.dart",
        "apps/desktop/test/messaging/conversation_motion_surface_test.dart",
        "apps/desktop/test/loading_effect_test.dart",
        "apps/desktop/lib/src/frontend/appearance/loading_effect_catalog.dart",
        "apps/desktop/test/messaging/conversation_motion/orb_motion_test.dart",
        "apps/desktop/test/messaging/conversation_motion/conversation_particle_geometry_test.dart",
        "apps/desktop/test/messaging/conversation_motion/conversation_motion_widget_test.dart",
        "apps/desktop/test/messaging/conversation_motion/conversation_motion_visual_evidence_test.dart",
        "apps/desktop/test/messaging/external_composer_clip_test.dart",
        "apps/desktop/test/messaging/messaging_list_refresh_test.dart",
        "apps/desktop/test/reading_position_scroll_controller_test.dart",
        "apps/desktop/test/toast/lico_toast_test.dart",
        "apps/desktop/test/lico_pane_scaffold_test.dart",
        "apps/desktop/test/lico_pane_title_bar_test.dart",
        "apps/desktop/test/lico_search_capsule_test.dart",
        "apps/desktop/test/message_markdown_test.dart",
        "apps/desktop/test/message_markdown_component_boundary_test.dart",
        "apps/desktop/test/single_instance_guard_test.dart",
        "apps/desktop/test/theme_test.dart",
        "apps/desktop/test/widget_test.dart",
      ],
      command: flutterTests([
        "test/apple_buttons_theme_test.dart",
        "test/continuous_stroke_test.dart",
        "test/lico_glass_test.dart",
        "test/apple_notifications_chrome_test.dart",
        "test/apple_popup_select_test.dart",
        "test/apple_ui_dependency_boundary_test.dart",
        "test/client_application_strings_test.dart",
        "test/client_current_view_restore_test.dart",
        "test/client_current_view_store_test.dart",
        "test/client_controller_facade_boundary_test.dart",
        "test/client_lifecycle_coordinator_test.dart",
        "test/client_navigation_controller_test.dart",
        "test/client_interface_entry_hook_controller_test.dart",
        "test/client_interface_entry_hooks_test.dart",
        "test/agent_hub_detail_tabs_test.dart",
        "test/agent_hub_panel_test.dart",
        "test/agent_hub_ports_test.dart",
        "test/presentation_state_owners_test.dart",
        "test/client_shell_mobile_layout_test.dart",
        "test/client_shell_user_journey_test.dart",
        "test/design_system_boundary_test.dart",
        "test/i18n_contract_test.dart",
        "test/l10n_library_boundary_test.dart",
        "test/composer_activity_border_test.dart",
        "test/messaging/conversation_material_profiles_test.dart",
        "test/messaging/conversation_motion_surface_test.dart",
        "test/loading_effect_test.dart",
        "test/messaging/conversation_motion/orb_motion_test.dart",
        "test/messaging/conversation_motion/conversation_particle_geometry_test.dart",
        "test/messaging/conversation_motion/conversation_motion_widget_test.dart",
        "test/messaging/conversation_motion/conversation_motion_visual_evidence_test.dart",
        "test/messaging/external_composer_clip_test.dart",
        "test/messaging/messaging_list_refresh_test.dart",
        "test/reading_position_scroll_controller_test.dart",
        "test/toast/lico_toast_test.dart",
        "test/lico_pane_scaffold_test.dart",
        "test/lico_pane_title_bar_test.dart",
        "test/lico_search_capsule_test.dart",
        "test/message_markdown_test.dart",
        "test/message_markdown_component_boundary_test.dart",
        "test/single_instance_guard_test.dart",
        "test/theme_test.dart",
        "test/widget_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.layer.platform-storage",
      kind: "flutter-layer",
      summary: "Portable data, workspace manifests, clipboard, and log storage",
      inputs: [
        "apps/desktop/lib/src/platform/storage/**",
        "apps/desktop/lib/src/platform/client_clipboard_service.dart",
        "apps/desktop/lib/src/platform/runtime_platform_bridge.dart",
        "apps/desktop/test/client_clipboard_service_test.dart",
        "apps/desktop/test/client_log_export_service_test.dart",
        "apps/desktop/test/client_workspace_manifest_component_test.dart",
        "apps/desktop/test/portable_data_root_test.dart",
      ],
      command: flutterTests([
        "test/client_clipboard_service_test.dart",
        "test/client_log_export_service_test.dart",
        "test/client_workspace_manifest_component_test.dart",
        "test/portable_data_root_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.continuous-assistant.pane",
      kind: "flutter-feature",
      summary: "Parent task card, child entry, and projection for continuous-assistant panes",
      inputs: [
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_child_entry.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_host_scope.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_keys.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_labels.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_parent_card.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_surfaces.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_projection.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_task_view.dart",
        "apps/desktop/test/continuous_assistant/support/continuous_assistant_test_harness.dart",
        "apps/desktop/test/continuous_assistant/continuous_assistant_projection_test.dart",
        "apps/desktop/test/continuous_assistant/continuity_contract_test.dart",
        "apps/desktop/test/continuous_assistant/host_integration_test.dart",
      ],
      command: flutterTests([
        "test/continuous_assistant/continuous_assistant_projection_test.dart",
        "test/continuous_assistant/continuity_contract_test.dart",
        "test/continuous_assistant/host_integration_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.continuous-assistant.toast",
      kind: "flutter-feature",
      summary: "Single existing-system completion notice without focus theft",
      inputs: [
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_completion_notice.dart",
        "apps/desktop/test/continuous_assistant/completion_notice_delivery_test.dart",
      ],
      command: flutterTests([
        "test/continuous_assistant/completion_notice_delivery_test.dart",
      ]),
    }),
  defineModule({
    id: "flutter.layer.diagnostics-v7-observation-port",
    kind: "flutter-layer",
    summary: "Bounded Dart observation probe, correlation ids, and segment records in the platform diagnostic layer",
    inputs: [
      "apps/desktop/lib/src/platform/diagnostics/observation/**",
      "apps/desktop/test/platform/diagnostics/observation/observation_probe_test.dart",
    ],
    command: flutterTests([
      "test/platform/diagnostics/observation/observation_probe_test.dart",
    ]),
  }),
]);
