import { flutterTests, defineModule } from "../../helpers.mjs";

export const COLLABORATION_MODULES = Object.freeze([
  defineModule({
    id: "flutter.feature.project-collaboration",
    kind: "flutter-feature",
    summary:
      "Native project collaboration: versioned graph resource capability, prepared worker layout, shared-gate swimlanes, and host-owned actions",
    inputs: [
      "apps/desktop/lib/src/projections/project_collaboration/**",
      "apps/desktop/lib/src/presentation/project_collaboration/**",
      "apps/desktop/lib/src/frontend/features/project_collaboration/**",
      "apps/desktop/lib/src/composition/extensions/**",
      "apps/desktop/test/project_collaboration/**",
      "apps/desktop/test/ui_state_machine/project_collaboration_harness.dart",
      "packages/presentation_contract/lib/src/graph/**",
      "packages/presentation_runtime/lib/src/graph/**",
      "packages/presentation_flutter/lib/src/graph/**",
      "packages/presentation_flutter/lib/src/extensions/**",
      "schemas/extensions/graph-resource.schema.json",
      "schemas/extensions/ui.schema.json",
      "crates/licoup-extension-contracts/src/ui.rs",
      "apps/desktop/test/ui_state_machine/model.json",
    ],
    command: flutterTests(["test/project_collaboration"]),
  }),
  defineModule({
      id: "flutter.feature.mcp-transfer",
      kind: "flutter-feature",
      summary: "MCP transfer preview, explicit confirmation, and private native execution",
      inputs: [
        "apps/desktop/lib/src/contracts/mcp_adapter.dart",
        "apps/desktop/lib/src/application/features/mcp/controller/mcp_transfer_controller.dart",
        "apps/desktop/lib/src/platform/native_client/native_mcp_actions.dart",
        "apps/desktop/test/mcp_transfer_controller_test.dart",
        "apps/desktop/test/native_mcp_actions_test.dart",
      ],
      command: flutterTests([
        "test/mcp_transfer_controller_test.dart",
        "test/native_mcp_actions_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration",
      kind: "flutter-feature",
      summary: "Disabled-by-default, explicit-confirmation optional collaboration lifecycle",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_controller.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_controller_context.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_workflow_action_context.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_workflow_controller.dart",
        "apps/desktop/lib/src/backend/features/settings/services/optional_collaboration_service.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_gateway.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_catalog_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_kind.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_parsing.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_plan_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_workflow_result_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_catalog_action.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings_action_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings_policy.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_status_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_workflow_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_workflow_plan_review.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings.dart",
        "apps/desktop/test/optional_collaboration_controller_test.dart",
        "apps/desktop/test/optional_collaboration_models_test.dart",
        "apps/desktop/test/optional_collaboration_service_test.dart",
        "apps/desktop/test/optional_collaboration_settings_boundary_test.dart",
        "apps/desktop/test/optional_collaboration_settings_test.dart",
        "apps/desktop/test/optional_collaboration_workflow_controller_test.dart",
        "apps/desktop/test/optional_collaboration_workflow_models_test.dart",
        "apps/desktop/test/optional_collaboration_workflow_service_test.dart",
        "apps/desktop/test/support/optional_collaboration_test_fixtures.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_controller_test.dart",
        "test/optional_collaboration_local_server_parser_test.dart",
        "test/optional_collaboration_models_test.dart",
        "test/optional_collaboration_service_test.dart",
        "test/optional_collaboration_settings_boundary_test.dart",
        "test/optional_collaboration_settings_test.dart",
        "test/optional_collaboration_workflow_controller_test.dart",
        "test/optional_collaboration_workflow_models_test.dart",
        "test/optional_collaboration_workflow_service_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.runner-trust",
      kind: "flutter-feature",
      summary: "Direct-user runner trust import and removal bound to key, source repository, fixed identity, and fingerprint",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_runner_trust_actions.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_model_parsing.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_runner_trust_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_controller_test.dart",
        "test/optional_collaboration_models_test.dart",
        "test/optional_collaboration_service_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.install-lifecycle",
      kind: "flutter-feature",
      summary: "Explicit enablement, exact-commit install planning, plan cancellation, application, disablement, and uninstall",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_install_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_lifecycle_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_plugin_binding.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_install_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_plugin_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_install_plan_review.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_controller_test.dart",
        "test/optional_collaboration_models_test.dart",
        "test/optional_collaboration_service_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.local-server-assembly",
      kind: "flutter-feature",
      summary: "Typed local assembly, digest-bound signed-runner deployment, verified runtime lifecycle, and direct approvals",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_local_assembly_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_server_runtime_actions.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_assembly_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_identity.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_lifecycle_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_models.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_parser.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_parsing.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_local_server_state.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_local_server_card.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_workflow_choice_subtitle.dart",
        "apps/desktop/test/optional_collaboration_local_server_models_test.dart",
        "apps/desktop/test/optional_collaboration_local_server_parser_test.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_local_server_models_test.dart",
        "test/optional_collaboration_local_server_parser_test.dart",
        "test/optional_collaboration_workflow_models_test.dart",
        "test/optional_collaboration_workflow_service_test.dart",
        "test/optional_collaboration_workflow_controller_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.optional-collaboration.mcp-install",
      kind: "flutter-feature",
      summary: "Agent-scoped MCP installation planning, local destination binding, per-file approval, cancellation, and apply",
      inputs: [
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_mcp_actions.dart",
        "apps/desktop/lib/src/application/features/settings/controller/optional_collaboration_workflow_validation.dart",
        "apps/desktop/lib/src/contracts/optional_collaboration_mcp_workflow_models.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_agent_destination_editor.dart",
        "apps/desktop/lib/src/frontend/features/plugin_management/ui/optional_collaboration_settings.dart",
      ],
      command: flutterTests([
        "test/optional_collaboration_workflow_models_test.dart",
        "test/optional_collaboration_workflow_service_test.dart",
        "test/optional_collaboration_workflow_controller_test.dart",
        "test/optional_collaboration_settings_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay",
      kind: "flutter-feature",
      summary: "Mobile relay, local pairing, and Secure Mesh UI",
      inputs: [
        "apps/desktop/lib/src/application/features/mobile_relay/controller/mobile_home_layout_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/mobile_relay_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/policy/**",
        "apps/desktop/lib/src/application/composition/mobile_home_layout_repository_adapter.dart",
        "apps/desktop/lib/src/application/composition/mobile_relay_client_adapter.dart",
        "apps/desktop/lib/src/backend/features/mobile_relay/**",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_add_agent.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agent_list.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agent_list_items.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agent_nav_icon.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_agents_home.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_desktop_agent_list.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_home_entry_ordering.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_local_agent.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_pair_device_scanner.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_surface_gestures.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_swipe_pin_action.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/secure_mesh_approval_card.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/secure_mesh_capability_card.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/secure_mesh_file_sync_card.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/shell_pair_device_dialog.dart",
        "apps/desktop/lib/src/platform/mobile_relay/**",
        "apps/desktop/lib/src/contracts/mobile_home_layout.dart",
        "apps/desktop/lib/src/contracts/mobile_home_layout_repository.dart",
        "apps/desktop/lib/src/contracts/mobile_pairing_presentation.dart",
        "apps/desktop/lib/src/contracts/mobile_relay/**",
        "apps/desktop/lib/src/contracts/mobile_relay_control.dart",
        "apps/desktop/lib/src/contracts/generated/secure_mesh.g.dart",
        "apps/desktop/test/fixtures/mobile_relay_presentation_fixture.dart",
        "apps/desktop/test/mobile_agents_home_boundary_test.dart",
        "apps/desktop/test/mobile_agents_home_regions_test.dart",
        "apps/desktop/test/mobile_agent_list_component_boundary_test.dart",
        "apps/desktop/test/mobile_home_entry_ordering_test.dart",
        "apps/desktop/test/mobile_home_layout_controller_test.dart",
        "apps/desktop/test/mobile_pairing_policy_test.dart",
        "apps/desktop/test/mobile_relay_panel/pair_device_dialog_test.dart",
        "apps/desktop/test/mobile_relay_component_boundary_test.dart",
        "apps/desktop/test/mobile_relay_controller_test.dart",
        "apps/desktop/test/mobile_relay_station_validation_test.dart",
        "apps/desktop/test/mobile_relay_models_boundary_test.dart",
        "apps/desktop/test/mobile_relay_operations_test.dart",
        "apps/desktop/test/mobile_relay_presentation_sources_test.dart",
        "apps/desktop/test/mobile_relay_secure_mesh_operations_test.dart",
        "apps/desktop/test/mobile_relay_service_test.dart",
        "apps/desktop/test/secure_mesh_capability_service_test.dart",
        "apps/desktop/test/secure_mesh_panel_test.dart",
        "apps/desktop/test/support/fake_mobile_relay_dispatch.dart",
      ],
      command: flutterTests([
        "test/mobile_agents_home_boundary_test.dart",
        "test/mobile_agents_home_regions_test.dart",
        "test/mobile_agent_list_component_boundary_test.dart",
        "test/mobile_home_entry_ordering_test.dart",
        "test/mobile_home_layout_controller_test.dart",
        "test/mobile_pairing_policy_test.dart",
        "test/mobile_relay_panel/pair_device_dialog_test.dart",
        "test/mobile_relay_component_boundary_test.dart",
        "test/mobile_relay_controller_test.dart",
        "test/mobile_relay_station_validation_test.dart",
        "test/mobile_relay_models_boundary_test.dart",
        "test/mobile_relay_operations_test.dart",
        "test/mobile_relay_presentation_sources_test.dart",
        "test/mobile_relay_secure_mesh_operations_test.dart",
        "test/mobile_relay_service_test.dart",
        "test/secure_mesh_capability_service_test.dart",
        "test/secure_mesh_panel_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.configuration",
      kind: "flutter-feature",
      summary: "Local mobile layout persistence and station configuration",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/configuration_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/configuration_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.pairing",
      kind: "flutter-feature",
      summary: "Pairing projection, reset, station selection, sync, and Secure Mesh operations",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/pairing_scenarios.dart",
        "apps/desktop/test/fixtures/mobile_relay/config_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/pairing_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.android-bridge",
      kind: "flutter-feature",
      summary: "Android Secure Mesh status and app-private runtime receipt bridge",
      inputs: [
        "apps/desktop/android/app/src/main/kotlin/land/lico/licoup/SecureMeshAndroidAtomicRecordWriter.kt",
        "apps/desktop/android/app/src/main/kotlin/land/lico/licoup/SecureMeshAndroidNativeDispatchQueue.kt",
        "apps/desktop/test/fixtures/mobile_relay/android_bridge_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/android_bridge_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.relay-poll",
      kind: "flutter-feature",
      summary: "Relay command binding, completion validation, and redacted failures",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/relay_poll_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/relay_poll_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.session-list",
      kind: "flutter-feature",
      summary: "Native session projection, deduplication, paging, and payload bounds",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/session_list_scenarios.dart",
        "apps/desktop/test/fixtures/mobile_relay/session_fixtures.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/session_list_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.scenario.ios-bridge",
      kind: "flutter-feature",
      summary: "iOS Secure Mesh status and native JSON method-channel bridge",
      inputs: [
        "apps/desktop/test/fixtures/mobile_relay/ios_bridge_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/mobile_relay/ios_bridge_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-composition",
      kind: "flutter-feature",
      summary: "Thin Mobile Relay panel facade, platform routing, and Secure Mesh card composition",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_pairing_channels.dart",
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/composition.dart",
        "apps/desktop/test/mobile_relay_panel/composition_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/composition_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-pairing",
      kind: "flutter-feature",
      summary: "Explicit station, pairing status, one-time code, and copy presentation",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/pairing.dart",
        "apps/desktop/test/mobile_relay_panel/pairing_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/pairing_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-qr",
      kind: "flutter-feature",
      summary: "Pairing invite QR rendering and configured-station generation gate",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/qr.dart",
        "apps/desktop/test/mobile_relay_panel/qr_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/qr_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-scan",
      kind: "flutter-feature",
      summary: "Mobile pairing scan prompt and platform-native scan affordance",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/scan.dart",
        "apps/desktop/test/mobile_relay_panel/scan_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/scan_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.panel-trust",
      kind: "flutter-feature",
      summary: "Device trust state, fingerprints, safety number, and verification QR",
      inputs: [
        "apps/desktop/lib/src/frontend/features/mobile_relay/ui/mobile_relay_panel/trust.dart",
        "apps/desktop/test/mobile_relay_panel/trust_test.dart",
        "apps/desktop/test/mobile_relay_panel/panel_test_harness.dart",
      ],
      command: flutterTests([
        "test/mobile_relay_panel/trust_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.mobile-relay.secure-mesh-controller",
      kind: "flutter-feature",
      summary: "Secure Mesh status, approval, protocol, file, and skill controller composition",
      inputs: [
        "apps/desktop/resources/state-machines/secure-mesh.json",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/generated/secure_mesh_state_machines.g.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_approval_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_controller_support.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_file_transfer_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_protocol_controller.dart",
        "apps/desktop/lib/src/application/features/mobile_relay/controller/secure_mesh_status_controller.dart",
        "apps/desktop/test/secure_mesh_component_boundary_test.dart",
        "apps/desktop/test/secure_mesh_component_controllers_test.dart",
        "apps/desktop/test/secure_mesh_controller_test.dart",
      ],
      command: flutterTests([
        "test/secure_mesh_component_boundary_test.dart",
        "test/secure_mesh_component_controllers_test.dart",
        "test/secure_mesh_controller_test.dart",
      ]),
    }),
]);
