import { FAKE_AGENT_SERVICE_INPUTS, flutterTests, defineModule } from "../../helpers.mjs";

export const CONTROLLERS_MODULES = Object.freeze([
  defineModule({
      id: "flutter.controller.facade",
      kind: "flutter-controller",
      summary: "Thin ClientController and focused runtime facade delegation",
      inputs: [
        "apps/desktop/lib/src/application/controller/client_controller.dart",
        "apps/desktop/lib/src/application/controller/client_agent_usage_facade.dart",
        "apps/desktop/lib/src/application/controller/client_conversation_archive_bindings.dart",
        "apps/desktop/lib/src/application/controller/client_conversation_facade.dart",
        "apps/desktop/lib/src/application/controller/client_lifecycle_facade.dart",
        "apps/desktop/lib/src/application/controller/client_maintenance_facade.dart",
        "apps/desktop/lib/src/application/controller/client_mobile_relay_facade.dart",
        "apps/desktop/lib/src/application/controller/client_navigation_facade.dart",
        "apps/desktop/lib/src/application/controller/client_routing_facade.dart",
        "apps/desktop/lib/src/application/controller/client_skill_hub_facade.dart",
        "apps/desktop/lib/src/application/controller/client_target_facade.dart",
        "apps/desktop/test/client_controller_facade_boundary_test.dart",
        "apps/desktop/test/client_controller_runtime_facades_test.dart",
        "apps/desktop/test/client_controller_construction_test.dart",
      ],
      command: flutterTests([
        "test/client_controller_facade_boundary_test.dart",
        "test/client_controller_runtime_facades_test.dart",
        "test/client_controller_construction_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.boundary",
      kind: "flutter-controller",
      summary: "Root component assembly and independent factory boundaries",
      inputs: [
        "apps/desktop/lib/src/application/controller/client_component_assembly.dart",
        "apps/desktop/lib/src/application/controller/assembly/client_component_assembly_contracts.dart",
        "apps/desktop/lib/src/application/controller/assembly/client_agent_hub_component_assembly.dart",
        "apps/desktop/lib/src/application/features/agent_hub/agent_hub_catalog_controller.dart",
        "apps/desktop/test/client_component_assembly_leaves_test.dart",
        "apps/desktop/test/client_controller_component_boundary_test.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/client_controller_component_boundary_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.lifecycle",
      kind: "flutter-controller",
      summary: "Authoritative client lifecycle state machine and immutable projection",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_lifecycle_component_assembly.dart",
        "apps/desktop/lib/src/application/controller/client_lifecycle_coordinator.dart",
        "apps/desktop/test/client_lifecycle_coordinator_test.dart",
      ],
      command: flutterTests(["test/client_lifecycle_coordinator_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.assembly.conversation",
      kind: "flutter-controller",
      summary: "Conversation gateways and presentation signal factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_conversation_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/conversation_presentation_signals_test.dart",
        "test/canonical_conversation_activity_echo_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.target",
      kind: "flutter-controller",
      summary: "Target discovery controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_target_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/target_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.skill",
      kind: "flutter-controller",
      summary: "Skill Hub controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_skill_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/skill_hub_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.settings",
      kind: "flutter-controller",
      summary: "Settings and maintenance controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_settings_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/client_update_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.mobile",
      kind: "flutter-controller",
      summary: "Mobile Relay and Secure Mesh controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_mobile_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/mobile_relay_component_boundary_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.usage",
      kind: "flutter-controller",
      summary: "Agent usage controller factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_usage_component_assembly.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/agent_usage_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.navigation",
      kind: "flutter-controller",
      summary: "Client navigation hook factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_navigation_component_assembly.dart",
        "apps/desktop/lib/src/application/features/navigation/controller/client_interface_entry_hook_controller.dart",
        "apps/desktop/test/client_interface_entry_hook_controller_test.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/client_navigation_controller_test.dart",
        "test/client_interface_entry_hook_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.assembly.presentation",
      kind: "flutter-controller",
      summary: "Shell and layout presentation factory",
      inputs: [
        "apps/desktop/lib/src/application/controller/assembly/client_presentation_component_assembly.dart",
        "apps/desktop/lib/src/application/controller/appearance_preference_owner.dart",
        "apps/desktop/lib/src/application/controller/client_appearance_commands.dart",
        "apps/desktop/lib/src/application/controller/client_functional_status_commands.dart",
        "apps/desktop/lib/src/application/controller/client_locale_commands.dart",
        "apps/desktop/lib/src/application/controller/functional_status_runtime.dart",
        "apps/desktop/lib/src/application/controller/locale_preference_owner.dart",
      ],
      command: flutterTests([
        "test/client_component_assembly_leaves_test.dart",
        "test/presentation_state_owners_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.scenario.bootstrap",
      kind: "flutter-controller",
      summary: "Client bootstrap, portable data, and initial relay behavior",
      inputs: [
        "apps/desktop/test/client_bootstrap_test.dart",
        "apps/desktop/test/local_conversation_startup_priority_test.dart",
        "apps/desktop/test/fixtures/client_controller_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/bootstrap_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/entry_hook_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        "apps/desktop/test/fixtures/client_controller/support/no_entry_hook_client_controller.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
        "apps/desktop/test/fixtures/client_controller/support/fake_mobile_relay_service.dart",
      ],
      command: flutterTests([
        "test/client_bootstrap_test.dart",
        "test/local_conversation_startup_priority_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.scenario.target",
      kind: "flutter-controller",
      summary: "Target discovery, selection, and tab ordering behavior",
      inputs: [
        "apps/desktop/test/client_target_test.dart",
        "apps/desktop/test/fixtures/client_controller/target_history_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/target_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_target_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.mobile-history",
      kind: "flutter-controller",
      summary: "Mobile Secure Mesh native history pagination and exact selection",
      inputs: [
        "apps/desktop/test/client_mobile_history_test.dart",
        "apps/desktop/test/fixtures/client_controller/mobile_history_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
        "apps/desktop/test/fixtures/client_controller/support/fake_mobile_relay_service.dart",
      ],
      command: flutterTests(["test/client_mobile_history_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.history-refresh",
      kind: "flutter-controller",
      summary: "Native history streaming, paging, refresh, and scheduler behavior",
      inputs: [
        "apps/desktop/test/client_history_refresh_test.dart",
        "apps/desktop/test/fixtures/client_controller/history_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/history_refresh_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_history_refresh_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.history-runtime",
      kind: "flutter-controller",
      summary: "Cached history selection and active native runtime turn behavior",
      inputs: [
        "apps/desktop/test/client_history_runtime_test.dart",
        "apps/desktop/test/fixtures/client_controller/history_runtime_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/history_runtime/**",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_history_runtime_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.conversation-dispatch",
      kind: "flutter-controller",
      summary: "Conversation runtime dispatch, refresh, and failure behavior",
      inputs: [
        "apps/desktop/test/client_conversation_dispatch_test.dart",
        "apps/desktop/test/client_conversation_controller_test.dart",
        "apps/desktop/test/fixtures/client_controller/conversation_dispatch_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests([
        "test/client_conversation_dispatch_test.dart",
        "test/client_conversation_controller_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.controller.scenario.local-management",
      kind: "flutter-controller",
      summary: "Local skill, archive, snapshot, and management behavior",
      inputs: [
        "apps/desktop/test/client_local_management_test.dart",
        "apps/desktop/test/fixtures/client_controller/local_management_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/conversation_archive_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/skill_freshness_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/skill_management_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/local_management/target_management_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
      ],
      command: flutterTests(["test/client_local_management_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.scenario.secure-mesh",
      kind: "flutter-controller",
      summary: "Secure Mesh pairing, command, file, skill, and approval behavior",
      inputs: [
        "apps/desktop/test/client_secure_mesh_test.dart",
        "apps/desktop/test/fixtures/client_controller/secure_mesh_scenarios.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_dependencies.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_environment.dart",
        "apps/desktop/test/fixtures/client_controller/support/client_controller_scenario_json.dart",
        ...FAKE_AGENT_SERVICE_INPUTS,
        "apps/desktop/test/fixtures/client_controller/support/fake_mobile_relay_service.dart",
        "apps/desktop/test/fixtures/client_controller/support/no_entry_hook_client_controller.dart",
      ],
      command: flutterTests(["test/client_secure_mesh_test.dart"]),
    }),
  defineModule({
      id: "flutter.controller.continuous-assistant",
      kind: "flutter-controller",
      summary: "Continuous-assistant command intent and late-get controller isolation",
      inputs: [
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_command_bar.dart",
        "apps/desktop/lib/src/frontend/features/continuous_assistant/continuous_assistant_command_intent.dart",
        "apps/desktop/test/continuous_assistant/controller_c1_test.dart",
      ],
      command: flutterTests([
        "test/continuous_assistant/controller_c1_test.dart",
      ]),
    }),
]);
