import { flutterTests, defineModule } from "../../helpers.mjs";

export const CONVERSATION_MODULES = Object.freeze([
  defineModule({
      id: "flutter.feature.agent-conversations",
      kind: "flutter-feature",
      summary: "Local agent conversation lifecycle, archive, projection, and UI",
      inputs: [
        "apps/desktop/lib/src/application/features/agents/agent_product_names.dart",
        "apps/desktop/lib/src/application/features/agents/archive/**",
        "apps/desktop/lib/src/application/features/agents/contracts/agent_conversation_gateway.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/agent_conversation_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/agent_conversation_read_only_policy.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_live_projection_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/persistent_turn_process_observer.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_execution_observer.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_message_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_mobile_session_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_presentation_signals.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_refresh_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_relay_projection_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_runtime_result_policy.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_runtime_options.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_turn_process_state.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/cursor_ide_cli_handoff.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_selection_store.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/agent_conversation_search_index.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_session_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_session_state_controller.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_working_directory_fallback.dart",
        "apps/desktop/lib/src/contracts/user_home_directory.dart",
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_state_holder.dart",
        "apps/desktop/lib/src/application/features/conversations/**",
        "apps/desktop/lib/src/application/features/agents/policy/conversation_refresh_policy.dart",
        "apps/desktop/lib/src/application/features/agents/policy/conversation_session_index.dart",
        "apps/desktop/lib/src/application/features/messaging/messaging_notification_center.dart",
        "apps/desktop/lib/src/application/composition/agent_conversation_gateway_adapter.dart",
        "apps/desktop/lib/src/backend/features/agents/services/agent_conversation_archive_service.dart",
        "apps/desktop/lib/src/backend/features/agents/services/agent_conversation_service.dart",
        "apps/desktop/lib/src/backend/features/conversations/**",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_composer.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_composer_capsules.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_image_attachments.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_layout_metrics.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_display.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_metadata_fields.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_view.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_participant_runtime_profile.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_parity_disclosure.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_runtime_settings.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_session_presentation.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_timeline.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_truncation_notice.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_virtual_machine_destination.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_usage_segmented_control.dart",
        "apps/desktop/lib/src/frontend/features/agents/data/plan_document_loader.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/lico_plan_document_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_search_palette.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/destination_search_ranking.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_workspace.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/assistant_configuration_dialog.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation_execution_entry.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation_execution_binding_viewer.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation_failure_notice.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/execution_process/**",
        "apps/desktop/lib/src/frontend/features/agents/ui/global_search_features.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_agent_avatar.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_agent_bubble.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_bubble_edge_glow.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_contact_list.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_conversation_header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_conversation_menu.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_conversation_switcher.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_conversation_overlay_glass.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_details_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_message_group.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_glass_option_card.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_hover_popover.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_participant_flow.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_scroll_to_latest_button.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/messaging/messaging_user_bubble_glass.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/create_dialog.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/pane.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/projection.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/reveal.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/roster.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/sidebar.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/strategy.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation/canonical_group_conversation_pane/support.dart",
        "apps/desktop/lib/src/events/event_sender.dart",
        "apps/desktop/lib/src/presentation/conversation/canonical_conversation_event_metadata.dart",
        "apps/desktop/lib/src/protocol/protocol_connection_state.dart",
        "apps/desktop/lib/src/protocol/protocol_frame_sink.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_context_projection.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_attachment.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_message.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_message_page.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/native_subagent_history_scope.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_message_parser.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_models.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_privacy_projection.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_semantic.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_session.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_structured_projection.dart",
        "apps/desktop/lib/src/contracts/agent_conversation_tab_activity.dart",
        "apps/desktop/lib/src/contracts/agent_dispatch_lane.dart",
        "apps/desktop/lib/src/contracts/agent_tool_allowlist_repository.dart",
        "apps/desktop/lib/src/contracts/client_conversation_models.dart",
        "apps/desktop/lib/src/contracts/conversation_native_port.dart",
        "apps/desktop/lib/src/contracts/conversation_execution.dart",
        "apps/desktop/lib/src/contracts/conversation_execution_port.dart",
        "apps/desktop/lib/src/contracts/client_memory_diagnostics.dart",
        "apps/desktop/lib/src/contracts/conversation_attachment_release.dart",
        "apps/desktop/lib/src/contracts/conversation_image_byte_reader.dart",
        "apps/desktop/lib/src/contracts/plan_document_reader.dart",
        "apps/desktop/lib/src/platform/conversation/conversation_image_byte_reader.dart",
        "apps/desktop/lib/src/platform/documents/plan_document_reader.dart",
        "apps/desktop/lib/src/platform/storage/client_memory_diagnostic_log.dart",
        "packages/contracts/client/semantic-conversation.schema.json",
        "apps/desktop/test/agent_conversation_archive_component_test.dart",
        "apps/desktop/test/agent_conversation_archive_test.dart",
        "apps/desktop/test/agent_conversation_component_boundary_test.dart",
        "apps/desktop/test/agent_conversation_composer_test.dart",
        "apps/desktop/test/agent_conversation_composer_apple_chrome_test.dart",
        "apps/desktop/test/agent_conversation_composer_capsules_test.dart",
        "apps/desktop/test/agent_conversation_dispatch_test.dart",
        "apps/desktop/test/local_conversation_flow_test.dart",
        "apps/desktop/test/agent_conversation_history_loading_test.dart",
        "apps/desktop/test/agent_conversation_message_paging_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/native_subagent_history_test.dart",
        "apps/desktop/test/native_child_conversation_paging_test.dart",
        "apps/desktop/test/agent_conversation_image_attachments_test.dart",
        "apps/desktop/test/agent_conversation_local_read_only_test.dart",
        "apps/desktop/test/agent_conversation_message_display_test.dart",
        "apps/desktop/test/agent_conversation_message_merge_test.dart",
        "apps/desktop/test/agent_conversation_model_boundary_test.dart",
        "apps/desktop/test/agent_conversation_parity_disclosure_test.dart",
        "apps/desktop/test/agent_conversation_privacy_projection_test.dart",
        "apps/desktop/test/agent_conversation_projection_test.dart",
        "apps/desktop/test/agent_conversation_queue_failure_cancel_test.dart",
        "apps/desktop/test/agent_conversation_runtime_settings_test.dart",
        "apps/desktop/test/agent_conversation_timeline_test.dart",
        "apps/desktop/test/agent_conversation_transport_error_test.dart",
        "apps/desktop/test/conversation_runtime_result_policy_test.dart",
        "apps/desktop/test/conversation_failure_attribution_test.dart",
        "apps/desktop/test/group_assistant_name_control_test.dart",
        "apps/desktop/test/conversation_browse_catalog_ensure_test.dart",
        "apps/desktop/test/conversation_catalog_refresh_intent_test.dart",
        "apps/desktop/test/conversation_selection_loading_test.dart",
        "apps/desktop/test/agent_conversation_search_index_test.dart",
        "apps/desktop/test/agent_conversation_search_palette_test.dart",
        "apps/desktop/test/destination_search_ranking_test.dart",
        "apps/desktop/test/agent_conversation_semantic_test.dart",
        "apps/desktop/test/agent_conversation_send_availability_copy_test.dart",
        "apps/desktop/test/agent_conversation_send_failure_projection_test.dart",
        "apps/desktop/test/agent_conversation_sidebar_test.dart",
        "apps/desktop/test/agent_conversation_tab_activity_test.dart",
        "apps/desktop/test/client_conversation_archive_bindings_test.dart",
        "apps/desktop/test/client_conversation_recent_participants_test.dart",
        "apps/desktop/test/client_conversation_controller_test.dart",
        "apps/desktop/test/client_conversation_service_test.dart",
        "apps/desktop/test/canonical_conversation_paging_test.dart",
        "apps/desktop/test/canonical_conversation_paging_surface_test.dart",
        "apps/desktop/test/support/fake_conversation_transport.dart",
        "apps/desktop/test/support/canonical_group/paged_conversation_native.dart",
        "apps/desktop/test/client_memory_diagnostic_journal_test.dart",
        "apps/desktop/test/client_memory_diagnostic_log_test.dart",
        "apps/desktop/test/canonical_group_conversation_projection_test.dart",
        "apps/desktop/test/canonical_group_roster_visibility_test.dart",
        "apps/desktop/test/group_native_session_membership_test.dart",
        "apps/desktop/test/group_native_session_sidebar_test.dart",
        "apps/desktop/test/canonical_group_assistant_surface_test.dart",
        "apps/desktop/test/canonical_group_live_turn_test.dart",
        "apps/desktop/test/canonical_group_strategy_mode_test.dart",
        "apps/desktop/test/conversation_attachment_flow_test.dart",
        "apps/desktop/test/conversation_execution_observer_test.dart",
        "apps/desktop/test/conversation_execution_projection_test.dart",
        "apps/desktop/test/execution_process/execution_document_test.dart",
        "apps/desktop/test/execution_process/conversation_execution_viewer_test.dart",
        "apps/desktop/test/execution_process/execution_viewer_visual_test.dart",
        "apps/desktop/test/messaging/conversation_reply_surface_test.dart",
        "apps/desktop/test/conversation_presentation_signals_test.dart",
        "apps/desktop/test/canonical_conversation_activity_echo_test.dart",
        "apps/desktop/test/conversation_refresh_policy_test.dart",
        "apps/desktop/test/conversation_session_index_test.dart",
        "apps/desktop/test/conversation_session_readback_test.dart",
        "apps/desktop/test/conversation_turn_process_state_test.dart",
        "apps/desktop/test/conversation_working_directory_fallback_test.dart",
        "apps/desktop/test/conversation_state_holder_test.dart",
        "apps/desktop/test/cursor_ide_cli_handoff_test.dart",
        "apps/desktop/test/lico_plan_document_panel_test.dart",
        "apps/desktop/test/fixtures/agent_conversation_service_scenarios.dart",
        "apps/desktop/test/messaging/messaging_bubble_edge_glow_test.dart",
        "apps/desktop/test/messaging/messaging_composer_strategy_test.dart",
        "apps/desktop/test/messaging/messaging_contact_list_test.dart",
        "apps/desktop/test/messaging/messaging_conversation_switcher_test.dart",
        "apps/desktop/test/messaging/messaging_conversation_overlay_glass_test.dart",
        "apps/desktop/test/messaging/messaging_details_panel_test.dart",
        "apps/desktop/test/messaging/messaging_glass_option_card_test.dart",
        "apps/desktop/test/messaging/messaging_image_attachment_test.dart",
        "apps/desktop/test/messaging/messaging_participant_flow_test.dart",
        "apps/desktop/test/messaging/messaging_sidebar_surface_test.dart",
        "apps/desktop/test/messaging/messaging_user_bubble_glass_test.dart",
        "apps/desktop/test/messaging/messaging_workspace_selection_test.dart",
        "apps/desktop/test/messaging_notification_center_test.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_archive_component_test.dart",
        "test/agent_conversation_archive_test.dart",
        "test/agent_conversation_component_boundary_test.dart",
        "test/agent_conversation_composer_test.dart",
        "test/agent_conversation_composer_apple_chrome_test.dart",
        "test/agent_conversation_composer_capsules_test.dart",
        "test/agent_conversation_dispatch_test.dart",
        "test/local_conversation_flow_test.dart",
        "test/agent_conversation_history_loading_test.dart",
        "test/agent_conversation_message_paging_test.dart",
        "test/agent_conversation_message_blocks/native_subagent_history_test.dart",
        "test/native_child_conversation_paging_test.dart",
        "test/agent_conversation_image_attachments_test.dart",
        "test/agent_conversation_local_read_only_test.dart",
        "test/agent_conversation_message_display_test.dart",
        "test/agent_conversation_message_merge_test.dart",
        "test/agent_conversation_model_boundary_test.dart",
        "test/agent_conversation_parity_disclosure_test.dart",
        "test/agent_conversation_privacy_projection_test.dart",
        "test/agent_conversation_projection_test.dart",
        "test/agent_conversation_queue_failure_cancel_test.dart",
        "test/agent_conversation_runtime_settings_test.dart",
        "test/agent_conversation_timeline_test.dart",
        "test/agent_conversation_transport_error_test.dart",
        "test/conversation_runtime_result_policy_test.dart",
        "test/conversation_failure_attribution_test.dart",
        "test/group_assistant_name_control_test.dart",
        "test/conversation_browse_catalog_ensure_test.dart",
        "test/conversation_catalog_refresh_intent_test.dart",
        "test/conversation_selection_loading_test.dart",
        "test/agent_conversation_search_index_test.dart",
        "test/agent_conversation_search_palette_test.dart",
        "test/destination_search_ranking_test.dart",
        "test/agent_conversation_semantic_test.dart",
        "test/agent_conversation_send_availability_copy_test.dart",
        "test/agent_conversation_send_failure_projection_test.dart",
        "test/agent_conversation_sidebar_test.dart",
        "test/agent_conversation_tab_activity_test.dart",
        "test/client_conversation_archive_bindings_test.dart",
        "test/client_conversation_recent_participants_test.dart",
        "test/client_conversation_controller_test.dart",
        "test/client_conversation_service_test.dart",
        "test/canonical_conversation_paging_test.dart",
        "test/canonical_conversation_paging_surface_test.dart",
        "test/client_memory_diagnostic_journal_test.dart",
        "test/client_memory_diagnostic_log_test.dart",
        "test/canonical_group_conversation_projection_test.dart",
        "test/canonical_group_roster_visibility_test.dart",
        "test/group_native_session_membership_test.dart",
        "test/group_native_session_sidebar_test.dart",
        "test/canonical_group_assistant_surface_test.dart",
        "test/canonical_group_live_turn_test.dart",
        "test/canonical_group_strategy_mode_test.dart",
        "test/conversation_attachment_flow_test.dart",
        "test/conversation_execution_observer_test.dart",
        "test/conversation_execution_projection_test.dart",
        "test/execution_process/execution_document_test.dart",
        "test/execution_process/conversation_execution_viewer_test.dart",
        "test/execution_process/execution_viewer_visual_test.dart",
        "test/messaging/conversation_reply_surface_test.dart",
        "test/conversation_presentation_signals_test.dart",
        "test/canonical_conversation_activity_echo_test.dart",
        "test/conversation_refresh_policy_test.dart",
        "test/conversation_session_index_test.dart",
        "test/conversation_session_readback_test.dart",
        "test/conversation_turn_process_state_test.dart",
        "test/conversation_working_directory_fallback_test.dart",
        "test/conversation_state_holder_test.dart",
        "test/cursor_ide_cli_handoff_test.dart",
        "test/lico_plan_document_panel_test.dart",
        "test/messaging/messaging_bubble_edge_glow_test.dart",
        "test/messaging/messaging_composer_strategy_test.dart",
        "test/messaging/messaging_contact_list_test.dart",
        "test/messaging/messaging_conversation_switcher_test.dart",
        "test/messaging/messaging_conversation_overlay_glass_test.dart",
        "test/messaging/messaging_details_panel_test.dart",
        "test/messaging/messaging_glass_option_card_test.dart",
        "test/messaging/messaging_image_attachment_test.dart",
        "test/messaging/messaging_participant_flow_test.dart",
        "test/messaging/messaging_sidebar_surface_test.dart",
        "test/messaging/messaging_user_bubble_glass_test.dart",
        "test/messaging/messaging_workspace_selection_test.dart",
        "test/messaging_notification_center_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.history-loading",
      kind: "flutter-feature",
      summary: "Native conversation history listing, streaming, and pagination",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/history_loading_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/history_loading_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.filtering",
      kind: "flutter-feature",
      summary: "Visible conversation filtering and provider wrapper projection",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/filtering_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/filtering_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.structured-events",
      kind: "flutter-feature",
      summary: "Structured event normalization, bounds, identity, and redaction",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/structured_event_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/structured_event_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.dispatch-resume",
      kind: "flutter-feature",
      summary: "Conversation dispatch, exact resume, streaming, steer, and cancel",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/dispatch_resume_scenarios.dart",
        "apps/desktop/test/native_persistent_runtime_test.dart",
        "apps/desktop/test/agent_conversation_reattachment_test.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/dispatch_resume_scenarios.dart",
        "test/native_persistent_runtime_test.dart",
        "test/agent_conversation_reattachment_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.scenario.snapshots",
      kind: "flutter-feature",
      summary: "Conversation snapshot collection and local archive job lifecycle",
      inputs: [
        "apps/desktop/test/fixtures/agent_conversation_service/snapshot_scenarios.dart",
      ],
      command: flutterTests([
        "test/fixtures/agent_conversation_service/snapshot_scenarios.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.follow-up-queue",
      kind: "flutter-feature",
      summary: "Bounded FIFO follow-up turns with exact native-session rebinding",
      inputs: [
        "apps/desktop/lib/src/application/features/agents/conversation/conversation_turn_queue.dart",
        "apps/desktop/test/conversation_turn_queue_test.dart",
      ],
      command: flutterTests([
        "test/conversation_turn_queue_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.archive-selection",
      kind: "flutter-feature",
      summary: "All-conversation and exact-keyword local backup selection dialog",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/conversation_archive_dialog.dart",
        "apps/desktop/test/conversation_archive_dialog_test.dart",
      ],
      command: flutterTests([
        "test/conversation_archive_dialog_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-dispatcher",
      kind: "flutter-feature",
      summary: "Thin message block facade and kind/layout presenter dispatch",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/dispatcher.dart",
        "apps/desktop/test/agent_conversation_message_blocks/dispatcher_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/dispatcher_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-disclosures",
      kind: "flutter-feature",
      summary: "Message body splitting, recommended-plugin details, metadata details, and event detail rendering",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/disclosures.dart",
        "apps/desktop/test/agent_conversation_message_blocks/disclosures_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/disclosures_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-roles",
      kind: "flutter-feature",
      summary: "User bubble and assistant document/bubble role presentations",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/role_blocks.dart",
        "apps/desktop/test/agent_conversation_message_blocks/role_blocks_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/role_blocks_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.message-blocks-subagent",
      kind: "flutter-feature",
      summary: "Subagent preview, expansion state, and child message rendering",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_message_blocks/subagent.dart",
        "apps/desktop/test/agent_conversation_message_blocks/subagent_test.dart",
        "apps/desktop/test/agent_conversation_message_blocks/message_blocks_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_message_blocks/subagent_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-composition",
      kind: "flutter-feature",
      summary: "Thin pane facade with message, send-gate, header, and composer composition",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/composition.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_controls.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_presentation.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_workspace.dart",
        "apps/desktop/test/lico_activity_animations_test.dart",
        "apps/desktop/test/agent_conversation_pane/composition_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/lico_activity_animations_test.dart",
        "test/agent_conversation_pane/composition_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-actions",
      kind: "flutter-feature",
      summary: "Pane empty selection, new, archive, and mobile composer surfaces",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/actions.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_controls.dart",
        "apps/desktop/test/agent_conversation_pane/actions_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_pane/actions_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-resize",
      kind: "flutter-feature",
      summary: "Conversation history split bounds and reusable edge drag handling",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/resize.dart",
        "apps/desktop/test/agent_conversation_pane/resize_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_pane/resize_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.pane-header",
      kind: "flutter-feature",
      summary: "Conversation identity, parity, orchestration, OpenCode status, and sidebar controls",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_connection_chips.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane/header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_controls.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/agent_conversation_pane_presentation.dart",
        "apps/desktop/test/agent_conversation_pane/header_test.dart",
        "apps/desktop/test/agent_conversation_pane/pane_test_harness.dart",
      ],
      command: flutterTests([
        "test/agent_conversation_pane/header_test.dart",
      ]),
    }),
  defineModule({
      id: "flutter.feature.agent-conversations.history-session",
      kind: "flutter-feature",
      summary: "Conversation history session models, search, header, list, and panel composition",
      inputs: [
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_header.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_list.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_models.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_panel.dart",
        "apps/desktop/lib/src/frontend/features/agents/ui/history_session_search.dart",
        "apps/desktop/test/history_session_component_boundary_test.dart",
        "apps/desktop/test/history_session_display_title_test.dart",
        "apps/desktop/test/history_session_panel_test.dart",
      ],
      command: flutterTests([
        "test/history_session_component_boundary_test.dart",
        "test/history_session_display_title_test.dart",
        "test/history_session_panel_test.dart",
      ]),
    }),
]);
