//! The single authority for what every LicoUp Agent adapter program shares.
//!
//! An Agent adapter program — the host's packaged driver for one Agent, and
//! after the crate split that Agent's own `licoup-agent-<agent>` crate — shares
//! exactly this vocabulary with its siblings and nothing of any one Agent's
//! protocol: the byte-line ingress contract every parser implements
//! ([`adapters::NativeLineParser`]), the adapter declaration each parser
//! reports ([`adapters::AdapterContract`]), the closed transition vocabulary
//! and its arrival-ordered reducer ([`Transition`], [`LifecycleStage`],
//! [`TransitionReducer`]), the delta/cumulative text reconciliation
//! ([`TextForm`], [`TextReconciler`]), the process-local type-erased driver
//! registry ([`adapters::driver_registry`]), the registry lookup and
//! dispatch-time admission ([`registry`]), the recorded-transcript replay
//! harness ([`replay`]), the privacy-minimal skill-call projection
//! ([`skill_invocation_projection`]), and the parser lifecycle state machine
//! this crate declares in `resources/state-machines/parser-lifecycle.json` and
//! compiles through `licoup_state_machine_codegen` in `build.rs`.
//!
//! No Agent's protocol is here. The thirteen parsers that classify one Agent's
//! vendor frames, the replay arm that drives each of them, the adapter
//! selection that maps an agent id to its parser, and the thirteen-entry
//! packaged inventory are all composed *above* this crate and reach it through
//! [`port::AdapterParserSet`], the port this SDK declares and composition
//! injects. There is no reference from this crate into `licoup-native` and no
//! vendor frame, vendor field name or vendor protocol name in it.
//!
//! Visibility in this crate is `pub` because the trees that consume it are one
//! crate away — `licoup-native` today, the driver and per-Agent crates after
//! the split. The re-exported vocabulary above is `pub` permanently: it is the
//! extension contract. The remaining items under [`adapters`] and [`replay`]
//! are also `pub` for the duration of the extraction, because the per-Agent
//! parser trees that name them are still in `licoup-native`; they narrow to
//! what an adapter program actually needs once those trees have moved.

pub mod adapters;
mod lifecycle;
pub mod port;
mod reconciliation;
pub mod registry;
pub mod replay;
pub mod serve;
pub mod skill_invocation_projection;

pub use lifecycle::{LifecycleStage, Transition, TransitionReducer};
pub use reconciliation::{TextForm, TextReconciler};

/// The state machines this crate declares, generated by `build.rs` from
/// `resources/state-machines/`.
pub(crate) mod state_machines {
    include!(concat!(env!("OUT_DIR"), "/state_machines.rs"));
}

#[cfg(test)]
mod tests;
