// @generated by schemas/client_bridge/conversation.json#continuousAssistant; do not edit.
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ContinuityCapabilitySupport {
    #[serde(rename = "supported")]
    Supported,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "unverified")]
    Unverified,
    #[serde(rename = "temporarily-unavailable")]
    TemporarilyUnavailable,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ContinuityFailureCode {
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "stale_revision")]
    StaleRevision,
    #[serde(rename = "designation_changed")]
    DesignationChanged,
    #[serde(rename = "scope_denied")]
    ScopeDenied,
    #[serde(rename = "source_unavailable")]
    SourceUnavailable,
    #[serde(rename = "source_revoked")]
    SourceRevoked,
    #[serde(rename = "agreement_conflict")]
    AgreementConflict,
    #[serde(rename = "invalid_span")]
    InvalidSpan,
    #[serde(rename = "idempotency_conflict")]
    IdempotencyConflict,
    #[serde(rename = "qualification_unknown")]
    QualificationUnknown,
    #[serde(rename = "qualification_stale")]
    QualificationStale,
    #[serde(rename = "budget_exhausted")]
    BudgetExhausted,
    #[serde(rename = "unsupported_capability")]
    UnsupportedCapability,
    #[serde(rename = "native_binding_lost")]
    NativeBindingLost,
    #[serde(rename = "native_isolation_unverified")]
    NativeIsolationUnverified,
    #[serde(rename = "writer_busy")]
    WriterBusy,
    #[serde(rename = "reconciliation_required")]
    ReconciliationRequired,
    #[serde(rename = "approval_required")]
    ApprovalRequired,
    #[serde(rename = "identity_conflict")]
    IdentityConflict,
    #[serde(rename = "premature_closure")]
    PrematureClosure,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ContinuityFailureStage {
    #[serde(rename = "continuity/parse")]
    ContinuityParse,
    #[serde(rename = "continuity/admission")]
    ContinuityAdmission,
    #[serde(rename = "continuity/commit")]
    ContinuityCommit,
    #[serde(rename = "continuity/effects")]
    ContinuityEffects,
    #[serde(rename = "continuity/native")]
    ContinuityNative,
    #[serde(rename = "continuity/qualification")]
    ContinuityQualification,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ContinuityEffectClass {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ContinuityRecoveryClass {
    #[serde(rename = "correct_request")]
    CorrectRequest,
    #[serde(rename = "recompute_proposal")]
    RecomputeProposal,
    #[serde(rename = "reconcile_effects")]
    ReconcileEffects,
    #[serde(rename = "review_or_wait")]
    ReviewOrWait,
    #[serde(rename = "obtain_approval")]
    ObtainApproval,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ContinuityDecisionLayer {
    #[serde(rename = "semantic-proposal")]
    SemanticProposal,
    #[serde(rename = "admission")]
    Admission,
    #[serde(rename = "effects")]
    Effects,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ContinuityNativeCapabilitySnapshot {
    #[serde(rename = "exactResume")]
    pub exact_resume: ContinuityCapabilitySupport,
    pub fork: ContinuityCapabilitySupport,
    pub compact: ContinuityCapabilitySupport,
    pub steer: ContinuityCapabilitySupport,
    pub cancel: ContinuityCapabilitySupport,
    pub tools: ContinuityCapabilitySupport,
    #[serde(rename = "isolatedContext")]
    pub isolated_context: ContinuityCapabilitySupport,
    #[serde(rename = "parallelContexts")]
    pub parallel_contexts: ContinuityCapabilitySupport,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ContinuityFailure {
    pub code: ContinuityFailureCode,
    pub stage: ContinuityFailureStage,
    pub recovery: ContinuityRecoveryClass,
    #[serde(rename = "effectClass")]
    pub effect_class: ContinuityEffectClass,
    #[serde(rename = "decisionLayer")]
    pub decision_layer: ContinuityDecisionLayer,
    pub retryable: bool,
}
