import 'package:flutter_client/src/contracts/agent_usage_models.dart';

/// Returns the semantic placeholder allowances shown before an agent's first
/// usage refresh completes.
List<AgentUsageAllowance> defaultAllowancesFor(String target) {
  return switch (target) {
    'claude-code' => const [
      AgentUsageAllowance(
        kind: 'claude-weekly-limit',
        label: 'Claude weekly limit',
        provider: 'Claude',
        period: 'week',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh the Claude quota.',
      ),
    ],
    'codex' => const [
      AgentUsageAllowance(
        kind: 'chatgpt-weekly-limit',
        label: 'ChatGPT weekly limit',
        provider: 'ChatGPT',
        period: 'week',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh the ChatGPT quota.',
      ),
      AgentUsageAllowance(
        kind: 'chatgpt-limit-reset-credits',
        label: 'ChatGPT limit reset credits',
        provider: 'ChatGPT',
        period: 'reset-credits',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh ChatGPT limit reset credits.',
      ),
    ],
    'antigravity' => const [
      AgentUsageAllowance(
        kind: 'antigravity-gemini-5h-limit',
        label: 'Gemini 5-hour limit',
        provider: 'Gemini',
        period: 'session',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh the Gemini 5-hour quota.',
      ),
      AgentUsageAllowance(
        kind: 'antigravity-gemini-weekly-limit',
        label: 'Gemini weekly limit',
        provider: 'Gemini',
        period: 'week',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh the Gemini quota.',
      ),
      AgentUsageAllowance(
        kind: 'antigravity-claude-gpt-5h-limit',
        label: 'Claude/GPT 5-hour limit',
        provider: 'Claude/GPT',
        period: 'session',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh the Claude/GPT 5-hour quota.',
      ),
      AgentUsageAllowance(
        kind: 'antigravity-claude-gpt-weekly-limit',
        label: 'Claude/GPT weekly limit',
        provider: 'Claude/GPT',
        period: 'week',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh the Antigravity quota.',
      ),
    ],
    'kilo-code' => const [
      AgentUsageAllowance(
        kind: 'kilo-pass-limit',
        label: 'Kilo Pass',
        provider: 'Kilo Pass',
        period: 'month',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh Kilo Pass.',
      ),
      AgentUsageAllowance(
        kind: 'kilo-recharge-credits',
        label: 'Recharge credits',
        provider: 'Kilo',
        period: 'balance',
        status: 'unavailable',
        value: '',
        unit: 'credits',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh Kilo recharge credits.',
      ),
    ],
    'opencode' => const [
      AgentUsageAllowance(
        kind: 'model-api-balance',
        label: 'Model API balance',
        provider: 'OpenCode',
        period: 'balance',
        status: 'unavailable',
        value: '',
        unit: '',
        source: 'lico-arc-pending',
        message: 'Run usage scan to refresh the OpenCode model balance.',
      ),
    ],
    _ => const [],
  };
}
