import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const read = (path) => readFileSync(path, "utf8");
const readJson = (path) => JSON.parse(read(path));

const extractActionCatalog = () => {
  const source = read(
    "crates/lico-client-native/src/ffi/secure_mesh_mobile_ffi/action_catalog.rs",
  );
  const begin = source.indexOf(
    "pub const MOBILE_RELAY_NATIVE_ACTIONS: &[&str] = &[",
  );
  const finish = source.indexOf("];", begin);
  assert.notEqual(begin, -1);
  assert.notEqual(finish, -1);
  return [...source.slice(begin, finish).matchAll(/\"([^\"]+)\"/g)].map(
    (match) => match[1],
  );
};

const nativeSecureMeshActions = extractActionCatalog().filter((action) =>
  action.startsWith("secure_mesh."),
);

const removedDtoPaths = [
  "apps/desktop/lib/src/contracts/secure_mesh_capability_models.dart",
  "apps/desktop/lib/src/contracts/secure_mesh_kt_models.dart",
  "apps/desktop/lib/src/contracts/secure_mesh_mls_models.dart",
  "apps/desktop/lib/src/contracts/secure_mesh_file_sync_models.dart",
  "apps/desktop/lib/src/contracts/secure_mesh_skill_sync_models.dart",
  "apps/desktop/lib/src/contracts/secure_mesh_approval_models.dart",
];

test("secure-mesh family stays active and keeps schema identity", () => {
  const schema = readJson("schemas/client_bridge/secure_mesh.json");
  const manifest = readJson("schemas/client_bridge/manifest.json");
  const family = manifest.families.find((item) => item.id === "secure_mesh");

  assert.ok(family);
  assert.equal(family.status, "active");
  assert.equal(family.schema, "schemas/client_bridge/secure_mesh.json");
  assert.equal(
    family.rustOutput,
    "crates/lico-client-native/src/ffi/generated/secure_mesh.rs",
  );
  assert.equal(
    family.dartOutput,
    "apps/desktop/lib/src/contracts/generated/secure_mesh.g.dart",
  );
  assert.deepEqual(schema.forbiddenFields, [
    "privateKey",
    "privateKeyMaterial",
    "secret",
    "seed",
    "token",
    "credential",
    "absolutePath",
  ]);
  assert.equal(new Set(schema.actions).size, schema.actions.length);
});

test("secure-mesh schema actions match canonical native action catalog", () => {
  const schema = readJson("schemas/client_bridge/secure_mesh.json");
  assert.deepEqual([...schema.actions].sort(), [...nativeSecureMeshActions].sort());
});

test("secure-mesh contract artifacts expose generated symbols and boundaries", () => {
  const schema = readJson("schemas/client_bridge/secure_mesh.json");
  const rust = read("crates/lico-client-native/src/ffi/generated/secure_mesh.rs");
  const dart = read("apps/desktop/lib/src/contracts/generated/secure_mesh.g.dart");
  const dispatchRouter = read(
    "crates/lico-client-native/src/ffi/secure_mesh_mobile_ffi/dispatch_router.rs",
  );

  for (const symbol of [
    "SecureMeshAction",
    "SecureMeshRequest",
    "SecureMeshResult",
    "SecureMeshFailure",
    "SecureMeshCapabilityProjection",
    "SecureMeshSelectedCustody",
    "SecureMeshMlsRequest",
    "SecureMeshKtRequest",
    "SecureMeshApprovalRequest",
    "SecureMeshFileSyncTransfer",
    "SecureMeshSkillSyncTransfer",
    "dispatch_request",
  ]) {
    assert.match(rust + "\n" + dart + "\n" + dispatchRouter, new RegExp(symbol));
  }

  assert.ok(rust.includes("@generated by schemas/client_bridge/secure_mesh.json"));
  assert.ok(
    dart.includes("@generated by schemas/client_bridge/secure_mesh.json") ||
      dart.includes("// @generated by schemas/client_bridge/secure_mesh.json"),
  );

  for (const field of schema.forbiddenFields) {
    assert.ok(
      rust.includes(`\"${field}\"`) ||
        rust.includes(`'${field}'`) ||
        dart.includes(`\"${field}\"`) ||
        dart.includes(`'${field}'`),
      `secure mesh generated contract should list forbidden field ${field}`,
    );
  }

  for (const removed of removedDtoPaths) {
    assert.ok(
      !existsSync(removed),
      `legacy DTO file should be removed: ${removed}`,
    );
  }

  for (const action of schema.actions) {
    assert.ok(
      rust.includes(`\"${action}\"`) || dart.includes(`'${action}'`),
      `generated Secure Mesh action missing: ${action}`,
    );
  }
});
