use crate::platform::acp_session_transport::{
    APPROVAL_POLL_INTERVAL, APPROVAL_WAIT_TIMEOUT, CONTROL_QUEUE_CAPACITY, MAX_PARKED_PERMISSIONS,
    MAX_POOLED_TRANSPORTS, MAX_TRACKED_SESSIONS, PROCESS_POLL_INTERVAL,
};

#[test]
fn runtime_resource_and_wait_bounds_remain_finite() {
    assert!(PROCESS_POLL_INTERVAL < APPROVAL_WAIT_TIMEOUT);
    assert!(APPROVAL_POLL_INTERVAL < APPROVAL_WAIT_TIMEOUT);
    assert!(CONTROL_QUEUE_CAPACITY > 0);
    assert!(MAX_POOLED_TRANSPORTS > 0);
    assert!(MAX_TRACKED_SESSIONS >= MAX_POOLED_TRANSPORTS);
    assert!(MAX_PARKED_PERMISSIONS > 0);
}
