export function fixtureDigest(character) {
  return `sha256:${character.repeat(64)}`;
}

export function fixtureMacos({
  sourceDigest,
  artifactDigest,
  productVersion,
  generatedAt,
  closureChallengeDigest,
  invocationNonceDigest,
}) {
  return {
    schemaVersion: "licolite.secure-mesh.macos-adaptive-capabilities-receipt.v3",
    verifier: "tools/scripts/client-secure-mesh-macos-capabilities.mjs",
    generatedAt,
    closureChallengeDigest,
    invocationNonceDigest,
    ok: true,
    platform: "macos",
    redacted: true,
    reportLeakScan: true,
    rawRuntimeOutputIncluded: false,
    rawPrivateMaterialIncluded: false,
    sourceStateDigest: sourceDigest,
    dependencies: [{
      id: "macos-user-presence-proof",
      ref: "build/reports/secure-mesh-macos-keychain-user-presence-proof.json",
      digest: fixtureDigest("f"),
    }],
    receipts: [{
      targetId: "macos-arm64",
      productVersion,
      buildNumber: 7,
      artifactKind: "macos-app-bundle",
      artifactDigest,
      runtimeExecutableDigest: fixtureDigest("4"),
      signatureKind: "local-identity-codesign",
      platformLocalSignatureReady: true,
      hardenedRuntime: true,
      nestedCodeMinimalEntitlements: true,
      entitlementsMatch: true,
      entitlementsDigest: fixtureDigest("e"),
      installedArtifactMatched: true,
      installReceiptReady: true,
      launchReady: true,
      newProcessReady: true,
      startedAfterInvocation: true,
      executableWithinInstalledBundle: true,
      closureChallengeBound: true,
      invocationNonceBound: true,
      stableProcessWindowReady: true,
      postLaunchArtifactStable: true,
      smokeReady: true,
      capabilityProofReady: true,
    }],
  };
}

export function fixtureAndroid({
  sourceDigest,
  artifactDigest,
  productVersion,
  generatedAt,
  closureChallengeDigest,
  invocationNonceDigest,
}) {
  return {
    schemaVersion: "licolite.secure-mesh.android-physical-install-launch-report.v3",
    verifier: "tools/scripts/client-android-physical-install-launch.mjs",
    generatedAt,
    closureChallengeDigest,
    invocationNonceDigest,
    ok: true,
    targetId: "android-arm64",
    productVersion,
    buildNumber: 7,
    platform: "android",
    physicalDevice: true,
    packageName: "com.liko.arc",
    redacted: true,
    reportLeakScan: true,
    rawPrivateMaterialIncluded: false,
    rawPlaintextIncluded: false,
    apk: { sha256: artifactDigest, nativeSecureMeshAbi: "arm64-v8a" },
    apkBinaryFacts: {
      packageName: "com.liko.arc",
      versionCode: "7",
      versionName: productVersion,
      debuggable: false,
      abis: ["arm64-v8a"],
      launchableActivity: "com.liko.arc.MainActivity",
      signerCount: 1,
      signatureSchemes: ["v2"],
      zipAligned: true,
      nativeSecureMeshLibrary: {
        path: "lib/arm64-v8a/liblico_client_native.so",
        contentDigest: fixtureDigest("d"),
        size: 4096,
        compressedSize: 4096,
        crc32: "12345678",
        compression: "stored",
        regular: true,
        unique: true,
        zipEntryCount: 10,
      },
    },
    sourceBuild: { sourceStateDigest: sourceDigest },
    evidenceBinding: {
      sourceStateDigest: sourceDigest,
      apkSha256: artifactDigest,
      signatureMatchedBuildManifest: true,
    },
    signing: {
      signingKind: "local-install-keystore",
      signatureVerified: true,
      signerIdentityVerified: true,
      signingPolicySatisfied: true,
      singleSigner: true,
      signatureMatchedBuildManifest: true,
    },
    install: {
      attempted: true,
      installedViaVerifier: true,
      packagePresentAfterInstall: true,
      installedArtifactMatched: true,
    },
    launch: {
      attempted: true,
      launchedViaVerifier: true,
      runtimeStatusFreshAfterLaunch: true,
    },
    summary: {
      installReady: true,
      launchReady: true,
      runtimeStatusReady: true,
      nativeRuntimeReady: true,
      androidCustodyReady: true,
      adaptiveAuthorizationReady: true,
      evidenceBindingReady: true,
      closureChallengeBound: true,
      invocationNonceBound: true,
    },
  };
}

export function fixtureLinux({
  sourceDigest,
  artifactDigest,
  productVersion,
  generatedAt,
  closureChallengeDigest,
  invocationNonceDigest,
}) {
  return {
    schema: "licolite.secure-mesh.linux-vm-package-receipt",
    schemaVersion: 2,
    producer: "linux-vm-package-receipt",
    generatedAt,
    closureChallengeDigest,
    invocationNonceDigest,
    productVersion,
    buildNumber: 7,
    ok: true,
    target: "ubuntu-linux-arm64",
    sourceBinding: {
      sourceStateDigest: sourceDigest,
      archiveDigest: artifactDigest,
      nativeClientDigest: fixtureDigest("4"),
    },
    package: { validationSignature: true, signatureVerified: true },
    summary: {
      installReceiptReady: true,
      sessionLaunchReady: true,
      smokeReady: true,
      privacyReady: true,
    },
  };
}
