use serde_json::Value;

pub(in crate::domain::mobile_relay) struct LocalEndpointState {
    pub(in crate::domain::mobile_relay) endpoint_id: String,
    pub(in crate::domain::mobile_relay) endpoint_kind: String,
    pub(in crate::domain::mobile_relay) private_key: String,
    pub(in crate::domain::mobile_relay) public_key: String,
    pub(in crate::domain::mobile_relay) signing_key: String,
    pub(in crate::domain::mobile_relay) signing_public_key: String,
    pub(in crate::domain::mobile_relay) rotation_epoch: u64,
    pub(in crate::domain::mobile_relay) mailbox_rotation_epoch: u64,
    pub(in crate::domain::mobile_relay) prekey_publication_version: u64,
    pub(in crate::domain::mobile_relay) signed_prekey_id: String,
    pub(in crate::domain::mobile_relay) signed_prekey_private_key: String,
    pub(in crate::domain::mobile_relay) signed_prekey_public_key: String,
    pub(in crate::domain::mobile_relay) signed_prekey_signature: String,
    pub(in crate::domain::mobile_relay) signed_prekey_created_at: String,
    pub(in crate::domain::mobile_relay) signed_prekey_expires_at: String,
    pub(in crate::domain::mobile_relay) one_time_prekey_id: String,
    pub(in crate::domain::mobile_relay) one_time_prekey_private_key: String,
    pub(in crate::domain::mobile_relay) one_time_prekey_public_key: String,
    pub(in crate::domain::mobile_relay) one_time_prekey_signature: String,
    pub(in crate::domain::mobile_relay) one_time_prekey_created_at: String,
    pub(in crate::domain::mobile_relay) one_time_prekey_expires_at: String,
    pub(in crate::domain::mobile_relay) one_time_mlkem1024_prekey_id: String,
    pub(in crate::domain::mobile_relay) one_time_mlkem1024_prekey_seed: String,
    pub(in crate::domain::mobile_relay) one_time_mlkem1024_prekey_public_key: String,
    pub(in crate::domain::mobile_relay) one_time_mlkem1024_prekey_signature: String,
    pub(in crate::domain::mobile_relay) one_time_mlkem1024_prekey_created_at: String,
    pub(in crate::domain::mobile_relay) one_time_mlkem1024_prekey_expires_at: String,
    pub(in crate::domain::mobile_relay) fingerprint: String,
    pub(in crate::domain::mobile_relay) session_id: String,
    pub(in crate::domain::mobile_relay) pending_pairwise_intro: Option<Value>,
    pub(in crate::domain::mobile_relay) pairwise_accepted: Option<Value>,
    pub(in crate::domain::mobile_relay) pairwise_finished: Option<Value>,
    pub(in crate::domain::mobile_relay) key_transparency_response: Option<Value>,
}
