//! The host side of Agent execution: the work-context seam, the adapter
//! registry and the adapter execution that drives them, the ACP session
//! transport, and the local service control plane.
//!
//! What this crate owns:
//!
//! * the work-context seam — the binding contract, the adapter transport, the
//!   production host driver and the C01 effect port over them, in [`effect_port`],
//!   [`host_driver`], [`port`] and [`transport`];
//! * the host-side adapter registry and adapter execution, in
//!   [`runtime_adapters`]: which packaged adapters exist, what each of them
//!   declares, how a turn is admitted and dispatched to one of them, how the
//!   Agent's own report is normalized into this host's execution vocabulary,
//!   and the Subagent MCP mesh that reaches the same registry.
//! * the ACP session transport, in [`acp_driver_runtime`] and
//!   [`acp_session_transport`]: the shared ACP frame dialect's two protocol
//!   reducers and their machines, bounded process I/O, capability negotiation,
//!   the service-neutral process runtime, the driver-scoped persistent session
//!   pool with its approval parking and control, and the recorded-transcript
//!   replay arms for both reducers in `acp_driver_runtime::replay`;
//! * the local service control plane, in [`local_service`]: the target-neutral
//!   bounded HTTP/SSE transport, the detached-service lifecycle, and the
//!   active-turn and endpoint-lease registry the host's serve lanes reach;
//! * the thirteen Agent declarations as data, `resources/agent-conversation-drivers.json`,
//!   `resources/agent-native-capabilities.json` and `resources/agent-conversation-readiness.json`,
//!   embedded by [`runtime_adapters::registry`] because they are the registry's
//!   own input, and the two ACP session-protocol machines,
//!   `resources/state-machines/copilot.json` and
//!   `resources/state-machines/hermes.json`, compiled by `build.rs` for the
//!   reducers that replay them.
//!
//! What it does not own: any Agent's protocol. The per-Agent protocol adapter,
//! its driver execution and its frame parser arrive through the ports declared
//! in [`port`], in [`acp_driver_runtime::parser_port`] and in
//! `licoup-agent-adapter-sdk::port`; the composition above this crate supplies
//! them — `licoup-native` while the Agent crates do not exist,
//! `licoup-agent-<agent>` once they do — and the host's own lane reach arrives
//! the same way. The ACP dialogs this crate does hold are shared: the ACP
//! profile Copilot, OpenCode and Kilo Code all speak and the persistent ACP
//! profile Hermes speaks are framing and session semantics, not any one Agent's
//! protocol, and every per-Agent fact they read arrives through the port. No
//! Agent's protocol is implemented in this crate and nothing here is a vendor
//! branch.
//!
//! One seam here is a feature rather than `cfg(test)`: `test-support` carries
//! the ACP frame dialect a build with no composition reads, the reducer
//! vocabulary the host's Hermes suites drive, and the replay arms. It is a
//! feature because the host's own test build links this crate as a dependency,
//! and `cfg(test)` is false for a dependency — so a `cfg(test)` seam is compiled
//! out of exactly the build that calls it. The hermetic work-context fixtures
//! the host's integration suites drive are still host test material and stay
//! with the host.

use licoup_agent_runtime::work_context::{
    HermeticProtocol, NativeWorkContextPort, UnavailableNativeWorkContext, WorkContextConfig,
    WorkContextRuntime, unavailable_work_context_port, work_context_runtime,
};

pub mod acp_driver_runtime;
pub mod acp_session_transport;
pub mod local_service;

// The ACP transport's vendor-protocol port: the frame dialect one driver's
// sessions are read through, and the approval authority its park-and-inbox
// registration evaluates against. The composition above this crate answers
// both, so the names are reachable from the composition rather than only from
// inside the tree that reads them.
pub use acp_driver_runtime::parser_port::{
    AcpParserRegistration, ProtocolClientRequest, ProtocolPermissionRequest,
};
pub use acp_session_transport::approval_port::{ApprovalPort, ApprovalEvaluate};

/// The ACP frame dialect a build with no composition reads.
///
/// It is behind `test-support` rather than `cfg(test)` because the host's own
/// suites drive the moved reducers and the host links this crate as a
/// dependency, so a `cfg(test)` dialect is compiled out of the build that calls
/// it. The reducers call [`test_support::ensure`] at construction, so a suite
/// cannot forget it and silently assert against refusals.
#[cfg(any(test, feature = "test-support"))]
pub mod test_support;

/// The state machines this crate declares, generated by `build.rs` from
/// `resources/state-machines/`.
pub(crate) mod state_machines {
    include!(concat!(env!("OUT_DIR"), "/state_machines.rs"));
}

mod effect_port;
mod host_driver;
mod port;
pub mod runtime_adapters;
mod transport;


pub use effect_port::{
    AgentProfileSource, CancelOutcome, ControlDelivery, ControlDisposition, DeliveryOutcome,
    EffectBridge, EffectCapabilities, EffectCapability, EffectControl, EffectDelivery,
    EffectDispatch, EffectHandle, EffectInvocation, EffectObservation, EffectOperation,
    EffectRefusal, EffectSessionOwner, EffectState, EffectTurn, EffectUnknownReason,
    ReconcileOutcome, RuntimeAgentProfile, Settlement, SteerOutcome, SubmitOutcome,
    effect_input_text,
};
pub use host_driver::HostDriverTransport;
pub use port::{
    AgentProtocolRegistration, BindProtocol, DriverExecute, DriverExecution, DriverFailure,
    DriverInvocation, LaneDispatch, LaneReach, unverified_snapshot,
};
pub use transport::{
    AdapterCall, AdapterResponse, AdapterTransport, CountingTransport, UnavailableAdapterTransport,
};

pub fn preregistered_work_context_port() -> UnavailableNativeWorkContext {
    unavailable_work_context_port()
}

pub fn boxed_work_context_port() -> Box<dyn NativeWorkContextPort> {
    Box::new(preregistered_work_context_port())
}

/// Test-only hermetic bind. Production attach does not call this.
pub fn bind_host_work_context(
    protocol: HermeticProtocol,
    config: WorkContextConfig,
) -> WorkContextRuntime {
    work_context_runtime(protocol, config)
}

/// Bind one Agent's protocol adapter, built by the composition, into the
/// work-context runtime.
///
/// This is the seam's whole binding step: the adapter that answers for one
/// Agent is built on that Agent's own side of the port and handed in already
/// wrapped around the host's transport, so the seam never names it.
pub fn bind_agent_protocol(
    protocol: AgentProtocolRegistration,
    config: WorkContextConfig,
    transport: std::sync::Arc<dyn AdapterTransport>,
    store: Option<licoup_conversation::ConversationStore>,
) -> WorkContextRuntime {
    (protocol.bind)(config, store, transport)
}

/// The production bind for one Agent, over the host's own driver transport.
///
/// The composition supplies the Agent's registration and the host's lane reach;
/// the transport itself is the seam's.
pub fn bind_persisted_work_context(
    protocol: AgentProtocolRegistration,
    lane: LaneReach,
    store: licoup_conversation::ConversationStore,
    config: WorkContextConfig,
) -> WorkContextRuntime {
    bind_agent_protocol(
        protocol,
        config,
        std::sync::Arc::new(HostDriverTransport::new(protocol, lane)),
        Some(store),
    )
}
