// @generated by schemas/conversation_protocol/conversation_protocol.schema.json; do not edit.
use serde_json::Value;
use std::path::PathBuf;

pub const CONVERSATION_PROTOCOL_VERSION: &str = "licoup.stdio.v1";
pub const CONVERSATION_PROTOCOL_MAX_FRAME_BYTES: usize = 16777216;
pub const CONVERSATION_PROTOCOL_MAX_RESPONSE_BYTES: usize = 16777216;
pub const CONVERSATION_PROTOCOL_MAX_ID_BYTES: usize = 128;
pub const CONVERSATION_PROTOCOL_MAX_ARGS: usize = 4097;
pub const CONVERSATION_PROTOCOL_MAX_CLIENT_ARGS: usize = 256;
pub const CONVERSATION_PROTOCOL_MAX_ERROR_CODE_BYTES: usize = 64;
pub const CONVERSATION_PROTOCOL_MAX_STDERR_BYTES: usize = 524288;

pub const CONVERSATION_PROTOCOL_METHODS: [&str; 29] = [
    "execute",
    "shutdown",
    "catalog.status",
    "catalog.invalidate",
    "catalog.refresh",
    "catalog.receipt",
    "catalog.purge",
    "catalog.reconnect",
    "catalog.list",
    "catalog.observe",
    "state.get",
    "state.set",
    "agent.conversation.open",
    "agent.conversation.history",
    "agent.conversation.cleanup",
    "agent.conversation.capabilities",
    "agent.conversation.cancel",
    "agent.conversation.steer",
    "agent.conversation.active",
    "agent.conversation.dispatch",
    "agent.conversation.send",
    "agent.conversation.attach",
    "agent.conversation.stream",
    "client.conversation.execute",
    "strategy.execute",
    "targets.scan",
    "targets.add",
    "gateway.credentials.create",
    "gateway.credentials.update",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ConversationProtocolMethod {
    Execute,
    Shutdown,
    CatalogStatus,
    CatalogInvalidate,
    CatalogRefresh,
    CatalogReceipt,
    CatalogPurge,
    CatalogReconnect,
    CatalogList,
    CatalogObserve,
    StateGet,
    StateSet,
    AgentConversationOpen,
    AgentConversationHistory,
    AgentConversationCleanup,
    AgentConversationCapabilities,
    AgentConversationCancel,
    AgentConversationSteer,
    AgentConversationActive,
    AgentConversationDispatch,
    AgentConversationSend,
    AgentConversationAttach,
    AgentConversationStream,
    ClientConversationExecute,
    StrategyExecute,
    TargetsScan,
    TargetsAdd,
    GatewayCredentialsCreate,
    GatewayCredentialsUpdate,
}

impl ConversationProtocolMethod {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Execute => "execute",
            Self::Shutdown => "shutdown",
            Self::CatalogStatus => "catalog.status",
            Self::CatalogInvalidate => "catalog.invalidate",
            Self::CatalogRefresh => "catalog.refresh",
            Self::CatalogReceipt => "catalog.receipt",
            Self::CatalogPurge => "catalog.purge",
            Self::CatalogReconnect => "catalog.reconnect",
            Self::CatalogList => "catalog.list",
            Self::CatalogObserve => "catalog.observe",
            Self::StateGet => "state.get",
            Self::StateSet => "state.set",
            Self::AgentConversationOpen => "agent.conversation.open",
            Self::AgentConversationHistory => "agent.conversation.history",
            Self::AgentConversationCleanup => "agent.conversation.cleanup",
            Self::AgentConversationCapabilities => "agent.conversation.capabilities",
            Self::AgentConversationCancel => "agent.conversation.cancel",
            Self::AgentConversationSteer => "agent.conversation.steer",
            Self::AgentConversationActive => "agent.conversation.active",
            Self::AgentConversationDispatch => "agent.conversation.dispatch",
            Self::AgentConversationSend => "agent.conversation.send",
            Self::AgentConversationAttach => "agent.conversation.attach",
            Self::AgentConversationStream => "agent.conversation.stream",
            Self::ClientConversationExecute => "client.conversation.execute",
            Self::StrategyExecute => "strategy.execute",
            Self::TargetsScan => "targets.scan",
            Self::TargetsAdd => "targets.add",
            Self::GatewayCredentialsCreate => "gateway.credentials.create",
            Self::GatewayCredentialsUpdate => "gateway.credentials.update",
        }
    }

    pub fn from_wire(name: &str) -> Option<Self> {
        match name {
            "execute" => Some(Self::Execute),
            "shutdown" => Some(Self::Shutdown),
            "catalog.status" => Some(Self::CatalogStatus),
            "catalog.invalidate" => Some(Self::CatalogInvalidate),
            "catalog.refresh" => Some(Self::CatalogRefresh),
            "catalog.receipt" => Some(Self::CatalogReceipt),
            "catalog.purge" => Some(Self::CatalogPurge),
            "catalog.reconnect" => Some(Self::CatalogReconnect),
            "catalog.list" => Some(Self::CatalogList),
            "catalog.observe" => Some(Self::CatalogObserve),
            "state.get" => Some(Self::StateGet),
            "state.set" => Some(Self::StateSet),
            "agent.conversation.open" => Some(Self::AgentConversationOpen),
            "agent.conversation.history" => Some(Self::AgentConversationHistory),
            "agent.conversation.cleanup" => Some(Self::AgentConversationCleanup),
            "agent.conversation.capabilities" => Some(Self::AgentConversationCapabilities),
            "agent.conversation.cancel" => Some(Self::AgentConversationCancel),
            "agent.conversation.steer" => Some(Self::AgentConversationSteer),
            "agent.conversation.active" => Some(Self::AgentConversationActive),
            "agent.conversation.dispatch" => Some(Self::AgentConversationDispatch),
            "agent.conversation.send" => Some(Self::AgentConversationSend),
            "agent.conversation.attach" => Some(Self::AgentConversationAttach),
            "agent.conversation.stream" => Some(Self::AgentConversationStream),
            "client.conversation.execute" => Some(Self::ClientConversationExecute),
            "strategy.execute" => Some(Self::StrategyExecute),
            "targets.scan" => Some(Self::TargetsScan),
            "targets.add" => Some(Self::TargetsAdd),
            "gateway.credentials.create" => Some(Self::GatewayCredentialsCreate),
            "gateway.credentials.update" => Some(Self::GatewayCredentialsUpdate),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConversationCommand {
    pub id: String,
    pub workflow_id: String,
    pub method: ConversationProtocolMethod,
    pub params: Value,
    pub args: Option<Vec<String>>,
    pub portable_data_dir: Option<PathBuf>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConversationCommandError {
    pub id: Option<String>,
    pub workflow_id: Option<String>,
    pub code: &'static str,
}

impl ConversationCommand {
    pub fn decode(bytes: &[u8]) -> Result<Self, ConversationCommandError> {
        let value: Value = serde_json::from_slice(bytes).map_err(|_| ConversationCommandError {
            id: None,
            workflow_id: None,
            code: "invalid_json",
        })?;
        let object = value.as_object().ok_or_else(|| ConversationCommandError {
            id: None,
            workflow_id: None,
            code: "invalid_request",
        })?;
        if object.get("protocol").and_then(Value::as_str) != Some(CONVERSATION_PROTOCOL_VERSION) {
            return Err(ConversationCommandError {
                id: None,
                workflow_id: None,
                code: "invalid_protocol",
            });
        }
        let id = object
            .get("id")
            .and_then(Value::as_str)
            .filter(|value| ConversationCommand::valid_identifier(value))
            .map(str::to_string);
        let workflow_id = object
            .get("workflowId")
            .and_then(Value::as_str)
            .filter(|value| ConversationCommand::valid_identifier(value))
            .map(str::to_string);
        let invalid = |code| ConversationCommandError {
            id: id.clone(),
            workflow_id: workflow_id.clone(),
            code,
        };
        let id = id.clone().ok_or_else(|| invalid("invalid_request_id"))?;
        let workflow_id = workflow_id
            .clone()
            .ok_or_else(|| invalid("invalid_workflow_id"))?;
        let method = object
            .get("method")
            .and_then(Value::as_str)
            .and_then(ConversationProtocolMethod::from_wire)
            .ok_or_else(|| invalid("invalid_method"))?;
        let params = object
            .get("params")
            .cloned()
            .unwrap_or_else(|| Value::Object(Default::default()));
        if !params.is_object() {
            return Err(invalid("invalid_params"));
        }
        let args = match method {
            ConversationProtocolMethod::Execute => Some(
                object
                    .get("args")
                    .and_then(Value::as_array)
                    .filter(|args| args.len() <= CONVERSATION_PROTOCOL_MAX_ARGS)
                    .ok_or_else(|| invalid("invalid_args"))?
                    .iter()
                    .map(|value| value.as_str().map(str::to_string))
                    .collect::<Option<Vec<_>>>()
                    .ok_or_else(|| invalid("invalid_args"))?,
            ),
            _ => None,
        };
        let portable_data_dir = match object.get("portableDataDir") {
            None | Some(Value::Null) => None,
            Some(Value::String(value)) if !value.trim().is_empty() => {
                let path = PathBuf::from(value);
                if !path.is_absolute() {
                    return Err(invalid("invalid_portable_data_dir"));
                }
                Some(path)
            }
            _ => return Err(invalid("invalid_portable_data_dir")),
        };
        Ok(Self {
            id,
            workflow_id,
            method,
            params,
            args,
            portable_data_dir,
        })
    }

    pub fn valid_identifier(value: &str) -> bool {
        !value.is_empty()
            && value.len() <= CONVERSATION_PROTOCOL_MAX_ID_BYTES
            && value
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    }

    pub fn frame(
        id: &str,
        workflow_id: &str,
        method: ConversationProtocolMethod,
        params: Value,
    ) -> Value {
        json_frame(
            CONVERSATION_PROTOCOL_VERSION,
            id,
            workflow_id,
            method.as_str(),
            params,
        )
    }
}

fn json_frame(protocol: &str, id: &str, workflow_id: &str, method: &str, params: Value) -> Value {
    let mut object = serde_json::Map::new();
    object.insert("protocol".to_owned(), Value::String(protocol.to_owned()));
    object.insert("id".to_owned(), Value::String(id.to_owned()));
    object.insert(
        "workflowId".to_owned(),
        Value::String(workflow_id.to_owned()),
    );
    object.insert("method".to_owned(), Value::String(method.to_owned()));
    object.insert("params".to_owned(), params);
    Value::Object(object)
}

#[derive(Clone, Debug, PartialEq)]
pub enum ConversationDelta {
    Event {
        id: String,
        workflow_id: String,
        sequence: u64,
        event: Value,
    },
    Terminal {
        id: String,
        workflow_id: String,
        sequence: u64,
        ok: bool,
        result: Option<Value>,
        error: Option<Value>,
    },
}

impl ConversationDelta {
    pub fn event_frame(id: &str, workflow_id: &str, sequence: u64, event: Value) -> Value {
        let mut object = serde_json::Map::new();
        object.insert(
            "protocol".to_owned(),
            Value::String(CONVERSATION_PROTOCOL_VERSION.to_owned()),
        );
        object.insert("id".to_owned(), Value::String(id.to_owned()));
        object.insert(
            "workflowId".to_owned(),
            Value::String(workflow_id.to_owned()),
        );
        object.insert("kind".to_owned(), Value::String("event".to_owned()));
        object.insert("sequence".to_owned(), Value::from(sequence));
        object.insert("event".to_owned(), event);
        Value::Object(object)
    }

    pub fn terminal_success_frame(
        id: &str,
        workflow_id: &str,
        sequence: u64,
        result: Value,
    ) -> Value {
        terminal_frame(id, workflow_id, sequence, true, Some(result), None)
    }

    pub fn terminal_error_frame(id: &str, workflow_id: &str, sequence: u64, error: Value) -> Value {
        terminal_frame(id, workflow_id, sequence, false, None, Some(error))
    }

    pub fn decode(frame: &Value) -> Result<Self, &'static str> {
        let object = frame.as_object().ok_or("invalid_delta")?;
        if object.get("protocol").and_then(Value::as_str) != Some(CONVERSATION_PROTOCOL_VERSION) {
            return Err("invalid_delta");
        }
        let id = object
            .get("id")
            .and_then(Value::as_str)
            .filter(|value| ConversationCommand::valid_identifier(value))
            .ok_or("invalid_delta")?;
        let workflow_id = object
            .get("workflowId")
            .and_then(Value::as_str)
            .filter(|value| ConversationCommand::valid_identifier(value))
            .ok_or("invalid_delta")?;
        let sequence = object
            .get("sequence")
            .and_then(Value::as_u64)
            .filter(|value| *value > 0)
            .ok_or("invalid_delta")?;
        match object.get("kind").and_then(Value::as_str) {
            Some("event") => {
                let event = object.get("event").cloned().ok_or("invalid_delta")?;
                if !event.is_object() {
                    return Err("invalid_delta");
                }
                Ok(Self::Event {
                    id: id.to_owned(),
                    workflow_id: workflow_id.to_owned(),
                    sequence,
                    event,
                })
            }
            Some("terminal") => {
                let ok = object
                    .get("ok")
                    .and_then(Value::as_bool)
                    .ok_or("invalid_delta")?;
                if ok {
                    let result = object.get("result").cloned().ok_or("invalid_delta")?;
                    if !result.is_object() {
                        return Err("invalid_delta");
                    }
                    Ok(Self::Terminal {
                        id: id.to_owned(),
                        workflow_id: workflow_id.to_owned(),
                        sequence,
                        ok: true,
                        result: Some(result),
                        error: None,
                    })
                } else {
                    let error = object.get("error").cloned().ok_or("invalid_delta")?;
                    if !error.is_object() {
                        return Err("invalid_delta");
                    }
                    Ok(Self::Terminal {
                        id: id.to_owned(),
                        workflow_id: workflow_id.to_owned(),
                        sequence,
                        ok: false,
                        result: None,
                        error: Some(error),
                    })
                }
            }
            _ => Err("invalid_delta"),
        }
    }
}

fn terminal_frame(
    id: &str,
    workflow_id: &str,
    sequence: u64,
    ok: bool,
    result: Option<Value>,
    error: Option<Value>,
) -> Value {
    let mut object = serde_json::Map::new();
    object.insert(
        "protocol".to_owned(),
        Value::String(CONVERSATION_PROTOCOL_VERSION.to_owned()),
    );
    object.insert("id".to_owned(), Value::String(id.to_owned()));
    object.insert(
        "workflowId".to_owned(),
        Value::String(workflow_id.to_owned()),
    );
    object.insert("kind".to_owned(), Value::String("terminal".to_owned()));
    object.insert("sequence".to_owned(), Value::from(sequence));
    object.insert("ok".to_owned(), Value::Bool(ok));
    if let Some(result) = result {
        object.insert("result".to_owned(), result);
    }
    if let Some(error) = error {
        object.insert("error".to_owned(), error);
    }
    Value::Object(object)
}
